version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "coverage"
          - "ruff"
          - "mypy"
          - "build"
          - "twine"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/webui"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        dependency-type: "development"