"""Regression tests for the encrypted credential store (Tier 0 item 0.3, Phase B).

Covers:
1. ``_Vault`` -- Fernet at-rest encryption, env-key vs 0600-keyfile resolution,
   loud plaintext fallback when ``cryptography`` is absent, fail-open decrypt for
   legacy/wrong-key reads.
2. ``CredentialStore`` -- in-memory plaintext / on-disk ciphertext round-trip,
   ``confirm_credential`` as the *only* path to ``confirmed=True``, dedup, and
   legacy plaintext files still loading.
3. The ``cred_store_add/get/list/confirm`` MCP tools end-to-end -- the on-disk
   vault holds ciphertext, the audit log never holds the cleartext secret, and
   ``confirmed`` only flips via the deliberate confirm call.
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path
from typing import Any

import pytest
from cryptography.fernet import Fernet

from tools.credential_store import CredentialRecord, CredentialStore, _Vault

_CLEARTEXT = "super-secret-password-42!"
_NTLM = "aad3b435b51404eeaad3b435b51404ee"


def _rec(
    username: str = "admin",
    password: str = _CLEARTEXT,
    ctype: str = "password",
    target_host: str = "10.0.0.50",
    confirmed: bool = False,
) -> CredentialRecord:
    return CredentialRecord(
        timestamp=time.time(),
        source_host="10.0.0.50",
        target_host=target_host,
        username=username,
        password=password,
        credential_type=ctype,
        source_action="test",
        confirmed=confirmed,
    )


# ── 1. _Vault ───────────────────────────────────────────────────────────────


def test_vault_env_key_roundtrip(monkeypatch, tmp_path):
    key = Fernet.generate_key().decode()
    monkeypatch.setenv("AI_NMAP_VAULT_KEY", key)
    v = _Vault(tmp_path)
    assert v.enabled is True
    token = v.encrypt(_CLEARTEXT)
    assert token != _CLEARTEXT
    assert token.startswith("gAAAAA")  # Fernet token prefix
    assert v.decrypt(token) == _CLEARTEXT


def test_vault_keyfile_autogenerated(monkeypatch, tmp_path):
    """The keyfile is auto-generated OUTSIDE the workspace tree (0600), so the
    AI's unrestricted workspace reads can never reach it."""
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    vault_dir = tmp_path / "vault_home"
    monkeypatch.setenv("BREACHPILOT_VAULT_DIR", str(vault_dir))
    store_dir = tmp_path / "workspace"
    v = _Vault(store_dir)
    assert v.enabled is True
    assert (store_dir / ".vault_key").exists() is False  # never in-workspace
    assert v._keyfile.parent == vault_dir
    assert v._keyfile.exists()
    import os as _os

    assert oct(v._keyfile.stat().st_mode & 0o777) == "0o600"
    token = v.encrypt(_CLEARTEXT)
    assert v.decrypt(token) == _CLEARTEXT


def test_vault_key_is_private_before_first_write(monkeypatch, tmp_path):
    """The key is created with private mode before key bytes are written."""
    import os

    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    vault_dir = tmp_path.parent / f"{tmp_path.name}-vault"
    monkeypatch.setenv("BREACHPILOT_VAULT_DIR", str(vault_dir))
    original_write = os.write
    observed_modes: list[int] = []

    def inspect_before_write(fd: int, data: bytes) -> int:
        observed_modes.append(os.fstat(fd).st_mode & 0o777)
        return original_write(fd, data)

    monkeypatch.setattr(os, "write", inspect_before_write)
    vault = _Vault(tmp_path / "workspace")
    assert vault.enabled
    assert observed_modes and all(mode == 0o600 for mode in observed_modes)


def test_vault_key_directory_inside_workspace_fails_closed(monkeypatch, tmp_path):
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    vault_dir = tmp_path / "vault_home"
    monkeypatch.setenv("BREACHPILOT_VAULT_DIR", str(vault_dir))
    store = CredentialStore(tmp_path, workspace_root=tmp_path)
    assert not store.encryption_enabled
    with pytest.raises(RuntimeError, match="refusing plaintext write"):
        store.add(_rec())
    assert not vault_dir.exists()


def test_vault_legacy_in_workspace_keyfile_adopted(monkeypatch, tmp_path):
    """A legacy in-workspace ``.vault_key`` is moved out (not copied) so old
    stores keep decrypting and no key material stays AI-readable."""
    from tools.credential_store import _vault_key_path

    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    vault_dir = tmp_path / "vault_home"
    monkeypatch.setenv("BREACHPILOT_VAULT_DIR", str(vault_dir))
    store_dir = tmp_path / "workspace"
    store_dir.mkdir(parents=True)
    legacy = store_dir / ".vault_key"
    legacy.write_text("legacy-key-material", encoding="utf-8")
    v = _Vault(store_dir)
    assert v._keyfile == _vault_key_path(store_dir)
    assert v._keyfile.exists()
    assert v._keyfile.read_text(encoding="utf-8").strip() == "legacy-key-material"
    assert not legacy.exists()  # moved, not copied


def test_vault_plaintext_fallback_when_cryptography_missing(monkeypatch, tmp_path):
    """When cryptography can't import, writes are refused by default (fail closed);
    BREACHPILOT_ALLOW_PLAINTEXT_VAULT=1 opts back into the loud plaintext fallback."""
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    monkeypatch.delenv("BREACHPILOT_ALLOW_PLAINTEXT_VAULT", raising=False)
    _Vault._plaintext_warned = False  # reset the one-time warning gate
    # Force `from cryptography.fernet import Fernet` inside _Vault.__init__ to fail.
    real = sys.modules.get("cryptography.fernet")
    sys.modules["cryptography.fernet"] = None  # sentinel -> ImportError on submodule import
    try:
        v = _Vault(tmp_path)
        assert v.enabled is False
        with pytest.raises(RuntimeError, match="refusing plaintext write"):
            v.assert_writable()
        # reads stay fail-open so legacy stores never brick
        assert v.encrypt(_CLEARTEXT) == _CLEARTEXT  # passthrough
        assert v.decrypt("anything") == "anything"  # passthrough
        # explicit opt-in restores the legacy loud plaintext fallback
        monkeypatch.setenv("BREACHPILOT_ALLOW_PLAINTEXT_VAULT", "1")
        v2 = _Vault(tmp_path)
        assert v2.enabled is False
        v2.assert_writable()  # no raise under opt-in
        assert v2.encrypt(_CLEARTEXT) == _CLEARTEXT
    finally:
        if real is None:
            sys.modules.pop("cryptography.fernet", None)
        else:
            sys.modules["cryptography.fernet"] = real
    assert _Vault._plaintext_warned is True


def test_store_refuses_plaintext_write_by_default(monkeypatch, tmp_path):
    """CredentialStore.add/save raise and write nothing when secure storage is
    unavailable, unless BREACHPILOT_ALLOW_PLAINTEXT_VAULT=1 is set."""
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    monkeypatch.delenv("BREACHPILOT_ALLOW_PLAINTEXT_VAULT", raising=False)
    _Vault._plaintext_warned = False
    real = sys.modules.get("cryptography.fernet")
    sys.modules["cryptography.fernet"] = None
    try:
        store = CredentialStore(tmp_path)
        assert store.encryption_enabled is False
        with pytest.raises(RuntimeError, match="refusing plaintext write"):
            store.add(_rec(username="admin"))
        assert not (tmp_path / "credentials.jsonl").exists()  # nothing persisted
        # opt-in allows the insecure write (loudly)
        monkeypatch.setenv("BREACHPILOT_ALLOW_PLAINTEXT_VAULT", "1")
        store2 = CredentialStore(tmp_path)
        store2.add(_rec(username="admin"))
        assert (tmp_path / "credentials.jsonl").exists()
    finally:
        if real is None:
            sys.modules.pop("cryptography.fernet", None)
        else:
            sys.modules["cryptography.fernet"] = real


def test_vault_decrypt_failopen_on_wrong_key(monkeypatch, tmp_path):
    key_a = Fernet.generate_key().decode()
    monkeypatch.setenv("AI_NMAP_VAULT_KEY", key_a)
    va = _Vault(tmp_path)
    token = va.encrypt(_CLEARTEXT)
    # A different key cannot decrypt -- the vault returns the token unchanged
    # rather than raising (legacy/wrong-key reads never brick the store).
    key_b = Fernet.generate_key().decode()
    monkeypatch.setenv("AI_NMAP_VAULT_KEY", key_b)
    vb = _Vault(tmp_path)
    assert vb.enabled is True
    assert vb.decrypt(token) == token  # fail-open, not an exception


# ── 2. CredentialStore ──────────────────────────────────────────────────────


def test_store_writes_ciphertext_disk_memory_plaintext(monkeypatch, tmp_path):
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    store = CredentialStore(tmp_path)
    assert store.encryption_enabled is True
    store.add(_rec(password=_CLEARTEXT))

    # In memory: plaintext
    assert store.all_credentials()[0].password == _CLEARTEXT
    # On disk: ciphertext -- the cleartext never appears in the file bytes
    disk = (tmp_path / "credentials.jsonl").read_text(encoding="utf-8")
    assert _CLEARTEXT not in disk
    line = json.loads(disk.strip().splitlines()[-1])
    assert line["password"].startswith("gAAAAA")
    assert line["confirmed"] is False  # add stores unconfirmed


def test_store_reloads_plaintext_from_ciphertext(monkeypatch, tmp_path):
    monkeypatch.setenv("AI_NMAP_VAULT_KEY", Fernet.generate_key().decode())
    s1 = CredentialStore(tmp_path)
    s1.add(_rec(password=_CLEARTEXT))
    # New instance, same key -> decrypts back to plaintext
    s2 = CredentialStore(tmp_path)
    assert s2.all_credentials()[0].password == _CLEARTEXT


def test_store_legacy_plaintext_file_still_loads(monkeypatch, tmp_path):
    """A pre-encryption plaintext file must still load (fail-open decrypt)."""
    monkeypatch.setenv("AI_NMAP_VAULT_KEY", Fernet.generate_key().decode())
    (tmp_path / "credentials.jsonl").write_text(
        json.dumps(
            {
                "timestamp": time.time(),
                "source_host": "10.0.0.50",
                "target_host": "10.0.0.50",
                "username": "legacy",
                "password": _CLEARTEXT,  # plaintext, not a Fernet token
                "credential_type": "password",
                "source_action": "legacy",
                "confirmed": False,
                "notes": "",
            }
        )
        + "\n",
        encoding="utf-8",
    )
    store = CredentialStore(tmp_path)
    recs = store.all_credentials()
    assert len(recs) == 1
    # decrypt() returns the value unchanged when it isn't a valid token
    assert recs[0].password == _CLEARTEXT


def test_confirm_credential_is_only_path_to_confirmed(monkeypatch, tmp_path):
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    store = CredentialStore(tmp_path)
    store.add(_rec(username="admin", target_host="10.0.0.50"))
    assert store.all_credentials()[0].confirmed is False

    # confirm without validated=True is refused by the gate -- flips nothing
    assert store.confirm_credential(username="admin", target_host="10.0.0.50") is False
    assert store.all_credentials()[0].confirmed is False
    # confirm with validated=True flips it
    assert store.confirm_credential(username="admin", target_host="10.0.0.50", validated=True) is True
    assert store.all_credentials()[0].confirmed is True
    # re-confirm of already-confirmed returns False (no new confirmation)
    assert store.confirm_credential(username="admin", target_host="10.0.0.50", validated=True) is False
    # confirm of a non-existent cred returns False
    assert store.confirm_credential(username="nobody", target_host="10.0.0.50", validated=True) is False
    # confirm persisted to disk (encrypted + HMAC-signed) and reloads confirmed
    s2 = CredentialStore(tmp_path)
    assert s2.all_credentials()[0].confirmed is True


def test_confirm_credential_filtered_by_type(monkeypatch, tmp_path):
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    store = CredentialStore(tmp_path)
    store.add(_rec(username="svc", password=_CLEARTEXT, ctype="password"))
    store.add(_rec(username="svc", password=_NTLM, ctype="hash"))
    # confirm only the hash, not the password
    assert (
        store.confirm_credential(username="svc", target_host="10.0.0.50", credential_type="hash", validated=True)
        is True
    )
    pw, h = sorted(store.all_credentials(), key=lambda r: r.credential_type)
    assert pw.credential_type == "hash" and pw.confirmed is True
    assert h.credential_type == "password" and h.confirmed is False


def test_add_dedups_same_username_host_type(monkeypatch, tmp_path):
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    store = CredentialStore(tmp_path)
    store.add(_rec(username="admin", target_host="10.0.0.50", ctype="password"))
    store.add(_rec(username="admin", target_host="10.0.0.50", ctype="password"))
    assert len(store.all_credentials()) == 1
    # different type -> separate record
    store.add(_rec(username="admin", target_host="10.0.0.50", ctype="hash"))
    assert len(store.all_credentials()) == 2


def test_save_rewrites_all_encrypted(monkeypatch, tmp_path):
    monkeypatch.setenv("AI_NMAP_VAULT_KEY", Fernet.generate_key().decode())
    store = CredentialStore(tmp_path)
    store.add(_rec(username="a", password="pwA"))
    store.add(_rec(username="b", password="pwB"))
    store.confirm_credential(username="a", target_host="10.0.0.50", validated=True)  # triggers save()
    disk = (tmp_path / "credentials.jsonl").read_text(encoding="utf-8")
    assert "pwA" not in disk and "pwB" not in disk  # all ciphertext
    assert disk.count("gAAAAA") == 4  # password and free-text notes for each record


# ── 3. MCP cred_store tools end-to-end ───────────────────────────────────────


def _make_server(tmp_path: Path, *, require_allowlist: bool = False, permission: str = "full_access"):
    from mcp_exploit_server import create_mcp_server
    from tools.cve_lookup import CVESearchSettings, NVDClient
    from tools.exploit_search import ExploitSearch, ExploitSearchSettings
    from tools.web_researcher import WebResearcher, WebResearcherSettings

    config: dict[str, Any] = {
        "exploit": {
            "require_explicit_allowlist": require_allowlist,
            "allowed_targets": [],
            "permission": permission,
        }
    }
    return create_mcp_server(
        ExploitSearch(ExploitSearchSettings()),
        NVDClient(CVESearchSettings()),
        WebResearcher(WebResearcherSettings()),
        tmp_path,
        config,
    )


def _text(result) -> str:
    content = result[0] if isinstance(result, (list, tuple)) else result
    if hasattr(content, "content"):
        content = content.content
    return "".join(getattr(c, "text", str(c)) for c in content)


@pytest.mark.asyncio
async def test_mcp_cred_store_add_encrypts_and_audits_redacted(monkeypatch, tmp_path):
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    mcp = _make_server(tmp_path)
    text = _text(
        await mcp.call_tool(
            "cred_store_add",
            {
                "target_ip": "10.0.0.50",
                "username": "admin",
                "password": _CLEARTEXT,
                "credential_type": "password",
            },
        )
    )
    assert "CRED_STORE_ADD: stored" in text
    assert "ENCRYPTION_AT_REST: ENABLED" in text

    # On-disk vault is ciphertext
    cred_file = tmp_path / "credentials" / "10.0.0.50" / "credentials.jsonl"
    assert cred_file.exists()
    disk = cred_file.read_text(encoding="utf-8")
    assert _CLEARTEXT not in disk

    # Audit log args redacted (password never reaches exploit_audit.jsonl)
    audit = (tmp_path / "exploit_audit.jsonl").read_text(encoding="utf-8")
    assert _CLEARTEXT not in audit
    assert "***REDACTED***" in audit


@pytest.mark.asyncio
async def test_mcp_cred_store_add_rejects_bad_inputs(tmp_path):
    mcp = _make_server(tmp_path)
    # bad target_ip -> ERROR (invalid target)
    assert "Invalid" in _text(
        await mcp.call_tool("cred_store_add", {"target_ip": "999.0.0.50", "username": "u", "password": "p"})
    )
    # missing username
    assert "BLOCKED" in _text(
        await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "", "password": "p"})
    )
    # missing secret
    assert "BLOCKED" in _text(
        await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "u", "password": ""})
    )
    # bad type
    assert "BLOCKED" in _text(
        await mcp.call_tool(
            "cred_store_add", {"target_ip": "10.0.0.50", "username": "u", "password": "p", "credential_type": "raw"}
        )
    )


@pytest.mark.asyncio
async def test_mcp_cred_store_get_masks_then_reveals(monkeypatch, tmp_path):
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    mcp = _make_server(tmp_path)
    await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "admin", "password": _CLEARTEXT})

    # default get masks the secret
    masked = _text(await mcp.call_tool("cred_store_get", {"target_ip": "10.0.0.50", "username": "admin"}))
    assert "admin" in masked
    assert _CLEARTEXT not in masked
    assert "masked" in masked.lower()

    # include_secret reveals it
    revealed = _text(
        await mcp.call_tool("cred_store_get", {"target_ip": "10.0.0.50", "username": "admin", "include_secret": True})
    )
    assert _CLEARTEXT in revealed


@pytest.mark.asyncio
@pytest.mark.parametrize("permission", ["read_only", "approve_only"])
async def test_mcp_cred_store_secret_reveal_requires_full_access(monkeypatch, tmp_path, permission):
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    mcp = _make_server(tmp_path, permission=permission)
    await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "admin", "password": _CLEARTEXT})

    result = _text(
        await mcp.call_tool(
            "cred_store_get",
            {"target_ip": "10.0.0.50", "username": "admin", "include_secret": True},
        )
    )
    assert "BLOCKED" in result
    assert _CLEARTEXT not in result


@pytest.mark.asyncio
async def test_mcp_cred_store_list_safe_no_cleartext(monkeypatch, tmp_path):
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    mcp = _make_server(tmp_path)
    await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "admin", "password": _CLEARTEXT})
    listed = _text(await mcp.call_tool("cred_store_list", {"target_ip": "10.0.0.50"}))
    assert "admin" in listed
    assert "confirmed=False" in listed
    assert _CLEARTEXT not in listed  # safe summary


@pytest.mark.asyncio
async def test_mcp_cred_store_confirmation_requires_operator(monkeypatch, tmp_path):
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    mcp = _make_server(tmp_path)
    await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "admin", "password": _CLEARTEXT})
    # before: unconfirmed
    assert "confirmed=False" in _text(await mcp.call_tool("cred_store_list", {"target_ip": "10.0.0.50"}))
    # There is no agent-callable validated=True assertion anymore.
    refused = _text(await mcp.call_tool("cred_store_confirm", {}))
    assert "BLOCKED" in refused and "operator" in refused.lower()
    forged = await mcp.call_tool(
        "cred_store_confirm",
        {"target_ip": "10.0.0.50", "username": "admin", "validated": True},
    )
    assert getattr(forged, "isError", False) or "BLOCKED" in _text(forged)
    assert "confirmed=False" in _text(await mcp.call_tool("cred_store_list", {"target_ip": "10.0.0.50"}))


@pytest.mark.asyncio
async def test_mcp_cred_store_add_duplicate_not_readded(monkeypatch, tmp_path):
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    mcp = _make_server(tmp_path)
    await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "admin", "password": _CLEARTEXT})
    second = _text(
        await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "admin", "password": _CLEARTEXT})
    )
    assert "duplicate" in second.lower()
    listed = _text(await mcp.call_tool("cred_store_list", {"target_ip": "10.0.0.50"}))
    assert listed.count("admin/password") == 1


# ── 4. HMAC integrity + validated gate (Tier 0 item 0.3, Unit E) ─────────────
#
# ``confirmed=True`` is the trust gate for credential reuse. Two defenses pin it:
# (1) ``confirm_credential`` refuses without ``validated=True``, so a careless or
#     harvest-time call cannot promote an unvalidated credential; (2) the
#     ``confirmed`` flag is HMAC-signed at rest, so a hand-edited file, a file
#     copied from another workspace, or anything written under plaintext fallback
#     cannot carry a forged ``confirmed=True`` into memory -- it is downgraded to
#     False on load and logged.


def test_confirm_refused_without_validated_flag(monkeypatch, tmp_path):
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    store = CredentialStore(tmp_path)
    store.add(_rec(username="admin", target_host="10.0.0.50"))
    # bare confirm flips nothing and persists nothing
    assert store.confirm_credential(username="admin", target_host="10.0.0.50") is False
    assert store.all_credentials()[0].confirmed is False
    disk = (tmp_path / "credentials.jsonl").read_text(encoding="utf-8")
    assert json.loads(disk.strip().splitlines()[-1])["confirmed"] is False


def test_hmac_confirmed_survives_reload_same_key(monkeypatch, tmp_path):
    """A signed confirmed=True reloads confirmed under the same vault key."""
    key = Fernet.generate_key().decode()
    monkeypatch.setenv("AI_NMAP_VAULT_KEY", key)
    store = CredentialStore(tmp_path)
    store.add(_rec(username="admin", target_host="10.0.0.50"))
    assert store.confirm_credential(username="admin", target_host="10.0.0.50", validated=True) is True
    line = json.loads((tmp_path / "credentials.jsonl").read_text(encoding="utf-8").strip().splitlines()[-1])
    assert "sig" in line and line["sig"]  # on-disk record carries an HMAC
    s2 = CredentialStore(tmp_path)
    assert s2.all_credentials()[0].confirmed is True  # sig verifies -> survives


def test_hmac_tampered_confirmed_downgraded(monkeypatch, tmp_path):
    """A hand-edited confirmed=True with no HMAC is downgraded on load -- a forged
    confirmed flag is never trusted."""
    key = Fernet.generate_key().decode()
    monkeypatch.setenv("AI_NMAP_VAULT_KEY", key)
    store = CredentialStore(tmp_path)
    store.add(_rec(username="admin", target_host="10.0.0.50"))
    store_path = tmp_path / "credentials.jsonl"
    rec_line = json.loads(store_path.read_text(encoding="utf-8").strip().splitlines()[-1])
    rec_line["confirmed"] = True
    rec_line.pop("sig", None)  # strip the signature -> unauthenticated
    store_path.write_text(json.dumps(rec_line) + "\n", encoding="utf-8")
    s2 = CredentialStore(tmp_path)
    assert s2.all_credentials()[0].confirmed is False  # downgraded, not trusted


def test_hmac_flipped_confirmed_breaks_signature(monkeypatch, tmp_path):
    """Flipping confirmed=True on a signed record (leaving the stale sig) makes the
    signature not verify under the key -> downgraded. Tamper-evidence holds even
    when the attacker knows to keep a sig field."""
    key = Fernet.generate_key().decode()
    monkeypatch.setenv("AI_NMAP_VAULT_KEY", key)
    store = CredentialStore(tmp_path)
    store.add(_rec(username="admin", target_host="10.0.0.50"))
    store_path = tmp_path / "credentials.jsonl"
    rec_line = json.loads(store_path.read_text(encoding="utf-8").strip().splitlines()[-1])
    rec_line["confirmed"] = True  # flip the flag, KEEP the (now-stale) sig
    store_path.write_text(json.dumps(rec_line) + "\n", encoding="utf-8")
    s2 = CredentialStore(tmp_path)
    assert s2.all_credentials()[0].confirmed is False  # sig no longer matches


def test_hmac_foreign_workspace_confirmed_downgraded(monkeypatch, tmp_path):
    """A confirmed=True signed under a different vault key is downgraded when read
    under this workspace's key (the file was copied in from elsewhere)."""
    key_a = Fernet.generate_key().decode()
    monkeypatch.setenv("AI_NMAP_VAULT_KEY", key_a)
    store_a = CredentialStore(tmp_path)
    store_a.add(_rec(username="admin", target_host="10.0.0.50"))
    assert store_a.confirm_credential(username="admin", target_host="10.0.0.50", validated=True) is True
    # read the same on-disk file under a DIFFERENT key -> sig does not verify
    monkeypatch.setenv("AI_NMAP_VAULT_KEY", Fernet.generate_key().decode())
    store_b = CredentialStore(tmp_path)
    assert store_b.all_credentials()[0].confirmed is False


def test_plaintext_fallback_confirmed_never_trusted_from_disk(monkeypatch, tmp_path):
    """In plaintext-fallback mode no HMAC can be produced, so a confirmed=True on
    disk is never trusted and is downgraded on reload -- only a SIGNED confirmed
    survives. (The in-memory confirm still works; the gate is the reload.)
    Requires the explicit plaintext opt-in since writes are fail-closed by default."""
    monkeypatch.setenv("BREACHPILOT_ALLOW_PLAINTEXT_VAULT", "1")
    _Vault._plaintext_warned = False
    real = sys.modules.get("cryptography.fernet")
    sys.modules["cryptography.fernet"] = None  # force ImportError inside _Vault
    try:
        store = CredentialStore(tmp_path)
        assert store.encryption_enabled is False
        store.add(_rec(username="admin", target_host="10.0.0.50"))
        # the validated gate still flips the in-memory flag
        assert store.confirm_credential(username="admin", target_host="10.0.0.50", validated=True) is True
        assert store.all_credentials()[0].confirmed is True
        # but no sig could be written, so a reload must not trust confirmed=True
        s2 = CredentialStore(tmp_path)
        assert s2.all_credentials()[0].confirmed is False
    finally:
        if real is None:
            sys.modules.pop("cryptography.fernet", None)
        else:
            sys.modules["cryptography.fernet"] = real


# ── 5. Workspace read/list denylist for credential artifacts (Unit E) ────────


def _read_audit(workspace: Path) -> list[dict[str, Any]]:
    audit = workspace / "exploit_audit.jsonl"
    if not audit.exists():
        return []
    return [json.loads(line) for line in audit.read_text(encoding="utf-8").splitlines() if line.strip()]


@pytest.mark.asyncio
async def test_read_workspace_file_denies_vault_keyfile(monkeypatch, tmp_path):
    """The vault keyfile is deny-listed from workspace reads: serving it would
    hand the credential-store Fernet key to the model (ciphertext = plaintext).
    The live key lives outside the workspace tree; a legacy in-workspace path
    is refused by basename either way."""
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    monkeypatch.setenv("BREACHPILOT_VAULT_DIR", str(tmp_path.parent / f"{tmp_path.name}-vault_home"))
    mcp = _make_server(tmp_path)
    await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "admin", "password": _CLEARTEXT})
    # no key material under the workspace tree anymore
    assert not (tmp_path / "credentials" / "10.0.0.50" / ".vault_key").exists()
    out = _text(await mcp.call_tool("read_workspace_file", {"filename": "credentials/10.0.0.50/.vault_key"}))
    assert out.startswith("BLOCKED:")
    # ... however the key path is spelled
    out2 = _text(await mcp.call_tool("read_workspace_file", {"filename": ".vault_key"}))
    assert out2.startswith("BLOCKED:")


@pytest.mark.asyncio
async def test_read_workspace_file_denies_vault_key_symlink_alias(tmp_path):
    """A benign in-workspace symlink must not expose a legacy vault key."""
    mcp = _make_server(tmp_path)
    key = tmp_path / ".vault_key"
    key.write_text("vault-key-secret", encoding="utf-8")
    alias = tmp_path / "notes.txt"
    try:
        alias.symlink_to(key)
    except (NotImplementedError, OSError) as exc:
        pytest.skip(f"symlink creation is unavailable: {exc}")

    result = _text(await mcp.call_tool("read_workspace_file", {"filename": alias.name}))
    assert result.startswith("BLOCKED:")
    assert "vault-key-secret" not in result


@pytest.mark.asyncio
async def test_read_workspace_file_rejects_symlink_swap_after_containment_check(monkeypatch, tmp_path):
    """A workspace file replaced after resolution is opened with O_NOFOLLOW."""
    from pathlib import Path

    from tools.kernel import workspace as workspace_module

    mcp = _make_server(tmp_path)
    target = tmp_path / "loot.txt"
    target.write_text("safe workspace content", encoding="utf-8")
    secret = tmp_path.parent / f"{tmp_path.name}-host-secret.txt"
    secret.write_text("host-only secret", encoding="utf-8")
    original_resolve = Path.resolve
    alias_resolves = 0
    swapped = False

    def racing_resolve(path, *args, **kwargs):
        nonlocal alias_resolves, swapped
        result = original_resolve(path, *args, **kwargs)
        if path == target and not swapped:
            alias_resolves += 1
            if alias_resolves == 2:
                target.unlink()
                target.symlink_to(secret)
                swapped = True
        return result

    monkeypatch.setattr(workspace_module.Path, "resolve", racing_resolve)
    result = _text(await mcp.call_tool("read_workspace_file", {"filename": "loot.txt"}))
    assert result.startswith("BLOCKED:")
    assert "host-only secret" not in result


@pytest.mark.asyncio
async def test_read_workspace_file_denies_credentials_store(monkeypatch, tmp_path):
    """Raw credential vault files are denied even when current rows are encrypted,
    because old rows and free-text content may contain plaintext secrets."""
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    mcp = _make_server(tmp_path)
    await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "admin", "password": _CLEARTEXT})
    assert (tmp_path / "credentials" / "10.0.0.50" / "credentials.jsonl").exists()
    out = _text(await mcp.call_tool("read_workspace_file", {"filename": "credentials/10.0.0.50/credentials.jsonl"}))
    assert out.startswith("BLOCKED:")


@pytest.mark.asyncio
async def test_read_workspace_file_denies_legacy_plaintext_credentials(monkeypatch, tmp_path):
    mcp = _make_server(tmp_path)
    cred_file = tmp_path / "credentials" / "10.0.0.50" / "credentials.jsonl"
    cred_file.parent.mkdir(parents=True)
    cred_file.write_text(json.dumps({"username": "admin", "password": _CLEARTEXT}) + "\n", encoding="utf-8")
    out = _text(await mcp.call_tool("read_workspace_file", {"filename": "credentials/10.0.0.50/credentials.jsonl"}))
    assert out.startswith("BLOCKED:")
    assert _CLEARTEXT not in out


@pytest.mark.asyncio
async def test_list_workspace_redacts_credentials_subtree_and_keyfile(monkeypatch, tmp_path):
    """list_workspace redacts the credentials/ subtree (count shown, names
    hidden) and never lists vault keyfile names anywhere in the tree."""
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    monkeypatch.setenv("BREACHPILOT_VAULT_DIR", str(tmp_path.parent / f"{tmp_path.name}-vault_home"))
    mcp = _make_server(tmp_path)
    await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "admin", "password": _CLEARTEXT})
    listed = _text(await mcp.call_tool("list_workspace", {}))
    assert "credentials/ (" in listed and "redacted" in listed  # subtree counted, not shown
    assert "credentials.jsonl" not in listed
    assert ".vault_key" not in listed  # keyfile names are never listed


@pytest.mark.asyncio
async def test_read_workspace_file_is_audited(monkeypatch, tmp_path):
    """Every read_workspace_file call writes an audit record (traceability)."""
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    mcp = _make_server(tmp_path)
    (tmp_path / "scan.txt").write_text("nmap output", encoding="utf-8")
    await mcp.call_tool("read_workspace_file", {"filename": "scan.txt"})
    audit = _read_audit(tmp_path)
    rr = [r for r in audit if r["tool_name"] == "read_workspace_file"]
    assert rr and any(r["status"] == "completed" for r in rr)
    assert rr[0]["args"]["filename"] == "scan.txt"  # filename logged, not secret


@pytest.mark.asyncio
async def test_read_workspace_file_still_reads_normal_files(monkeypatch, tmp_path):
    """The denylist must not block legitimate workspace files (regression guard)."""
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    mcp = _make_server(tmp_path)
    (tmp_path / "loot.txt").write_text("here is some loot", encoding="utf-8")
    out = _text(await mcp.call_tool("read_workspace_file", {"filename": "loot.txt"}))
    assert "here is some loot" in out


# ── 6. Unit E bypass hardening (confirmed-forge, hardlink alias, link-list leak) ─


def test_add_forces_confirmed_false_even_when_caller_supplies_true(
    monkeypatch,
    tmp_path,
    caplog,
):
    """Bypass 1 (validated-gate forge): ``add`` must not persist a caller-supplied
    ``confirmed=True``. Without this, a harvest path (or a hand-built record) could
    store a confirmed credential that reloads HMAC-verified -- silently bypassing
    the ``confirm_credential(validated=True)`` gate the exploit loop trusts before
    reusing a credential at full access. The *only* path to confirmed=True stays
    ``confirm_credential``; ``add`` is the harvester and must yield unconfirmed."""
    import logging

    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    store = CredentialStore(tmp_path)
    rec = _rec(username="admin", target_host="10.0.0.50", confirmed=True)
    with caplog.at_level(logging.WARNING, logger="tools.credential_store"):
        store.add(rec)
    # the record object itself is forced back to unconfirmed before it is stored
    assert rec.confirmed is False
    assert store.all_credentials()[0].confirmed is False
    # on-disk: confirmed=False, so the HMAC we just wrote covers False (not True)
    line = json.loads((tmp_path / "credentials.jsonl").read_text(encoding="utf-8").strip().splitlines()[-1])
    assert line["confirmed"] is False
    assert "sig" in line and line["sig"]
    # reload: verified signature + confirmed=False -> stays False (no promotion
    # from a forge; only confirm_credential(validated=True) can flip this)
    store2 = CredentialStore(tmp_path)
    assert store2.all_credentials()[0].confirmed is False
    # the forge attempt was not silent -- the operator-visible warning fired
    assert any("forcing False" in r.message for r in caplog.records)


@pytest.mark.asyncio
async def test_cred_store_add_notes_secret_redacted_in_audit(monkeypatch, tmp_path):
    """Bypass 6 (free-text leak): a secret placed in the free-text ``notes`` param
    must not reach ``exploit_audit.jsonl`` in cleartext. ``notes`` mirrors
    ``input_text`` -- free text the LLM can stuff with anything, and
    ``_mask_secret_content`` only catches known inline-credential *shapes*, so the
    whole value is wholesale-redacted in the audit log (execution still uses the raw
    value). The on-disk store is operator-controlled; the audit log is the leak
    surface this closes."""
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    mcp = _make_server(tmp_path)
    secret = "plaintext-is-hunter2-from-notes"
    text = _text(
        await mcp.call_tool(
            "cred_store_add",
            {
                "target_ip": "10.0.0.50",
                "username": "admin",
                "password": _CLEARTEXT,
                "credential_type": "password",
                "notes": f"reused from ssh login; {secret}",
            },
        )
    )
    assert "CRED_STORE_ADD: stored" in text
    audit = (tmp_path / "exploit_audit.jsonl").read_text(encoding="utf-8")
    assert secret not in audit  # the notes-embedded secret never reaches disk
    assert _CLEARTEXT not in audit  # the password arg is also redacted
    # the notes field is masked wholesale (not shape-matched); password too
    records = _read_audit(tmp_path)
    add_recs = [r for r in records if r.get("tool_name") == "cred_store_add"]
    assert add_recs
    assert all(r["args"].get("notes") == "***REDACTED***" for r in add_recs)
    assert all(r["args"].get("password") == "***REDACTED***" for r in add_recs)


@pytest.mark.asyncio
async def test_credential_notes_are_encrypted_and_withheld_by_default(monkeypatch, tmp_path):
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    monkeypatch.setenv("BREACHPILOT_VAULT_DIR", str(tmp_path.parent / f"{tmp_path.name}-vault"))
    mcp = _make_server(tmp_path)
    sensitive_note = "operator-private-auth-context"
    await mcp.call_tool(
        "cred_store_add",
        {"target_ip": "10.0.0.50", "username": "admin", "password": _CLEARTEXT, "notes": sensitive_note},
    )
    raw = (tmp_path / "credentials" / "10.0.0.50" / "credentials.jsonl").read_text(encoding="utf-8")
    assert sensitive_note not in raw
    summary = _text(await mcp.call_tool("cred_store_get", {"target_ip": "10.0.0.50", "username": "admin"}))
    assert sensitive_note not in summary
    revealed = _text(
        await mcp.call_tool("cred_store_get", {"target_ip": "10.0.0.50", "username": "admin", "include_secret": True})
    )
    assert sensitive_note in revealed


@pytest.mark.asyncio
async def test_read_workspace_file_denies_hardlink_to_credential_store(monkeypatch, tmp_path):
    """A benign-named hard link cannot bypass credential-path redaction."""
    import os

    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    monkeypatch.setenv("BREACHPILOT_VAULT_DIR", str(tmp_path.parent / f"{tmp_path.name}-vault_home"))
    mcp = _make_server(tmp_path)
    await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "admin", "password": _CLEARTEXT})
    cred_file = tmp_path / "credentials" / "10.0.0.50" / "credentials.jsonl"
    assert cred_file.exists()
    assert not (tmp_path / "credentials" / "10.0.0.50" / ".vault_key").exists()
    cred_link = tmp_path / "loot.txt"
    try:
        os.link(cred_file, cred_link)
    except OSError as exc:  # filesystem does not support hard links
        pytest.skip(f"hard links unavailable on this filesystem: {exc!r}")
    assert os.path.samefile(cred_link, cred_file)
    # The outside alias still names the same protected inode.
    out = _text(await mcp.call_tool("read_workspace_file", {"filename": "loot.txt"}))
    assert out.startswith("BLOCKED:")
    assert _CLEARTEXT not in out


@pytest.mark.asyncio
async def test_list_workspace_redacts_credentials_via_link_alias(monkeypatch, tmp_path):
    """Credential paths remain redacted when a workspace contains a directory alias."""
    import os
    import subprocess

    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    mcp = _make_server(tmp_path)
    await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "admin", "password": _CLEARTEXT})
    cred_dir = tmp_path / "credentials"
    alias = tmp_path / "data"
    # try a real symlink first (POSIX always; Windows needs dev-mode/privilege)
    created = False
    try:
        os.symlink(cred_dir, alias, target_is_directory=True)
        created = True
    except (OSError, NotImplementedError):
        created = False
    # Windows junction via mklink /J needs no privilege
    if not created and os.name == "nt":
        try:
            r = subprocess.run(
                ["cmd", "/c", "mklink", "/J", str(alias), str(cred_dir)],
                capture_output=True,
                timeout=10,
            )
            created = r.returncode == 0
        except Exception:
            created = False
    if not created:
        pytest.skip("link/junction creation unavailable in this environment")
    listed = _text(await mcp.call_tool("list_workspace", {}))
    low = listed.lower()
    # the credentials/ subtree is counted, never enumerated (followlinks=False
    # also keeps the symlink alias from leaking names)
    assert "credentials" in low
    assert ".vault_key" not in listed  # keyfile names are never listed
    assert "credentials.jsonl" not in listed


def test_vault_canonical_env_key_roundtrip(monkeypatch, tmp_path):
    """TODO 012: BREACHPILOT_VAULT_KEY is canonical and warns nothing."""
    import warnings

    key = Fernet.generate_key().decode()
    monkeypatch.setenv("BREACHPILOT_VAULT_KEY", key)
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    with warnings.catch_warnings():
        warnings.simplefilter("error", DeprecationWarning)
        v = _Vault(tmp_path)
    assert v.enabled is True
    assert v.decrypt(v.encrypt(_CLEARTEXT)) == _CLEARTEXT


def test_vault_legacy_alias_warns(monkeypatch, tmp_path):
    """TODO 012: AI_NMAP_VAULT_KEY still works but warns."""
    import warnings

    key = Fernet.generate_key().decode()
    monkeypatch.delenv("BREACHPILOT_VAULT_KEY", raising=False)
    monkeypatch.setenv("AI_NMAP_VAULT_KEY", key)
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always", DeprecationWarning)
        v = _Vault(tmp_path)
    assert v.enabled is True
    assert any("AI_NMAP_VAULT_KEY is deprecated" in str(w.message) for w in caught)


def test_vault_canonical_wins_when_both_set(monkeypatch, tmp_path):
    """TODO 012: both set -> canonical wins."""
    key_canonical = Fernet.generate_key().decode()
    key_legacy = Fernet.generate_key().decode()
    assert key_canonical != key_legacy
    monkeypatch.setenv("BREACHPILOT_VAULT_KEY", key_canonical)
    monkeypatch.setenv("AI_NMAP_VAULT_KEY", key_legacy)
    v = _Vault(tmp_path)
    assert v.enabled is True
    # Canonical key material is the signing key.
    assert v.signing_key == key_canonical.encode()


def test_credential_store_rejects_symlinked_store_without_reading_target(monkeypatch, tmp_path):
    """A sandbox-created credential-store link cannot expose a host file."""
    root = tmp_path / "workspace"
    store_dir = root / "credentials" / "10.0.0.50"
    store_dir.mkdir(parents=True)
    host_file = tmp_path / "host-credentials.jsonl"
    host_contents = (
        json.dumps(
            {
                "timestamp": time.time(),
                "source_host": "host",
                "target_host": "host",
                "username": "host-user",
                "password": "host-secret-must-not-be-read",
                "credential_type": "password",
                "source_action": "host",
                "confirmed": False,
                "notes": "",
            }
        )
        + "\n"
    )
    host_file.write_text(host_contents, encoding="utf-8")
    try:
        (store_dir / "credentials.jsonl").symlink_to(host_file)
    except (NotImplementedError, OSError) as exc:
        pytest.skip(f"symlink creation is unavailable: {exc}")

    monkeypatch.setenv("BREACHPILOT_VAULT_KEY", Fernet.generate_key().decode())
    with pytest.raises(OSError):
        CredentialStore(store_dir, workspace_root=root)
    assert host_file.read_text(encoding="utf-8") == host_contents


def test_credential_store_rejects_symlink_swaps_for_append_and_atomic_save(monkeypatch, tmp_path):
    """Append refuses a linked store; save replaces only the link entry itself."""
    monkeypatch.setenv("BREACHPILOT_VAULT_KEY", Fernet.generate_key().decode())
    root = tmp_path / "workspace"
    store_dir = root / "credentials" / "10.0.0.50"
    store = CredentialStore(store_dir, workspace_root=root)
    host_file = tmp_path / "host-credentials.jsonl"
    host_file.write_text("host data\n", encoding="utf-8")
    store_file = store_dir / "credentials.jsonl"
    try:
        store_file.symlink_to(host_file)
    except (NotImplementedError, OSError) as exc:
        pytest.skip(f"symlink creation is unavailable: {exc}")

    with pytest.raises(OSError):
        store.add(_rec(username="blocked"))
    assert store.all_credentials() == []
    assert host_file.read_text(encoding="utf-8") == "host data\n"

    store_file.unlink()
    store.add(_rec(username="admin"))
    store_file.unlink()
    store_file.symlink_to(host_file)
    assert store.confirm_credential(username="admin", target_host="10.0.0.50", validated=True)
    assert not store_file.is_symlink()
    assert host_file.read_text(encoding="utf-8") == "host data\n"
    reloaded = CredentialStore(store_dir, workspace_root=root)
    assert reloaded.all_credentials()[0].confirmed is True


def test_credential_store_append_repairs_permissive_mode(monkeypatch, tmp_path):
    monkeypatch.setenv("BREACHPILOT_VAULT_KEY", Fernet.generate_key().decode())
    store = CredentialStore(tmp_path)
    store.add(_rec(username="first"))
    store_path = tmp_path / "credentials.jsonl"
    store_path.chmod(0o644)

    reloaded = CredentialStore(tmp_path)
    reloaded.add(_rec(username="second"))

    assert store_path.stat().st_mode & 0o077 == 0
    assert [record.username for record in reloaded.all_credentials()] == ["first", "second"]


def test_credential_store_append_fails_closed_when_permissions_cannot_be_repaired(monkeypatch, tmp_path):
    import os

    monkeypatch.setenv("BREACHPILOT_VAULT_KEY", Fernet.generate_key().decode())
    store = CredentialStore(tmp_path)
    store.add(_rec(username="first"))
    store_path = tmp_path / "credentials.jsonl"
    store_path.chmod(0o644)
    before = store_path.read_bytes()
    original_fchmod = os.fchmod

    def fail_fchmod(fd: int, mode: int) -> None:
        raise PermissionError("simulated chmod failure")

    monkeypatch.setattr(os, "fchmod", fail_fchmod)
    with pytest.raises(PermissionError, match="simulated chmod failure"):
        store.add(_rec(username="second"))

    monkeypatch.setattr(os, "fchmod", original_fchmod)
    assert store_path.read_bytes() == before
    assert store_path.stat().st_mode & 0o077
    assert [record.username for record in store.all_credentials()] == ["first"]


def test_credential_store_rejects_symlinked_parent_directory(monkeypatch, tmp_path):
    """A linked credentials directory cannot redirect host reads or writes."""
    monkeypatch.setenv("BREACHPILOT_VAULT_KEY", Fernet.generate_key().decode())
    root = tmp_path / "workspace"
    root.mkdir()
    external = tmp_path / "external"
    external.mkdir()
    sentinel = external / "sentinel.txt"
    sentinel.write_text("host-only", encoding="utf-8")
    try:
        (root / "credentials").symlink_to(external, target_is_directory=True)
    except (NotImplementedError, OSError) as exc:
        pytest.skip(f"symlink creation is unavailable: {exc}")

    with pytest.raises(OSError):
        CredentialStore(root / "credentials" / "10.0.0.50", workspace_root=root)
    assert sentinel.read_text(encoding="utf-8") == "host-only"


def test_credential_store_save_refuses_precreated_temp_symlink(monkeypatch, tmp_path):
    """Exclusive temporary creation fails without following a planted link."""
    monkeypatch.setenv("BREACHPILOT_VAULT_KEY", Fernet.generate_key().decode())
    root = tmp_path / "workspace"
    store_dir = root / "credentials" / "10.0.0.50"
    store = CredentialStore(store_dir, workspace_root=root)
    store.add(_rec(username="admin"))
    host_file = tmp_path / "host-temp-target"
    host_file.write_text("host-only", encoding="utf-8")
    temp_name = ".credentials-fixed-token.tmp"
    try:
        (store_dir / temp_name).symlink_to(host_file)
    except (NotImplementedError, OSError) as exc:
        pytest.skip(f"symlink creation is unavailable: {exc}")

    from tools import credential_store as credential_store_module

    monkeypatch.setattr(credential_store_module.secrets, "token_hex", lambda _size: "fixed-token")
    with pytest.raises(FileExistsError):
        store.save()
    assert host_file.read_text(encoding="utf-8") == "host-only"
    assert (store_dir / temp_name).is_symlink()


def test_credential_store_revalidates_parent_after_workspace_swap(monkeypatch, tmp_path):
    """Every operation reopens parent components with no-follow checks."""
    monkeypatch.setenv("BREACHPILOT_VAULT_KEY", Fernet.generate_key().decode())
    root = tmp_path / "workspace"
    store_dir = root / "credentials" / "10.0.0.50"
    store = CredentialStore(store_dir, workspace_root=root)
    store.add(_rec(username="admin"))
    external = tmp_path / "external"
    external.mkdir()
    sentinel = external / "sentinel.txt"
    sentinel.write_text("host-only", encoding="utf-8")
    (root / "credentials").rename(root / "credentials-original")
    try:
        (root / "credentials").symlink_to(external, target_is_directory=True)
    except (NotImplementedError, OSError) as exc:
        pytest.skip(f"symlink creation is unavailable: {exc}")

    with pytest.raises(OSError):
        store.add(_rec(username="second"))
    assert sentinel.read_text(encoding="utf-8") == "host-only"


def test_encryption_failure_never_writes_plaintext(monkeypatch, tmp_path):
    """A transient crypto failure cannot use plaintext fallback after the write gate."""
    monkeypatch.setenv("BREACHPILOT_VAULT_KEY", Fernet.generate_key().decode())
    store = CredentialStore(tmp_path)

    class BrokenFernet:
        @staticmethod
        def encrypt(_plaintext: bytes) -> bytes:
            raise ValueError("simulated crypto failure")

    store._vault._fernet = BrokenFernet()
    with pytest.raises(RuntimeError, match="refusing plaintext write"):
        store.add(_rec(password=_CLEARTEXT))
    assert store.all_credentials() == []
    assert not (tmp_path / "credentials.jsonl").exists()
