"""Category modules re-exports."""

from tools.attack_modules.modules.web import (
    Log4jRCE,
    BasicAuthBuster,
    APIFuzzer,
    WebShellUpload,
    SQLInjection,
    XSSScanner,
    SSTIProbe,
    GraphQLIntrospect,
    RaceRequest,
    TimingOracle,
    RequestSmuggling,
    SSRFProbe,
    XXEProbe,
    LFITraversal,
)
from tools.attack_modules.modules.network_smb import (
    SMBGhost,
    EternalBlue,
    SMBRelay,
    SMBNullSession,
    PassTheHash,
    DumpHashes,
)
from tools.attack_modules.modules.ssh import (
    SSHBruteForce,
    RegreSSHion,
    OpenSSHCVECheck,
)
from tools.attack_modules.modules.services import (
    RDPBlueKeep,
    FTPAnonymous,
    RedisExploit,
    ElasticsearchExploit,
    LDAPAnonymous,
    RDPExploit,
)
from tools.attack_modules.modules.auth_creds import (
    CredentialSpray,
    PasswordSpray,
    HashCrack,
    ASREPRoast,
    Kerberoasting,
    DCSyncAttack,
    ADLDAPEnum,
)
from tools.attack_modules.modules.privesc import (
    LinuxPrivescCheck,
    WindowsPrivescCheck,
    SUIDEnumeration,
    KernelExploitCheck,
    ContainerBreakout,
    CloudPrivesc,
    K8sPrivesc,
)
from tools.attack_modules.modules.persistence import (
    LinuxPersistence,
    WindowsPersistence,
    WebShellPersistence,
)
from tools.attack_modules.modules.crypto_jwt import JWTTamper
from tools.attack_modules.modules.deserialize import DeserializeAttack
from tools.attack_modules.modules.synthesis import (
    CVEToExploit,
    DiffPatchAnalysis,
    FuzzToExploit,
    WeaponizedExploit,
)
from tools.attack_modules.modules.ics_iot import (
    ModbusEnum,
    DNP3Enum,
    S7Enum,
    BACnetEnum,
    HMIDefaultCred,
    IoTDefaultCred,
)
from tools.attack_modules.modules.supply_chain import (
    ExposedVCS,
    CICDMisconfig,
    DependencyConfusion,
    ArtifactExposure,
    SupplyChainRecon,
)
from tools.attack_modules.modules.detection import (
    DetectionCoverageProbe,
    LogSourceEnum,
    OPSECPostureReport,
)

__all__ = [
    "Log4jRCE",
    "SMBGhost",
    "EternalBlue",
    "BasicAuthBuster",
    "APIFuzzer",
    "RDPBlueKeep",
    "SSHBruteForce",
    "RegreSSHion",
    "OpenSSHCVECheck",
    "SMBRelay",
    "SMBNullSession",
    "WebShellUpload",
    "SQLInjection",
    "XSSScanner",
    "CredentialSpray",
    "LinuxPrivescCheck",
    "WindowsPrivescCheck",
    "SUIDEnumeration",
    "KernelExploitCheck",
    "ContainerBreakout",
    "LinuxPersistence",
    "WindowsPersistence",
    "WebShellPersistence",
    "FTPAnonymous",
    "RedisExploit",
    "ElasticsearchExploit",
    "LDAPAnonymous",
    "RDPExploit",
    "JWTTamper",
    "SSTIProbe",
    "DeserializeAttack",
    "GraphQLIntrospect",
    "RaceRequest",
    "TimingOracle",
    "RequestSmuggling",
    "PasswordSpray",
    "HashCrack",
    "PassTheHash",
    "DumpHashes",
    "CVEToExploit",
    "DiffPatchAnalysis",
    "FuzzToExploit",
    "SSRFProbe",
    "XXEProbe",
    "LFITraversal",
    "ASREPRoast",
    "Kerberoasting",
    "DCSyncAttack",
    "ADLDAPEnum",
    "WeaponizedExploit",
    "CloudPrivesc",
    "K8sPrivesc",
    "ModbusEnum",
    "DNP3Enum",
    "S7Enum",
    "BACnetEnum",
    "HMIDefaultCred",
    "IoTDefaultCred",
    "ExposedVCS",
    "CICDMisconfig",
    "DependencyConfusion",
    "ArtifactExposure",
    "SupplyChainRecon",
    "DetectionCoverageProbe",
    "LogSourceEnum",
    "OPSECPostureReport",
]
