// Presentation metadata for the settings page. The backend config schema is
// the source of truth for what exists; this file only decorates it with
// friendly labels, descriptions, categories, and control hints. Unknown
// properties (no entry here) still render automatically under Advanced with
// their raw config key.

export type SettingCategory = "general" | "ai" | "runs" | "features" | "integrations" | "advanced";

export interface SettingMeta {
  label: string;
  description?: string;
  category: SettingCategory;
  group?: string;
  order?: number;
  dependsOn?: string;
  /** Hidden under "Show advanced settings" within its category. */
  advanced?: boolean;
  /** Enumerated values â†’ rendered as a select. May be a function of the draft
   *  for dynamic options (e.g. default model = registry keys). */
  options?: string[] | ((draft: Record<string, unknown>) => string[]);
  placeholder?: string;
  /** Rendered as a password input. */
  secret?: boolean;
  /** Never rendered (e.g. token_file). */
  hide?: boolean;
}

export const CATEGORY_LABELS: Record<SettingCategory, string> = {
  general: "General",
  ai: "AI & Models",
  runs: "Runs & Scanning",
  features: "Features",
  integrations: "Notifications & Integrations",
  advanced: "Advanced",
};

export const CATEGORY_DESCRIPTIONS: Record<SettingCategory, string> = {
  general: "Common application configuration.",
  ai: "Provider, models, and API keys.",
  runs: "Execution, scanning, and run-time behavior.",
  features: "Optional subsystems you can turn on or off.",
  integrations: "External integrations and notifications.",
  advanced: "Technical configuration, diagnostics, and system information.",
};

/** Default category for a schema section. Sections not listed here (and
 *  fields without explicit meta) fall through to "advanced". */
export const SECTION_CATEGORY: Record<string, SettingCategory> = {
  adaptive_exploits: "features",
  agent: "advanced",
  api: "advanced",
  autonomous: "advanced",
  benchmark: "advanced",
  browser: "advanced",
  caldera: "integrations",
  chatgpt: "ai",
  cve_lookup: "features",
  engine_mcp: "advanced",
  eval: "advanced",
  exploit: "runs",
  ics: "advanced",
  killchain: "advanced",
  long_session: "runs",
  mcp: "advanced",
  memory: "features",
  mitre: "integrations",
  models: "ai",
  multi_model: "features",
  nmap: "runs",
  ollama: "ai",
  opencode_go: "ai",
  operator_connection: "advanced",
  opsec: "runs",
  orchestrator: "advanced",
  outcome_judgment: "advanced",
  plugins: "features",
  poc_verification: "advanced",
  reasoning: "ai",
  recon: "runs",
  replay_simulator: "advanced",
  research: "features",
  sandbox: "advanced",
  skills: "features",
  snapshots: "advanced",
  stealth: "advanced",
  swarm: "features",
  threat_intel: "features",
  ticketing: "integrations",
  webhook_notify: "integrations",
  witness: "features",
};

export const SECTION_LABELS: Record<string, string> = {
  adaptive_exploits: "Adaptive exploits",
  agent: "Agent",
  api: "WebUI",
  autonomous: "Autonomous orchestrator",
  benchmark: "Benchmark",
  browser: "Browser agent",
  caldera: "Caldera",
  chatgpt: "ChatGPT",
  cve_lookup: "CVE lookup",
  engine_mcp: "Engine MCP",
  eval: "Eval harness",
  exploit: "Exploit engine",
  ics: "ICS",
  killchain: "Killchain",
  long_session: "Long session",
  mcp: "MCP",
  memory: "Memory",
  mitre: "MITRE ATT&CK",
  models: "Models",
  multi_model: "Multi-model",
  nmap: "Nmap",
  ollama: "Ollama",
  opencode_go: "OpenCode Go",
  operator_connection: "Operator connection",
  opsec: "OPSEC",
  orchestrator: "Orchestrator",
  outcome_judgment: "Outcome judgment",
  plugins: "Plugins",
  poc_verification: "PoC verification",
  reasoning: "Reasoning",
  recon: "Recon",
  replay_simulator: "Replay simulator",
  research: "Web research",
  sandbox: "Sandbox",
  skills: "Skills",
  snapshots: "Snapshots",
  stealth: "Stealth (legacy)",
  swarm: "Swarm",
  threat_intel: "Threat intel",
  ticketing: "Remediation tickets",
  webhook_notify: "Webhook notifications",
  witness: "Witness agent",
};

const registryKeys = (draft: Record<string, unknown>): string[] => {
  const registry = (draft.models as Record<string, unknown> | undefined)?.registry;
  if (registry && typeof registry === "object") return Object.keys(registry as Record<string, unknown>);
  return [];
};

export const SETTING_META: Record<string, SettingMeta> = {
  // â”€â”€ AI & Models â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  // -- chatgpt / ChatGPT --
  "chatgpt.enabled": {
    label: "ChatGPT provider",
    category: "ai",
    group: "ChatGPT",
    order: 1,
  },
  // -- models / Models --
  "models.auto_update": {
    label: "Auto Update",
    category: "ai",
    group: "Registry",
    order: 1,
    advanced: true,
  },
  "models.default_alias": {
    label: "Default model",
    description: "Model alias used when no model is chosen for a run.",
    category: "ai",
    group: "Registry",
    order: 2,
    hide: true,
    options: registryKeys,
  },
  "models.info.deepseek.context_window": {
    label: "Info.deepseek.context Window",
    category: "ai",
    group: "Info",
    order: 3,
    advanced: true,
  },
  "models.info.deepseek.description": {
    label: "Info.deepseek.description",
    category: "ai",
    group: "Info",
    order: 4,
    advanced: true,
  },
  "models.info.deepseek.label": {
    label: "Info.deepseek.label",
    category: "ai",
    group: "Info",
    order: 5,
    advanced: true,
  },
  "models.info.deepseek_flash.context_window": {
    label: "Info.deepseek Flash.context Window",
    category: "ai",
    group: "Info",
    order: 6,
    advanced: true,
  },
  "models.info.deepseek_flash.description": {
    label: "Info.deepseek Flash.description",
    category: "ai",
    group: "Info",
    order: 7,
    advanced: true,
  },
  "models.info.deepseek_flash.label": {
    label: "Info.deepseek Flash.label",
    category: "ai",
    group: "Info",
    order: 8,
    advanced: true,
  },
  "models.info.glm.context_window": {
    label: "Info.glm.context Window",
    category: "ai",
    group: "Info",
    order: 9,
    advanced: true,
  },
  "models.info.glm.description": {
    label: "Info.glm.description",
    category: "ai",
    group: "Info",
    order: 10,
    advanced: true,
  },
  "models.info.glm.label": {
    label: "Info.glm.label",
    category: "ai",
    group: "Info",
    order: 11,
    advanced: true,
  },
  "models.info.kimi.context_window": {
    label: "Info.kimi.context Window",
    category: "ai",
    group: "Info",
    order: 12,
    advanced: true,
  },
  "models.info.kimi.description": {
    label: "Info.kimi.description",
    category: "ai",
    group: "Info",
    order: 13,
    advanced: true,
  },
  "models.info.kimi.label": {
    label: "Info.kimi.label",
    category: "ai",
    group: "Info",
    order: 14,
    advanced: true,
  },
  "models.info.minimax.context_window": {
    label: "Info.minimax.context Window",
    category: "ai",
    group: "Info",
    order: 15,
    advanced: true,
  },
  "models.info.minimax.description": {
    label: "Info.minimax.description",
    category: "ai",
    group: "Info",
    order: 16,
    advanced: true,
  },
  "models.info.minimax.label": {
    label: "Info.minimax.label",
    category: "ai",
    group: "Info",
    order: 17,
    advanced: true,
  },
  "models.provider": {
    label: "Provider",
    category: "ai",
    group: "Registry",
    order: 18,
    options: ["ollama", "chatgpt"],
  },
  "models.registry.deepseek": {
    label: "Registry.deepseek",
    category: "ai",
    group: "Registry",
    order: 19,
    advanced: true,
  },
  "models.registry.deepseek_flash": {
    label: "Registry.deepseek Flash",
    category: "ai",
    group: "Registry",
    order: 20,
    advanced: true,
  },
  "models.registry.glm": {
    label: "Registry.glm",
    category: "ai",
    group: "Registry",
    order: 21,
    advanced: true,
  },
  "models.registry.kimi": {
    label: "Registry.kimi",
    category: "ai",
    group: "Registry",
    order: 22,
    advanced: true,
  },
  "models.registry.minimax": {
    label: "Registry.minimax",
    category: "ai",
    group: "Registry",
    order: 23,
    advanced: true,
  },
  "models.roles.code_generator": {
    label: "Roles.code Generator",
    category: "ai",
    group: "Roles",
    order: 24,
    advanced: true,
  },
  "models.roles.critic": {
    label: "Roles.critic",
    category: "ai",
    group: "Roles",
    order: 25,
    advanced: true,
  },
  "models.roles.executor": {
    label: "Roles.executor",
    category: "ai",
    group: "Roles",
    order: 26,
    advanced: true,
  },
  "models.roles.interpreter": {
    label: "Roles.interpreter",
    category: "ai",
    group: "Roles",
    order: 27,
    advanced: true,
  },
  "models.roles.planner": {
    label: "Roles.planner",
    category: "ai",
    group: "Roles",
    order: 28,
    advanced: true,
  },
  "models.roles.summarizer": {
    label: "Roles.summarizer",
    category: "ai",
    group: "Roles",
    order: 29,
    advanced: true,
  },
  // -- ollama / Ollama --
  "ollama.api_key_env": {
    label: "Ollama API key env var",
    category: "ai",
    group: "Connection",
    order: 1,
    advanced: true,
  },
  "ollama.embed_host": {
    label: "Embeddings host",
    category: "ai",
    group: "Connection",
    order: 2,
    advanced: true,
  },
  "ollama.host": {
    label: "Ollama host",
    description: "Base URL for the Ollama API.",
    category: "ai",
    group: "Connection",
    order: 3,
  },
  "ollama.model": {
    label: "Ollama model",
    category: "ai",
    group: "Connection",
    order: 4,
  },
  // -- opencode_go / OpenCode Go --
  "opencode_go.api_key_env": {
    label: "API Key Env",
    category: "ai",
    group: "OpenCode Go",
    order: 1,
    dependsOn: "opencode_go.enabled",
    advanced: true,
    secret: true,
  },
  "opencode_go.base_url": {
    label: "Base URL",
    category: "ai",
    group: "OpenCode Go",
    order: 2,
    dependsOn: "opencode_go.enabled",
    advanced: true,
  },
  "opencode_go.context_window": {
    label: "Context Window",
    category: "ai",
    group: "OpenCode Go",
    order: 3,
    dependsOn: "opencode_go.enabled",
    advanced: true,
  },
  "opencode_go.default_model": {
    label: "Default Model",
    category: "ai",
    group: "OpenCode Go",
    order: 4,
    dependsOn: "opencode_go.enabled",
    advanced: true,
  },
  "opencode_go.discover_cache_seconds": {
    label: "Discover Cache (s)",
    category: "ai",
    group: "OpenCode Go",
    order: 5,
    dependsOn: "opencode_go.enabled",
    advanced: true,
  },
  "opencode_go.enabled": {
    label: "Enabled",
    category: "ai",
    group: "OpenCode Go",
    order: 6,
  },
  "opencode_go.models": {
    label: "Models",
    category: "ai",
    group: "OpenCode Go",
    order: 7,
    dependsOn: "opencode_go.enabled",
    advanced: true,
  },
  "opencode_go.request_timeout_seconds": {
    label: "Request Timeout Seconds (s)",
    category: "ai",
    group: "OpenCode Go",
    order: 8,
    dependsOn: "opencode_go.enabled",
    advanced: true,
  },
  // -- reasoning / Reasoning --
  "reasoning.chain_of_thought": {
    label: "Chain of thought",
    category: "ai",
    group: "Cognition",
    order: 1,
  },
  "reasoning.critic_enabled": {
    label: "Critic",
    category: "ai",
    group: "Cognition",
    order: 2,
  },
  "reasoning.llm_reflection": {
    label: "LLM reflection",
    category: "ai",
    group: "Cognition",
    order: 3,
    advanced: true,
  },
  "reasoning.observer_mode": {
    label: "Observer mode",
    category: "ai",
    group: "Cognition",
    order: 4,
    options: ["heuristic", "llm", "hybrid"],
  },
  "reasoning.peer_consult_on_failure_threshold": {
    label: "Peer consult threshold",
    category: "ai",
    group: "Cognition",
    order: 5,
    advanced: true,
  },
  "reasoning.reflection_every_n_actions": {
    label: "Reflect every N actions",
    category: "ai",
    group: "Cognition",
    order: 6,
  },
  "reasoning.ultrathink": {
    label: "Ultrathink",
    category: "ai",
    group: "Cognition",
    order: 7,
  },
  "reasoning.ultrathink_reflection_interval": {
    label: "Ultrathink reflection interval",
    category: "ai",
    group: "Cognition",
    order: 8,
    advanced: true,
  },
  // â”€â”€ Runs & Scanning â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  // -- exploit / Exploit engine --
  "exploit.ad_kerberos.adcs_enum": {
    label: "AD Kerberos.adcs Enum",
    category: "runs",
    group: "AD Kerberos",
    order: 1,
    dependsOn: "exploit.ad_kerberos.enabled",
    advanced: true,
  },
  "exploit.ad_kerberos.asrep_roast": {
    label: "AD Kerberos.asrep Roast",
    category: "runs",
    group: "AD Kerberos",
    order: 2,
    dependsOn: "exploit.ad_kerberos.enabled",
    advanced: true,
  },
  "exploit.ad_kerberos.bloodhound": {
    label: "AD Kerberos.bloodhound",
    category: "runs",
    group: "AD Kerberos",
    order: 3,
    dependsOn: "exploit.ad_kerberos.enabled",
    advanced: true,
  },
  "exploit.ad_kerberos.enabled": {
    label: "AD Kerberos.enabled",
    category: "runs",
    group: "AD Kerberos",
    order: 4,
    dependsOn: "exploit.enabled",
  },
  "exploit.ad_kerberos.golden_ticket": {
    label: "AD Kerberos.golden Ticket",
    category: "runs",
    group: "AD Kerberos",
    order: 5,
    dependsOn: "exploit.ad_kerberos.enabled",
    advanced: true,
  },
  "exploit.ad_kerberos.pass_the_hash": {
    label: "AD Kerberos.pass The Hash",
    category: "runs",
    group: "AD Kerberos",
    order: 6,
    dependsOn: "exploit.ad_kerberos.enabled",
    advanced: true,
  },
  "exploit.ad_kerberos.responder_relay": {
    label: "AD Kerberos.responder Relay",
    category: "runs",
    group: "AD Kerberos",
    order: 7,
    dependsOn: "exploit.ad_kerberos.enabled",
    advanced: true,
  },
  "exploit.ad_kerberos.smb_signing_check": {
    label: "AD Kerberos.smb Signing Check",
    category: "runs",
    group: "AD Kerberos",
    order: 8,
    dependsOn: "exploit.ad_kerberos.enabled",
    advanced: true,
  },
  "exploit.allowed_targets": {
    label: "Allowed targets",
    category: "runs",
    group: "Engine",
    order: 9,
    dependsOn: "exploit.enabled",
  },
  "exploit.attack_max_commands": {
    label: "Max commands per assessment",
    description: "Stop an assessment after this many commands.",
    category: "runs",
    group: "Limits",
    order: 30,
  },
  "exploit.attack_max_duration_minutes": {
    label: "Attack max duration (min)",
    category: "runs",
    group: "Engine",
    order: 11,
    dependsOn: "exploit.enabled",
  },
  "exploit.attack_max_rounds": {
    label: "Attack max rounds",
    category: "runs",
    group: "Engine",
    order: 12,
    dependsOn: "exploit.enabled",
  },
  "exploit.attack_mode": {
    label: "Attack mode",
    category: "runs",
    group: "Engine",
    order: 13,
    dependsOn: "exploit.enabled",
  },
  "exploit.attacker_os": {
    label: "Attacker OS",
    category: "runs",
    group: "Engine",
    order: 14,
    dependsOn: "exploit.enabled",
    options: ["auto", "linux", "windows"],
  },
  "exploit.auto_post_exploit": {
    label: "Auto post-exploit",
    category: "runs",
    group: "Engine",
    order: 15,
    dependsOn: "exploit.enabled",
  },
  "exploit.cache_max_entries": {
    label: "Cache max entries",
    category: "runs",
    group: "Engine",
    order: 16,
    dependsOn: "exploit.enabled",
  },
  "exploit.cache_ttl_seconds": {
    label: "Cache TTL (s)",
    category: "runs",
    group: "Engine",
    order: 17,
    dependsOn: "exploit.enabled",
  },
  "exploit.command_timeout_seconds": {
    label: "Command timeout (s)",
    category: "runs",
    group: "Engine",
    order: 18,
    dependsOn: "exploit.enabled",
  },
  "exploit.context_summarize_every": {
    label: "Context summarize every",
    category: "runs",
    group: "Engine",
    order: 19,
    dependsOn: "exploit.enabled",
  },
  "exploit.disallowed_assets": {
    label: "Disallowed assets",
    category: "runs",
    group: "Engine",
    order: 20,
    dependsOn: "exploit.enabled",
  },
  "exploit.enabled": {
    label: "Exploit engine",
    category: "runs",
    group: "Engine",
    order: 21,
  },
  "exploit.forbidden_actions": {
    label: "Forbidden actions",
    category: "runs",
    group: "Engine",
    order: 22,
    dependsOn: "exploit.enabled",
  },
  "exploit.listeners.dns": {
    label: "Listeners.dns",
    category: "runs",
    group: "Listeners",
    order: 23,
    dependsOn: "exploit.enabled",
    advanced: true,
  },
  "exploit.listeners.https_beacon": {
    label: "Listeners.https Beacon",
    category: "runs",
    group: "Listeners",
    order: 24,
    dependsOn: "exploit.enabled",
    advanced: true,
  },
  "exploit.listeners.socks_pivot": {
    label: "Listeners.socks Pivot",
    category: "runs",
    group: "Listeners",
    order: 25,
    dependsOn: "exploit.enabled",
    advanced: true,
  },
  "exploit.listeners.tls": {
    label: "Listeners.tls",
    category: "runs",
    group: "Listeners",
    order: 26,
    dependsOn: "exploit.enabled",
    advanced: true,
  },
  "exploit.loot_workspace": {
    label: "Loot Workspace",
    category: "runs",
    group: "Engine",
    order: 27,
    dependsOn: "exploit.enabled",
    advanced: true,
  },
  "exploit.max_commands_per_session": {
    label: "Max commands per session",
    category: "runs",
    group: "Engine",
    order: 28,
    dependsOn: "exploit.enabled",
  },
  "exploit.max_pivot_depth": {
    label: "Max pivot depth",
    category: "runs",
    group: "Engine",
    order: 29,
    dependsOn: "exploit.enabled",
  },
  "exploit.max_query_chars": {
    label: "Max query chars",
    category: "runs",
    group: "Engine",
    order: 30,
    dependsOn: "exploit.enabled",
  },
  "exploit.max_rounds": {
    label: "Max rounds",
    category: "runs",
    group: "Engine",
    order: 31,
    dependsOn: "exploit.enabled",
  },
  "exploit.mode": {
    label: "Mode",
    category: "runs",
    group: "Engine",
    order: 32,
    dependsOn: "exploit.enabled",
    advanced: true,
  },
  "exploit.msf.auto_local_exploit_suggester": {
    label: "MSF.auto Local Exploit Suggester",
    category: "runs",
    group: "MSF",
    order: 33,
    dependsOn: "exploit.enabled",
    advanced: true,
  },
  "exploit.msf.recipes_enabled": {
    label: "MSF.recipes Enabled",
    category: "runs",
    group: "MSF",
    order: 34,
    dependsOn: "exploit.enabled",
    advanced: true,
  },
  "exploit.msfconsole_path": {
    label: "msfconsole path",
    category: "runs",
    group: "Engine",
    order: 35,
    dependsOn: "exploit.enabled",
  },
  "exploit.permission": {
    label: "Exploit permission",
    description: "full_access auto-approves every action; read_only proposes only.",
    category: "runs",
    group: "Engine",
    order: 36,
    dependsOn: "exploit.enabled",
    options: ["read_only", "approve_only", "full_access"],
  },
  "exploit.require_explicit_allowlist": {
    label: "Require explicit allowlist",
    category: "runs",
    group: "Engine",
    order: 37,
    dependsOn: "exploit.enabled",
  },
  "exploit.searchsploit_path": {
    label: "searchsploit path",
    category: "runs",
    group: "Engine",
    order: 38,
    dependsOn: "exploit.enabled",
  },
  "exploit.shell": {
    label: "Shell",
    category: "runs",
    group: "Engine",
    order: 39,
    dependsOn: "exploit.enabled",
  },
  "exploit.terminal": {
    label: "Terminal",
    category: "runs",
    group: "Engine",
    order: 40,
    dependsOn: "exploit.enabled",
    options: ["visible", "hidden"],
  },
  "exploit.web_search": {
    label: "Web search",
    category: "runs",
    group: "Engine",
    order: 41,
    dependsOn: "exploit.enabled",
  },
  "exploit.workspace_dir": {
    label: "Workspace dir",
    category: "runs",
    group: "Engine",
    order: 42,
    dependsOn: "exploit.enabled",
  },
  // -- long_session / Long session --
  "long_session.attack_max_commands": {
    label: "Attack max commands",
    category: "runs",
    group: "Persistence",
    order: 1,
    dependsOn: "long_session.enabled",
    advanced: true,
  },
  "long_session.attack_max_duration_minutes": {
    label: "Attack max duration (min)",
    category: "runs",
    group: "Persistence",
    order: 2,
    dependsOn: "long_session.enabled",
    advanced: true,
  },
  "long_session.attack_max_rounds": {
    label: "Attack max rounds",
    category: "runs",
    group: "Persistence",
    order: 3,
    dependsOn: "long_session.enabled",
    advanced: true,
  },
  "long_session.enabled": {
    label: "Long session",
    category: "runs",
    group: "Persistence",
    order: 4,
  },
  "long_session.persist_messages": {
    label: "Persist messages",
    category: "runs",
    group: "Persistence",
    order: 5,
    dependsOn: "long_session.enabled",
    advanced: true,
  },
  "long_session.request_timeout_seconds": {
    label: "Request timeout (s)",
    category: "runs",
    group: "Persistence",
    order: 6,
    dependsOn: "long_session.enabled",
    advanced: true,
  },
  "long_session.swarm_session_timeout_minutes": {
    label: "Swarm session timeout (min)",
    category: "runs",
    group: "Persistence",
    order: 7,
    dependsOn: "long_session.enabled",
    advanced: true,
  },
  // -- nmap / Nmap --
  "nmap.path": {
    label: "Nmap binary path",
    description: "Path to the Nmap executable. Leave as 'nmap' if it is on your PATH.",
    category: "runs",
    group: "Scanning",
    order: 20,
    advanced: true,
  },
  "nmap.priv_fallback": {
    label: "Auto-downgrade privileged flags",
    description: "Drop -O / -sS instead of failing when unprivileged.",
    category: "runs",
    group: "Scanner",
    order: 2,
    advanced: true,
  },
  "nmap.sudo": {
    label: "Use privileged scanning",
    description: "Run Nmap with sudo for OS detection and SYN scans on Linux.",
    category: "general",
    group: "Scanning",
    order: 10,
  },
  // -- opsec / OPSEC --
  "opsec.doh": {
    label: "DNS over HTTPS",
    category: "runs",
    group: "Stealth",
    order: 1,
    dependsOn: "opsec.enabled",
  },
  "opsec.doh_provider": {
    label: "DoH provider",
    category: "runs",
    group: "Stealth",
    order: 2,
    dependsOn: "opsec.enabled",
    options: ["cloudflare", "google"],
  },
  "opsec.enabled": {
    label: "Stealth mode",
    description: "Slow down and randomise traffic to look less like a scan.",
    category: "runs",
    group: "Stealth",
    order: 10,
  },
  "opsec.jitter_seconds": {
    label: "Jitter (s)",
    category: "runs",
    group: "Stealth",
    order: 4,
    dependsOn: "opsec.enabled",
  },
  "opsec.local_cidrs": {
    label: "Local CIDRs",
    category: "runs",
    group: "Stealth",
    order: 5,
    dependsOn: "opsec.enabled",
  },
  "opsec.local_targets_off": {
    label: "Disable for local targets",
    category: "runs",
    group: "Stealth",
    order: 6,
    dependsOn: "opsec.enabled",
  },
  "opsec.min_gap_seconds": {
    label: "Min gap (s)",
    category: "runs",
    group: "Stealth",
    order: 7,
    dependsOn: "opsec.enabled",
  },
  "opsec.noise_budget": {
    label: "Noise budget",
    category: "runs",
    group: "Stealth",
    order: 8,
    dependsOn: "opsec.enabled",
  },
  "opsec.public_autonomy": {
    label: "Public target autonomy",
    category: "runs",
    group: "Stealth",
    order: 9,
    dependsOn: "opsec.enabled",
  },
  "opsec.quiet_command_patterns": {
    label: "Quiet command patterns",
    category: "runs",
    group: "Stealth",
    order: 10,
    dependsOn: "opsec.enabled",
  },
  "opsec.rate_per_minute": {
    label: "Rate per minute",
    category: "runs",
    group: "Stealth",
    order: 11,
    dependsOn: "opsec.enabled",
  },
  "opsec.ua_rotation": {
    label: "User-Agent rotation",
    category: "runs",
    group: "Stealth",
    order: 12,
    dependsOn: "opsec.enabled",
  },
  // -- recon / Recon --
  "recon.asn_whois": {
    label: "ASN / WHOIS",
    category: "runs",
    group: "Enumeration",
    order: 1,
  },
  "recon.cloud_metadata_probe": {
    label: "Cloud metadata probe",
    category: "runs",
    group: "Enumeration",
    order: 2,
  },
  "recon.dns_zone_transfer": {
    label: "DNS zone transfer",
    category: "runs",
    group: "Enumeration",
    order: 3,
  },
  "recon.domain_resolution.dns_zone_transfer": {
    label: "Domain Resolution.dns Zone Transfer",
    category: "runs",
    group: "Domain Resolution",
    order: 4,
    dependsOn: "recon.domain_resolution.enabled",
    advanced: true,
  },
  "recon.domain_resolution.enabled": {
    label: "Domain Resolution.enabled",
    category: "runs",
    group: "Domain Resolution",
    order: 5,
  },
  "recon.domain_resolution.max_subdomains": {
    label: "Domain Resolution.max Subdomains",
    category: "runs",
    group: "Domain Resolution",
    order: 6,
    dependsOn: "recon.domain_resolution.enabled",
    advanced: true,
  },
  "recon.domain_resolution.subdomain_sources": {
    label: "Domain Resolution.subdomain Sources",
    category: "runs",
    group: "Domain Resolution",
    order: 7,
    dependsOn: "recon.domain_resolution.enabled",
    advanced: true,
  },
  "recon.domain_resolution.whois_enabled": {
    label: "Domain Resolution.whois Enabled",
    category: "runs",
    group: "Domain Resolution",
    order: 8,
    dependsOn: "recon.domain_resolution.enabled",
    advanced: true,
  },
  "recon.extended_enumerators": {
    label: "Extended enumerators",
    category: "runs",
    group: "Enumeration",
    order: 9,
  },
  "recon.fast.cache_ttl_seconds": {
    label: "Fast.cache Ttl (s)",
    category: "runs",
    group: "Fast",
    order: 10,
    dependsOn: "recon.fast.enabled",
    advanced: true,
  },
  "recon.fast.cve_concurrency": {
    label: "Fast.cve Concurrency",
    category: "runs",
    group: "Fast",
    order: 11,
    dependsOn: "recon.fast.enabled",
    advanced: true,
  },
  "recon.fast.cve_lookup": {
    label: "Fast.cve Lookup",
    category: "runs",
    group: "Fast",
    order: 12,
    dependsOn: "recon.fast.enabled",
    advanced: true,
  },
  "recon.fast.enabled": {
    label: "Fast.enabled",
    category: "runs",
    group: "Fast",
    order: 13,
  },
  "recon.fast.max_concurrency": {
    label: "Fast.max Concurrency",
    category: "runs",
    group: "Fast",
    order: 14,
    dependsOn: "recon.fast.enabled",
    advanced: true,
  },
  "recon.fast.overall_timeout_seconds": {
    label: "Fast.overall Timeout Seconds (s)",
    category: "runs",
    group: "Fast",
    order: 15,
    dependsOn: "recon.fast.enabled",
    advanced: true,
  },
  "recon.fast.passive_osint": {
    label: "Fast.passive Osint",
    category: "runs",
    group: "Fast",
    order: 16,
    dependsOn: "recon.fast.enabled",
    advanced: true,
  },
  "recon.fast.per_task_timeout_seconds": {
    label: "Fast.per Task Timeout Seconds (s)",
    category: "runs",
    group: "Fast",
    order: 17,
    dependsOn: "recon.fast.enabled",
    advanced: true,
  },
  "recon.fast.service_concurrency": {
    label: "Fast.service Concurrency",
    category: "runs",
    group: "Fast",
    order: 18,
    dependsOn: "recon.fast.enabled",
    advanced: true,
  },
  "recon.fast.service_enumeration": {
    label: "Fast.service Enumeration",
    category: "runs",
    group: "Fast",
    order: 19,
    dependsOn: "recon.fast.enabled",
    advanced: true,
  },
  "recon.fast.tcp_discovery": {
    label: "Fast.tcp Discovery",
    category: "runs",
    group: "Fast",
    order: 20,
    dependsOn: "recon.fast.enabled",
    advanced: true,
  },
  "recon.fast.udp_top_ports": {
    label: "Fast.udp Top Ports",
    category: "runs",
    group: "Fast",
    order: 21,
    dependsOn: "recon.fast.enabled",
    advanced: true,
  },
  "recon.max_retries": {
    label: "Max Retries",
    category: "runs",
    group: "Enumeration",
    order: 22,
    advanced: true,
  },
  "recon.preflight_ports": {
    label: "Preflight Ports",
    category: "runs",
    group: "Enumeration",
    order: 23,
    advanced: true,
  },
  "recon.preflight_probe": {
    label: "Preflight Probe",
    category: "runs",
    group: "Enumeration",
    order: 24,
    advanced: true,
  },
  "recon.preflight_timeout_ms": {
    label: "Preflight Timeout (ms)",
    category: "runs",
    group: "Enumeration",
    order: 25,
    advanced: true,
  },
  "recon.retry_delay": {
    label: "Retry Delay",
    category: "runs",
    group: "Enumeration",
    order: 26,
    advanced: true,
  },
  "recon.shodan_api_key": {
    label: "Shodan API key",
    category: "runs",
    group: "Enumeration",
    order: 27,
    secret: true,
  },
  "recon.snmp_enum": {
    label: "SNMP enumeration",
    category: "runs",
    group: "Enumeration",
    order: 28,
  },
  "recon.subdomain_enum": {
    label: "Subdomain enumeration",
    category: "runs",
    group: "Enumeration",
    order: 29,
  },
  "recon.timeout_seconds": {
    label: "Timeout Seconds (s)",
    category: "runs",
    group: "Enumeration",
    order: 30,
    advanced: true,
  },
  "recon.udp_top_ports": {
    label: "UDP top ports",
    category: "runs",
    group: "Enumeration",
    order: 31,
  },
  "recon.vhost_discovery": {
    label: "Vhost discovery",
    category: "runs",
    group: "Enumeration",
    order: 32,
  },
  "recon.waf_fingerprint": {
    label: "WAF fingerprinting",
    category: "runs",
    group: "Enumeration",
    order: 33,
  },
  // â”€â”€ Features â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  // -- adaptive_exploits / Adaptive exploits --
  "adaptive_exploits.enabled": {
    label: "Adaptive exploits",
    category: "features",
    group: "Adaptive",
    order: 1,
  },
  "adaptive_exploits.max_mutations": {
    label: "Max mutations",
    category: "features",
    group: "Adaptive",
    order: 2,
    dependsOn: "adaptive_exploits.enabled",
    advanced: true,
  },
  "adaptive_exploits.mutation_strategies": {
    label: "Mutation strategies",
    category: "features",
    group: "Adaptive",
    order: 3,
    dependsOn: "adaptive_exploits.enabled",
    advanced: true,
  },
  // -- cve_lookup / CVE lookup --
  "cve_lookup.api_key_env": {
    label: "NVD API key env",
    category: "features",
    group: "CVE",
    order: 1,
    dependsOn: "cve_lookup.enabled",
    secret: true,
  },
  "cve_lookup.cache_max_entries": {
    label: "Cache max entries",
    category: "features",
    group: "CVE",
    order: 2,
    dependsOn: "cve_lookup.enabled",
  },
  "cve_lookup.cache_ttl_seconds": {
    label: "Cache TTL (s)",
    category: "features",
    group: "CVE",
    order: 3,
    dependsOn: "cve_lookup.enabled",
  },
  "cve_lookup.circuit_failure_threshold": {
    label: "Circuit failure threshold",
    category: "features",
    group: "CVE",
    order: 4,
    dependsOn: "cve_lookup.enabled",
  },
  "cve_lookup.circuit_recovery_timeout": {
    label: "Circuit recovery timeout",
    category: "features",
    group: "CVE",
    order: 5,
    dependsOn: "cve_lookup.enabled",
  },
  "cve_lookup.enabled": {
    label: "CVE lookup",
    category: "features",
    group: "CVE",
    order: 6,
  },
  "cve_lookup.epss_enabled": {
    label: "EPSS enrichment",
    category: "features",
    group: "CVE",
    order: 7,
    dependsOn: "cve_lookup.enabled",
  },
  "cve_lookup.github.token_env": {
    label: "Github.token Env",
    category: "features",
    group: "Github",
    order: 8,
    dependsOn: "cve_lookup.enabled",
    advanced: true,
    secret: true,
  },
  "cve_lookup.kev_cache_path": {
    label: "KEV cache path",
    category: "features",
    group: "CVE",
    order: 9,
    dependsOn: "cve_lookup.enabled",
  },
  "cve_lookup.kev_cache_ttl_seconds": {
    label: "KEV cache TTL (s)",
    category: "features",
    group: "CVE",
    order: 10,
    dependsOn: "cve_lookup.enabled",
  },
  "cve_lookup.kev_enabled": {
    label: "KEV enrichment",
    category: "features",
    group: "CVE",
    order: 11,
    dependsOn: "cve_lookup.enabled",
  },
  "cve_lookup.max_results": {
    label: "Max results",
    category: "features",
    group: "CVE",
    order: 12,
    dependsOn: "cve_lookup.enabled",
  },
  "cve_lookup.rate_limit_seconds": {
    label: "Rate limit (s)",
    category: "features",
    group: "CVE",
    order: 13,
    dependsOn: "cve_lookup.enabled",
  },
  "cve_lookup.search_rate_limit_per_minute": {
    label: "Search rate limit/min",
    category: "features",
    group: "CVE",
    order: 14,
    dependsOn: "cve_lookup.enabled",
  },
  "cve_lookup.timeout_seconds": {
    label: "Timeout (s)",
    category: "features",
    group: "CVE",
    order: 15,
    dependsOn: "cve_lookup.enabled",
  },
  // -- memory / Memory --
  "memory.attack_memory_enabled": {
    label: "Attack memory",
    category: "features",
    group: "Memory",
    order: 1,
  },
  "memory.attack_memory_max_context_chars": {
    label: "Attack memory max chars",
    category: "features",
    group: "Memory",
    order: 2,
    advanced: true,
  },
  "memory.cross_mission_learning": {
    label: "Cross-mission learning",
    category: "features",
    group: "Memory",
    order: 3,
  },
  "memory.embedding_model": {
    label: "Embedding model",
    category: "features",
    group: "Memory",
    order: 4,
  },
  "memory.experience_min_samples": {
    label: "Experience min samples",
    category: "features",
    group: "Memory",
    order: 5,
    advanced: true,
  },
  "memory.experience_time_decay_days": {
    label: "Experience decay (days)",
    category: "features",
    group: "Memory",
    order: 6,
    advanced: true,
  },
  "memory.semantic_enabled": {
    label: "Semantic memory",
    description: "Store useful information between agent operations.",
    category: "features",
    group: "Memory",
    order: 7,
    hide: true,
  },
  // -- multi_model / Multi-model --
  "multi_model.consult_aliases": {
    label: "Consult aliases",
    category: "features",
    group: "Multi-model",
    order: 1,
    dependsOn: "multi_model.enabled",
  },
  "multi_model.enabled": {
    label: "Multi-model consult",
    category: "features",
    group: "Multi-model",
    order: 2,
  },
  "multi_model.max_answer_chars": {
    label: "Max answer chars",
    category: "features",
    group: "Multi-model",
    order: 3,
    dependsOn: "multi_model.enabled",
    advanced: true,
  },
  "multi_model.max_consultations": {
    label: "Max consultations",
    category: "features",
    group: "Multi-model",
    order: 4,
    dependsOn: "multi_model.enabled",
    advanced: true,
  },
  "multi_model.max_question_chars": {
    label: "Max question chars",
    category: "features",
    group: "Multi-model",
    order: 5,
    dependsOn: "multi_model.enabled",
    advanced: true,
  },
  // -- plugins / Plugins --
  "plugins.disabled": {
    label: "Disabled plugins",
    category: "features",
    group: "Plugins",
    order: 1,
    dependsOn: "plugins.enabled",
  },
  "plugins.enabled": {
    label: "Enabled plugins",
    category: "features",
    group: "Plugins",
    order: 2,
  },
  "plugins.entry_points": {
    label: "Entry-point discovery",
    category: "features",
    group: "Plugins",
    order: 3,
    dependsOn: "plugins.enabled",
    advanced: true,
  },
  "plugins.search_paths": {
    label: "Plugin search paths",
    category: "features",
    group: "Plugins",
    order: 4,
    dependsOn: "plugins.enabled",
    advanced: true,
  },
  // -- research / Web research --
  "research.allow_local_fetch": {
    label: "Allow local fetch",
    category: "features",
    group: "Research",
    order: 1,
    dependsOn: "research.enabled",
  },
  "research.assistant.automatic": {
    label: "Assistant.automatic",
    category: "features",
    group: "Assistant",
    order: 2,
    dependsOn: "research.assistant.enabled",
    advanced: true,
  },
  "research.assistant.enabled": {
    label: "Assistant.enabled",
    category: "features",
    group: "Assistant",
    order: 3,
    dependsOn: "research.enabled",
  },
  "research.assistant.failure_trigger": {
    label: "Assistant.failure Trigger",
    category: "features",
    group: "Assistant",
    order: 4,
    dependsOn: "research.assistant.enabled",
    advanced: true,
  },
  "research.assistant.max_advisory_chars": {
    label: "Assistant.max ADvisory chars",
    category: "features",
    group: "Assistant",
    order: 5,
    dependsOn: "research.assistant.enabled",
    advanced: true,
  },
  "research.assistant.max_auto_consultations": {
    label: "Assistant.max Auto Consultations",
    category: "features",
    group: "Assistant",
    order: 6,
    dependsOn: "research.assistant.enabled",
    advanced: true,
  },
  "research.assistant.max_model_rounds": {
    label: "Assistant.max Model Rounds",
    category: "features",
    group: "Assistant",
    order: 7,
    dependsOn: "research.assistant.enabled",
    advanced: true,
  },
  "research.assistant.max_tool_calls_per_consultation": {
    label: "Assistant.max Tool Calls Per Consultation",
    category: "features",
    group: "Assistant",
    order: 8,
    dependsOn: "research.assistant.enabled",
    advanced: true,
  },
  "research.assistant.model_alias": {
    label: "Assistant.model Alias",
    category: "features",
    group: "Assistant",
    order: 9,
    dependsOn: "research.assistant.enabled",
    advanced: true,
  },
  "research.assistant.save_advisories": {
    label: "Assistant.save ADvisories",
    category: "features",
    group: "Assistant",
    order: 10,
    dependsOn: "research.assistant.enabled",
    advanced: true,
  },
  "research.assistant.timeout_seconds": {
    label: "Assistant.timeout (s)",
    category: "features",
    group: "Assistant",
    order: 11,
    dependsOn: "research.assistant.enabled",
    advanced: true,
  },
  "research.cache_max_entries": {
    label: "Cache max entries",
    category: "features",
    group: "Research",
    order: 12,
    dependsOn: "research.enabled",
  },
  "research.cache_ttl_seconds": {
    label: "Cache TTL (s)",
    category: "features",
    group: "Research",
    order: 13,
    dependsOn: "research.enabled",
  },
  "research.enabled": {
    label: "Web research",
    category: "features",
    group: "Research",
    order: 14,
  },
  "research.fallback_provider": {
    label: "Fallback provider",
    category: "features",
    group: "Research",
    order: 15,
    dependsOn: "research.enabled",
    options: ["ollama", "serpapi"],
  },
  "research.max_content_chars": {
    label: "Max content chars",
    category: "features",
    group: "Research",
    order: 16,
    dependsOn: "research.enabled",
  },
  "research.max_fetch_depth": {
    label: "Max fetch depth",
    category: "features",
    group: "Research",
    order: 17,
    dependsOn: "research.enabled",
  },
  "research.max_results": {
    label: "Max results",
    category: "features",
    group: "Research",
    order: 18,
    dependsOn: "research.enabled",
  },
  "research.min_source_quality": {
    label: "Min source quality",
    category: "features",
    group: "Research",
    order: 19,
    dependsOn: "research.enabled",
    options: ["low", "medium", "high"],
  },
  "research.ollama.api_key_env": {
    label: "Ollama.api Key Env",
    category: "features",
    group: "Connection",
    order: 20,
    dependsOn: "research.enabled",
    advanced: true,
    secret: true,
  },
  "research.ollama.max_results": {
    label: "Ollama.max Results",
    category: "features",
    group: "Connection",
    order: 21,
    dependsOn: "research.enabled",
    advanced: true,
  },
  "research.ollama.use_web_fetch": {
    label: "Ollama.use Web Fetch",
    category: "features",
    group: "Connection",
    order: 22,
    dependsOn: "research.enabled",
    advanced: true,
  },
  "research.ollama.use_web_search": {
    label: "Ollama.use Web Search",
    category: "features",
    group: "Connection",
    order: 23,
    dependsOn: "research.enabled",
    advanced: true,
  },
  "research.provider": {
    label: "Research provider",
    category: "features",
    group: "Research",
    order: 24,
    dependsOn: "research.enabled",
    options: ["ollama", "serpapi"],
  },
  "research.require_api_key_for_mcp_tools": {
    label: "Require API key for MCP tools",
    category: "features",
    group: "Research",
    order: 25,
    dependsOn: "research.enabled",
  },
  "research.serpapi.api_key_env": {
    label: "Serpapi.api Key Env",
    category: "features",
    group: "Serpapi",
    order: 26,
    dependsOn: "research.enabled",
    advanced: true,
    secret: true,
  },
  "research.serpapi.endpoint": {
    label: "Serpapi.endpoint",
    category: "features",
    group: "Serpapi",
    order: 27,
    dependsOn: "research.enabled",
    advanced: true,
  },
  "research.serpapi.engine": {
    label: "Serpapi.engine",
    category: "features",
    group: "Serpapi",
    order: 28,
    dependsOn: "research.enabled",
    advanced: true,
  },
  "research.serpapi.region": {
    label: "Serpapi.region",
    category: "features",
    group: "Serpapi",
    order: 29,
    dependsOn: "research.enabled",
    advanced: true,
  },
  "research.timeout_seconds": {
    label: "Timeout (s)",
    category: "features",
    group: "Research",
    order: 30,
    dependsOn: "research.enabled",
  },
  // -- skills / Skills --
  "skills.allow_model_lookup": {
    label: "Allow model lookup",
    category: "features",
    group: "Skills",
    order: 1,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.allow_reference_listing": {
    label: "Allow reference listing",
    category: "features",
    group: "Skills",
    order: 2,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.context_skill_weight": {
    label: "Context skill weight",
    category: "features",
    group: "Skills",
    order: 3,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.default_enabled": {
    label: "Default enabled skills",
    category: "features",
    group: "Skills",
    order: 4,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.default_skill_weight": {
    label: "Default skill weight",
    category: "features",
    group: "Skills",
    order: 5,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.diversity_penalty": {
    label: "Diversity penalty",
    category: "features",
    group: "Skills",
    order: 6,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.enabled": {
    label: "Skills",
    category: "features",
    group: "Skills",
    order: 7,
  },
  "skills.exclude_names": {
    label: "Exclude names",
    category: "features",
    group: "Skills",
    order: 8,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.feedback_enabled": {
    label: "Skill feedback",
    category: "features",
    group: "Skills",
    order: 9,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.feedback_min_observations": {
    label: "Feedback min observations",
    category: "features",
    group: "Skills",
    order: 10,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.feedback_skill_weight": {
    label: "Feedback skill weight",
    category: "features",
    group: "Skills",
    order: 11,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.include_metadata": {
    label: "Include metadata",
    category: "features",
    group: "Skills",
    order: 12,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.include_tags": {
    label: "Include tags",
    category: "features",
    group: "Skills",
    order: 13,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.inject_startup_context": {
    label: "Inject startup context",
    category: "features",
    group: "Skills",
    order: 14,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.max_active_skills": {
    label: "Max active skills",
    category: "features",
    group: "Skills",
    order: 15,
    dependsOn: "skills.enabled",
  },
  "skills.max_chars_per_skill": {
    label: "Max chars per skill",
    category: "features",
    group: "Skills",
    order: 16,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.max_total_chars": {
    label: "Max total chars",
    category: "features",
    group: "Skills",
    order: 17,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.maybe_enabled": {
    label: "Maybe enabled",
    category: "features",
    group: "Skills",
    order: 18,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.min_contextual_skills": {
    label: "Min contextual skills",
    category: "features",
    group: "Skills",
    order: 19,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.reselect_max_per_run": {
    label: "Max re-selections per run",
    category: "features",
    group: "Skills",
    order: 20,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.reselect_mid_run": {
    label: "Re-select mid-run",
    category: "features",
    group: "Skills",
    order: 21,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.reselect_min_interval_actions": {
    label: "Min interval between re-selections",
    category: "features",
    group: "Skills",
    order: 22,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.reselect_sticky_defaults": {
    label: "Sticky defaults",
    category: "features",
    group: "Skills",
    order: 23,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.roots": {
    label: "Skill roots",
    category: "features",
    group: "Skills",
    order: 24,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.semantic_matching": {
    label: "Semantic matching",
    category: "features",
    group: "Skills",
    order: 25,
    dependsOn: "skills.enabled",
  },
  "skills.semantic_min_similarity": {
    label: "Semantic min similarity",
    category: "features",
    group: "Skills",
    order: 26,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.semantic_model": {
    label: "Semantic model",
    category: "features",
    group: "Skills",
    order: 27,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.semantic_skill_weight": {
    label: "Semantic skill weight",
    category: "features",
    group: "Skills",
    order: 28,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.swarm_inject": {
    label: "Inject into swarm",
    category: "features",
    group: "Skills",
    order: 29,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  "skills.swarm_phase_hints_only": {
    label: "Swarm phase hints only",
    category: "features",
    group: "Skills",
    order: 30,
    dependsOn: "skills.enabled",
    advanced: true,
  },
  // -- swarm / Swarm --
  "swarm.agents": {
    label: "Agents",
    category: "features",
    group: "Swarm",
    order: 1,
    dependsOn: "swarm.enabled",
    advanced: true,
  },
  "swarm.enabled": {
    label: "Swarm",
    category: "features",
    group: "Swarm",
    order: 2,
  },
  "swarm.exploit_parallel": {
    label: "Parallel exploit agents",
    category: "features",
    group: "Swarm",
    order: 3,
    dependsOn: "swarm.enabled",
    advanced: true,
  },
  "swarm.max_parallel_agents": {
    label: "Max parallel agents",
    category: "features",
    group: "Swarm",
    order: 4,
    dependsOn: "swarm.enabled",
  },
  "swarm.negotiation_rounds": {
    label: "Critic negotiation rounds",
    category: "features",
    group: "Swarm",
    order: 5,
    dependsOn: "swarm.enabled",
    advanced: true,
  },
  "swarm.parallel_enabled": {
    label: "Parallel swarm",
    category: "features",
    group: "Swarm",
    order: 6,
    dependsOn: "swarm.enabled",
  },
  "swarm.per_phase_concurrency": {
    label: "Per-phase concurrency",
    category: "features",
    group: "Swarm",
    order: 7,
    dependsOn: "swarm.enabled",
    advanced: true,
  },
  "swarm.subagent_timeout_seconds": {
    label: "Subagent timeout (s)",
    category: "features",
    group: "Swarm",
    order: 8,
    dependsOn: "swarm.enabled",
    advanced: true,
  },
  // -- threat_intel / Threat intel --
  "threat_intel.cache_dir": {
    label: "Cache dir",
    category: "features",
    group: "Feeds",
    order: 1,
    dependsOn: "threat_intel.enabled",
  },
  "threat_intel.cache_ttl_seconds": {
    label: "Cache TTL (s)",
    category: "features",
    group: "Feeds",
    order: 2,
    dependsOn: "threat_intel.enabled",
  },
  "threat_intel.enabled": {
    label: "Threat intel feed",
    category: "features",
    group: "Feeds",
    order: 3,
  },
  "threat_intel.github_token_env": {
    label: "GitHub token env",
    category: "features",
    group: "Feeds",
    order: 4,
    dependsOn: "threat_intel.enabled",
    secret: true,
  },
  "threat_intel.max_results": {
    label: "Max results",
    category: "features",
    group: "Feeds",
    order: 5,
    dependsOn: "threat_intel.enabled",
  },
  "threat_intel.sources.exploitdb_rss": {
    label: "Sources.exploitdb Rss",
    category: "features",
    group: "Sources",
    order: 6,
    dependsOn: "threat_intel.enabled",
    advanced: true,
  },
  "threat_intel.sources.ghsa": {
    label: "Sources.ghsa",
    category: "features",
    group: "Sources",
    order: 7,
    dependsOn: "threat_intel.enabled",
    advanced: true,
  },
  "threat_intel.sources.kev": {
    label: "Sources.kev",
    category: "features",
    group: "Sources",
    order: 8,
    dependsOn: "threat_intel.enabled",
    advanced: true,
  },
  "threat_intel.sources.osv": {
    label: "Sources.osv",
    category: "features",
    group: "Sources",
    order: 9,
    dependsOn: "threat_intel.enabled",
    advanced: true,
  },
  "threat_intel.timeout_seconds": {
    label: "Timeout (s)",
    category: "features",
    group: "Feeds",
    order: 10,
    dependsOn: "threat_intel.enabled",
  },
  // -- witness / Witness agent --
  "witness.dos_failure_threshold": {
    label: "DoS failure threshold",
    category: "features",
    group: "Witness",
    order: 1,
    dependsOn: "witness.enabled",
    advanced: true,
  },
  "witness.dos_failure_window_seconds": {
    label: "DoS failure window (s)",
    category: "features",
    group: "Witness",
    order: 2,
    dependsOn: "witness.enabled",
    advanced: true,
  },
  "witness.enabled": {
    label: "Witness agent",
    category: "features",
    group: "Witness",
    order: 3,
  },
  "witness.escalate_to_event_broker": {
    label: "Escalate to event broker",
    category: "features",
    group: "Witness",
    order: 4,
    dependsOn: "witness.enabled",
    advanced: true,
  },
  "witness.log_path": {
    label: "Witness log path",
    category: "features",
    group: "Witness",
    order: 5,
    dependsOn: "witness.enabled",
    advanced: true,
  },
  "witness.max_flags_per_signal_per_minute": {
    label: "Max flags per signal/min",
    category: "features",
    group: "Witness",
    order: 6,
    dependsOn: "witness.enabled",
    advanced: true,
  },
  "witness.poll_interval_seconds": {
    label: "Poll interval (s)",
    category: "features",
    group: "Witness",
    order: 7,
    dependsOn: "witness.enabled",
    advanced: true,
  },
  // â”€â”€ Notifications & Integrations â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  // -- caldera / Caldera --
  "caldera.api_key_env": {
    label: "API Key Env",
    category: "integrations",
    group: "Caldera",
    order: 1,
    dependsOn: "caldera.enabled",
    advanced: true,
    secret: true,
  },
  "caldera.enabled": {
    label: "Enabled",
    category: "integrations",
    group: "Caldera",
    order: 2,
  },
  "caldera.url": {
    label: "URL",
    category: "integrations",
    group: "Caldera",
    order: 3,
    dependsOn: "caldera.enabled",
    advanced: true,
  },
  // -- mitre / MITRE ATT&CK --
  "mitre.enabled": {
    label: "MITRE ATT&CK export",
    category: "integrations",
    group: "MITRE",
    order: 1,
  },
  "mitre.include_skill_tags": {
    label: "Include skill tags",
    category: "integrations",
    group: "MITRE",
    order: 2,
    dependsOn: "mitre.enabled",
    advanced: true,
  },
  "mitre.navigator_output_dir": {
    label: "Navigator output dir",
    category: "integrations",
    group: "MITRE",
    order: 3,
    dependsOn: "mitre.enabled",
    advanced: true,
  },
  "mitre.technique_map": {
    label: "Technique map",
    category: "integrations",
    group: "MITRE",
    order: 4,
    dependsOn: "mitre.enabled",
    advanced: true,
  },
  // -- ticketing / Remediation tickets --
  "ticketing.backoff_seconds": {
    label: "Backoff (s)",
    category: "integrations",
    group: "Ticketing",
    order: 1,
    dependsOn: "ticketing.enabled",
    advanced: true,
  },
  "ticketing.base_url": {
    label: "Ticket base URL",
    category: "integrations",
    group: "Ticketing",
    order: 2,
    dependsOn: "ticketing.enabled",
    advanced: true,
  },
  "ticketing.enabled": {
    label: "Remediation tickets",
    category: "integrations",
    group: "Ticketing",
    order: 3,
  },
  "ticketing.max_retries": {
    label: "Max retries",
    category: "integrations",
    group: "Ticketing",
    order: 4,
    dependsOn: "ticketing.enabled",
    advanced: true,
  },
  "ticketing.project_key": {
    label: "Project key",
    category: "integrations",
    group: "Ticketing",
    order: 5,
    dependsOn: "ticketing.enabled",
    advanced: true,
  },
  "ticketing.provider": {
    label: "Ticket provider",
    category: "integrations",
    group: "Ticketing",
    order: 6,
    dependsOn: "ticketing.enabled",
    advanced: true,
  },
  "ticketing.token_env": {
    label: "Ticket token env",
    category: "integrations",
    group: "Ticketing",
    order: 7,
    dependsOn: "ticketing.enabled",
    advanced: true,
    secret: true,
  },
  // -- webhook_notify / Webhook notifications --
  "webhook_notify.backoff_seconds": {
    label: "Backoff (s)",
    category: "integrations",
    group: "Notifications",
    order: 1,
    dependsOn: "webhook_notify.enabled",
    advanced: true,
  },
  "webhook_notify.enabled": {
    label: "Webhook notifications",
    category: "integrations",
    group: "Notifications",
    order: 2,
  },
  "webhook_notify.events": {
    label: "Events",
    category: "integrations",
    group: "Notifications",
    order: 3,
    dependsOn: "webhook_notify.enabled",
    advanced: true,
  },
  "webhook_notify.max_payload_chars": {
    label: "Max payload chars",
    category: "integrations",
    group: "Notifications",
    order: 4,
    dependsOn: "webhook_notify.enabled",
    advanced: true,
  },
  "webhook_notify.max_retries": {
    label: "Max retries",
    category: "integrations",
    group: "Notifications",
    order: 5,
    dependsOn: "webhook_notify.enabled",
    advanced: true,
  },
  "webhook_notify.timeout_seconds": {
    label: "Timeout (s)",
    category: "integrations",
    group: "Notifications",
    order: 6,
    dependsOn: "webhook_notify.enabled",
    advanced: true,
  },
  "webhook_notify.url": {
    label: "Webhook URL",
    category: "integrations",
    group: "Notifications",
    order: 7,
    dependsOn: "webhook_notify.enabled",
    secret: true,
  },
  // â”€â”€ Advanced â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  // -- agent / Agent --
  "agent.capability_discovery_enabled": {
    label: "Capability discovery",
    category: "advanced",
    group: "Capabilities",
    order: 1,
    advanced: true,
  },
  "agent.decision_log_enabled": {
    label: "Decision log",
    category: "advanced",
    group: "Capabilities",
    order: 2,
    advanced: true,
  },
  "agent.generated_code_repair_attempts": {
    label: "Code repair attempts",
    category: "advanced",
    group: "Capabilities",
    order: 3,
    advanced: true,
  },
  "agent.max_actions": {
    label: "Maximum agent actions",
    description: "Maximum number of actions the agent can take during one run.",
    category: "advanced",
    group: "Capabilities",
    order: 4,
  },
  "agent.max_retries_per_task": {
    label: "Max retries per task",
    category: "advanced",
    group: "Capabilities",
    order: 5,
  },
  "agent.planner_hints_enabled": {
    label: "Planner hints",
    category: "advanced",
    group: "Capabilities",
    order: 6,
    advanced: true,
  },
  "agent.reflection_enabled": {
    label: "Reflection",
    category: "advanced",
    group: "Capabilities",
    order: 7,
    advanced: true,
  },
  "agent.state_tools_enabled": {
    label: "State tools",
    category: "advanced",
    group: "Capabilities",
    order: 8,
    advanced: true,
  },
  "agent.task_graph_enabled": {
    label: "Task graph",
    category: "advanced",
    group: "Capabilities",
    order: 9,
    advanced: true,
  },
  // -- api / WebUI --
  "api.allowed_origins": {
    label: "Allowed origins",
    description: "Extra loopback origins permitted for CORS/WebSocket.",
    category: "advanced",
    group: "WebUI",
    order: 1,
    dependsOn: "api.enabled",
    advanced: true,
  },
  "api.enabled": {
    label: "WebUI API",
    category: "advanced",
    group: "WebUI",
    order: 2,
  },
  "api.event_buffer_size": {
    label: "Event buffer size",
    category: "advanced",
    group: "WebUI",
    order: 3,
    dependsOn: "api.enabled",
    advanced: true,
  },
  "api.graph_route": {
    label: "Attack graph route",
    category: "advanced",
    group: "WebUI",
    order: 4,
    dependsOn: "api.enabled",
    advanced: true,
  },
  "api.host": {
    label: "WebUI host",
    category: "advanced",
    group: "WebUI",
    order: 5,
    dependsOn: "api.enabled",
    advanced: true,
  },
  "api.max_concurrent_runs": {
    label: "Simultaneous assessments",
    description: "How many assessments BreachPilot can run at the same time.",
    category: "general",
    group: "Assessments",
    order: 10,
  },
  "api.multi_operator": {
    label: "Multi-operator accounts",
    description: "Enable user accounts for pair-testing collaboration.",
    category: "advanced",
    group: "WebUI",
    order: 7,
    dependsOn: "api.enabled",
  },
  "api.port": {
    label: "WebUI port",
    category: "advanced",
    group: "WebUI",
    order: 8,
    dependsOn: "api.enabled",
  },
  "api.serve_webui": {
    label: "Serve WebUI",
    category: "advanced",
    group: "WebUI",
    order: 9,
    dependsOn: "api.enabled",
  },
  "api.shutdown_timeout_seconds": {
    label: "Shutdown timeout (s)",
    category: "advanced",
    group: "WebUI",
    order: 10,
    dependsOn: "api.enabled",
    advanced: true,
  },
  "api.token_file": {
    label: "Token file",
    category: "advanced",
    group: "WebUI",
    order: 11,
    dependsOn: "api.enabled",
    hide: true,
  },
  // -- autonomous / Autonomous orchestrator --
  "autonomous.adaptive_replan": {
    label: "Adaptive replan",
    category: "advanced",
    group: "Campaign",
    order: 1,
  },
  "autonomous.checkpoint_every": {
    label: "Checkpoint every N targets",
    category: "advanced",
    group: "Campaign",
    order: 2,
  },
  "autonomous.dedup_targets": {
    label: "Dedup Targets",
    category: "advanced",
    group: "Campaign",
    order: 3,
    advanced: true,
  },
  "autonomous.hard_target_max_rounds": {
    label: "Hard Target Max Rounds",
    category: "advanced",
    group: "Campaign",
    order: 4,
    advanced: true,
  },
  "autonomous.max_cycles": {
    label: "Max cycles",
    category: "advanced",
    group: "Campaign",
    order: 5,
  },
  "autonomous.max_pivot_depth": {
    label: "Max pivot depth",
    category: "advanced",
    group: "Campaign",
    order: 6,
  },
  "autonomous.persistence_phase": {
    label: "Persistence phase",
    category: "advanced",
    group: "Campaign",
    order: 7,
  },
  "autonomous.skip_non_routable": {
    label: "Skip Non Routable",
    category: "advanced",
    group: "Campaign",
    order: 8,
    advanced: true,
  },
  // -- benchmark / Benchmark --
  "benchmark.baseline_path": {
    label: "Baseline Path",
    category: "advanced",
    group: "Benchmark",
    order: 1,
    dependsOn: "benchmark.enabled",
    advanced: true,
  },
  "benchmark.enabled": {
    label: "Enabled",
    category: "advanced",
    group: "Benchmark",
    order: 2,
  },
  "benchmark.output_dir": {
    label: "Output Dir",
    category: "advanced",
    group: "Benchmark",
    order: 3,
    dependsOn: "benchmark.enabled",
    advanced: true,
  },
  "benchmark.regression.cost_tolerance": {
    label: "Regression.cost Tolerance",
    category: "advanced",
    group: "Regression",
    order: 4,
    dependsOn: "benchmark.regression.enabled",
    advanced: true,
  },
  "benchmark.regression.enabled": {
    label: "Regression.enabled",
    category: "advanced",
    group: "Regression",
    order: 5,
    dependsOn: "benchmark.enabled",
  },
  "benchmark.regression.false_positive_tolerance": {
    label: "Regression.false Positive Tolerance",
    category: "advanced",
    group: "Regression",
    order: 6,
    dependsOn: "benchmark.regression.enabled",
    advanced: true,
  },
  "benchmark.regression.median_time_tolerance": {
    label: "Regression.median Time Tolerance",
    category: "advanced",
    group: "Regression",
    order: 7,
    dependsOn: "benchmark.regression.enabled",
    advanced: true,
  },
  "benchmark.regression.success_rate_tolerance": {
    label: "Regression.success Rate Tolerance",
    category: "advanced",
    group: "Regression",
    order: 8,
    dependsOn: "benchmark.regression.enabled",
    advanced: true,
  },
  "benchmark.regression.tool_actions_tolerance": {
    label: "Regression.tool Actions Tolerance",
    category: "advanced",
    group: "Regression",
    order: 9,
    dependsOn: "benchmark.regression.enabled",
    advanced: true,
  },
  "benchmark.sandbox_required": {
    label: "Sandbox Required",
    category: "advanced",
    group: "Benchmark",
    order: 10,
    dependsOn: "benchmark.enabled",
    advanced: true,
  },
  "benchmark.telemetry.cost": {
    label: "Telemetry.cost",
    category: "advanced",
    group: "Telemetry",
    order: 11,
    dependsOn: "benchmark.enabled",
    advanced: true,
  },
  "benchmark.telemetry.events": {
    label: "Telemetry.events",
    category: "advanced",
    group: "Telemetry",
    order: 12,
    dependsOn: "benchmark.enabled",
    advanced: true,
  },
  "benchmark.telemetry.token_usage": {
    label: "Telemetry.token Usage",
    category: "advanced",
    group: "Telemetry",
    order: 13,
    dependsOn: "benchmark.enabled",
    advanced: true,
  },
  "benchmark.timeout_seconds": {
    label: "Timeout Seconds (s)",
    category: "advanced",
    group: "Benchmark",
    order: 14,
    dependsOn: "benchmark.enabled",
    advanced: true,
  },
  "benchmark.trials": {
    label: "Trials",
    category: "advanced",
    group: "Benchmark",
    order: 15,
    dependsOn: "benchmark.enabled",
    advanced: true,
  },
  // -- engine_mcp / Engine MCP --
  "engine_mcp.enabled": {
    label: "Engine MCP server",
    category: "advanced",
    group: "Engine MCP",
    order: 1,
  },
  "engine_mcp.host": {
    label: "Engine MCP host",
    category: "advanced",
    group: "Engine MCP",
    order: 2,
    dependsOn: "engine_mcp.enabled",
    advanced: true,
  },
  "engine_mcp.port": {
    label: "Engine MCP port",
    category: "advanced",
    group: "Engine MCP",
    order: 3,
    dependsOn: "engine_mcp.enabled",
    advanced: true,
  },
  // -- eval / Eval harness --
  "eval.baseline_path": {
    label: "Baseline Path",
    category: "advanced",
    group: "Evaluation",
    order: 1,
    dependsOn: "eval.enabled",
    advanced: true,
  },
  "eval.enabled": {
    label: "Eval harness",
    category: "advanced",
    group: "Evaluation",
    order: 2,
  },
  "eval.max_rounds": {
    label: "Eval max rounds",
    category: "advanced",
    group: "Evaluation",
    order: 3,
    dependsOn: "eval.enabled",
  },
  "eval.output_dir": {
    label: "Eval output dir",
    category: "advanced",
    group: "Evaluation",
    order: 4,
    dependsOn: "eval.enabled",
  },
  "eval.regression_tolerance": {
    label: "Regression Tolerance",
    category: "advanced",
    group: "Evaluation",
    order: 5,
    dependsOn: "eval.enabled",
    advanced: true,
  },
  "eval.write_html": {
    label: "Write HTML",
    category: "advanced",
    group: "Evaluation",
    order: 6,
    dependsOn: "eval.enabled",
  },
  "eval.write_markdown": {
    label: "Write markdown",
    category: "advanced",
    group: "Evaluation",
    order: 7,
    dependsOn: "eval.enabled",
  },
  // -- ics / ICS --
  "ics.allow_write": {
    label: "Allow Write",
    category: "advanced",
    group: "ICS",
    order: 1,
  },
  "ics.destructive_ics": {
    label: "Destructive ICS",
    category: "advanced",
    group: "ICS",
    order: 2,
    advanced: true,
  },
  // -- killchain / Killchain --
  "killchain.enabled": {
    label: "Enabled",
    category: "advanced",
    group: "Killchain",
    order: 1,
  },
  "killchain.goal_state": {
    label: "Goal State",
    category: "advanced",
    group: "Killchain",
    order: 2,
    dependsOn: "killchain.enabled",
    advanced: true,
  },
  "killchain.graph_db": {
    label: "Graph Db",
    category: "advanced",
    group: "Killchain",
    order: 3,
    dependsOn: "killchain.enabled",
    advanced: true,
  },
  "killchain.require_verification": {
    label: "Require Verification",
    category: "advanced",
    group: "Killchain",
    order: 4,
    dependsOn: "killchain.enabled",
    advanced: true,
  },
  // -- mcp / MCP --
  "mcp.default_transport": {
    label: "MCP transport",
    description: "Transport used to connect to the exploit MCP server.",
    category: "advanced",
    group: "MCP",
    order: 1,
    options: ["stdio", "http"],
  },
  // -- operator_connection / Operator connection --
  "operator_connection.auto_start_listener": {
    label: "Auto Start Listener",
    category: "advanced",
    group: "Operator link",
    order: 1,
    dependsOn: "operator_connection.enabled",
    advanced: true,
  },
  "operator_connection.beacon_interval_seconds": {
    label: "Beacon Interval Seconds (s)",
    category: "advanced",
    group: "Operator link",
    order: 2,
    dependsOn: "operator_connection.enabled",
    advanced: true,
  },
  "operator_connection.default_callback_port": {
    label: "Default Callback Port",
    category: "advanced",
    group: "Operator link",
    order: 3,
    dependsOn: "operator_connection.enabled",
    advanced: true,
  },
  "operator_connection.default_listener_type": {
    label: "Default Listener Type",
    category: "advanced",
    group: "Operator link",
    order: 4,
    dependsOn: "operator_connection.enabled",
    advanced: true,
  },
  "operator_connection.enabled": {
    label: "Enabled",
    category: "advanced",
    group: "Operator link",
    order: 5,
  },
  "operator_connection.health_check_interval_seconds": {
    label: "Health Check Interval Seconds (s)",
    category: "advanced",
    group: "Operator link",
    order: 6,
    dependsOn: "operator_connection.enabled",
    advanced: true,
  },
  "operator_connection.workspace_dir": {
    label: "Workspace Dir",
    category: "advanced",
    group: "Operator link",
    order: 7,
    dependsOn: "operator_connection.enabled",
    advanced: true,
  },
  // -- orchestrator / Orchestrator --
  "orchestrator.semantic_memory": {
    label: "Orchestrator semantic memory",
    category: "advanced",
    group: "Orchestration",
    order: 1,
  },
  // -- outcome_judgment / Outcome judgment --
  "outcome_judgment.confirmation_threshold": {
    label: "Confirmation threshold",
    category: "advanced",
    group: "Judgment",
    order: 1,
  },
  "outcome_judgment.flow_a": {
    label: "Flow A outcome judging",
    category: "advanced",
    group: "Judgment",
    order: 2,
  },
  "outcome_judgment.max_inconclusive_attempts": {
    label: "Max inconclusive attempts",
    category: "advanced",
    group: "Judgment",
    order: 3,
  },
  "outcome_judgment.min_evidence_references": {
    label: "Min evidence references",
    category: "advanced",
    group: "Judgment",
    order: 4,
  },
  "outcome_judgment.peer_review": {
    label: "Peer review judging",
    category: "advanced",
    group: "Judgment",
    order: 5,
  },
  "outcome_judgment.refutation_threshold": {
    label: "Refutation threshold",
    category: "advanced",
    group: "Judgment",
    order: 6,
  },
  // -- poc_verification / PoC verification --
  "poc_verification.compile_timeout_seconds": {
    label: "Compile timeout (s)",
    category: "advanced",
    group: "Verification",
    order: 1,
    dependsOn: "poc_verification.enabled",
  },
  "poc_verification.docker_image": {
    label: "Docker image",
    category: "advanced",
    group: "Verification",
    order: 2,
    dependsOn: "poc_verification.enabled",
  },
  "poc_verification.docker_memory": {
    label: "Docker memory",
    category: "advanced",
    group: "Verification",
    order: 3,
    dependsOn: "poc_verification.enabled",
  },
  "poc_verification.docker_network": {
    label: "Docker network",
    category: "advanced",
    group: "Verification",
    order: 4,
    dependsOn: "poc_verification.enabled",
  },
  "poc_verification.docker_read_only": {
    label: "Docker read-only",
    category: "advanced",
    group: "Verification",
    order: 5,
    dependsOn: "poc_verification.enabled",
  },
  "poc_verification.enabled": {
    label: "PoC verification",
    category: "advanced",
    group: "Verification",
    order: 6,
  },
  "poc_verification.max_retries": {
    label: "Max retries",
    category: "advanced",
    group: "Verification",
    order: 7,
    dependsOn: "poc_verification.enabled",
  },
  // -- replay_simulator / Replay simulator --
  "replay_simulator.counterfactual": {
    label: "Counterfactual",
    category: "advanced",
    group: "Simulation",
    order: 1,
    dependsOn: "replay_simulator.enabled",
    advanced: true,
  },
  "replay_simulator.enabled": {
    label: "Replay simulator",
    category: "advanced",
    group: "Simulation",
    order: 2,
  },
  // -- sandbox / Sandbox --
  "sandbox.backend": {
    label: "Backend",
    category: "advanced",
    group: "Sandbox",
    order: 1,
    dependsOn: "sandbox.enabled",
    advanced: true,
  },
  "sandbox.cleanup.remove_on_exit": {
    label: "Cleanup.remove On Exit",
    category: "advanced",
    group: "Cleanup",
    order: 2,
    dependsOn: "sandbox.enabled",
    advanced: true,
  },
  "sandbox.cleanup.remove_stale_on_startup": {
    label: "Cleanup.remove Stale On Startup",
    category: "advanced",
    group: "Cleanup",
    order: 3,
    dependsOn: "sandbox.enabled",
    advanced: true,
  },
  "sandbox.enabled": {
    label: "Enabled",
    category: "advanced",
    group: "Sandbox",
    order: 4,
  },
  "sandbox.env_passthrough": {
    label: "Env Passthrough",
    category: "advanced",
    group: "Sandbox",
    order: 5,
    dependsOn: "sandbox.enabled",
    advanced: true,
  },
  "sandbox.image": {
    label: "Image",
    category: "advanced",
    group: "Sandbox",
    order: 6,
    dependsOn: "sandbox.enabled",
    advanced: true,
  },
  "sandbox.multi_net_raw": {
    label: "Multi Net Raw",
    category: "advanced",
    group: "Sandbox",
    order: 7,
    dependsOn: "sandbox.enabled",
    advanced: true,
  },
  "sandbox.network.allow_dns": {
    label: "Network.allow DNS",
    category: "advanced",
    group: "Network",
    order: 8,
    dependsOn: "sandbox.enabled",
    advanced: true,
  },
  "sandbox.network.allow_gateway": {
    label: "Network.allow Gateway",
    category: "advanced",
    group: "Network",
    order: 9,
    dependsOn: "sandbox.enabled",
    advanced: true,
  },
  "sandbox.network.allow_research_hosts": {
    label: "Network.allow Research Hosts",
    category: "advanced",
    group: "Network",
    order: 10,
    dependsOn: "sandbox.enabled",
    advanced: true,
  },
  "sandbox.network.enforce": {
    label: "Network.enforce",
    category: "advanced",
    group: "Network",
    order: 11,
    dependsOn: "sandbox.enabled",
    advanced: true,
  },
  "sandbox.network.extra_allow_cidrs": {
    label: "Network.extra Allow CIDRs",
    category: "advanced",
    group: "Network",
    order: 12,
    dependsOn: "sandbox.enabled",
    advanced: true,
  },
  "sandbox.network.fail_closed": {
    label: "Network.fail Closed",
    category: "advanced",
    group: "Network",
    order: 13,
    dependsOn: "sandbox.enabled",
    advanced: true,
  },
  "sandbox.network.map_host_loopback": {
    label: "Network.map Host Loopback",
    category: "advanced",
    group: "Network",
    order: 14,
    dependsOn: "sandbox.enabled",
    advanced: true,
  },
  "sandbox.read_only_rootfs": {
    label: "Read Only Rootfs",
    category: "advanced",
    group: "Sandbox",
    order: 15,
    dependsOn: "sandbox.enabled",
    advanced: true,
  },
  "sandbox.resources.cpus": {
    label: "Resources.cpus",
    category: "advanced",
    group: "Resources",
    order: 16,
    dependsOn: "sandbox.enabled",
    advanced: true,
  },
  "sandbox.resources.memory_mb": {
    label: "Resources.memory Mb",
    category: "advanced",
    group: "Resources",
    order: 17,
    dependsOn: "sandbox.enabled",
    advanced: true,
  },
  "sandbox.resources.output_max_bytes": {
    label: "Resources.output Max Bytes",
    category: "advanced",
    group: "Resources",
    order: 18,
    dependsOn: "sandbox.enabled",
    advanced: true,
  },
  "sandbox.resources.pids": {
    label: "Resources.pids",
    category: "advanced",
    group: "Resources",
    order: 19,
    dependsOn: "sandbox.enabled",
    advanced: true,
  },
  "sandbox.resources.timeout_seconds": {
    label: "Resources.timeout (s)",
    category: "advanced",
    group: "Resources",
    order: 20,
    dependsOn: "sandbox.enabled",
    advanced: true,
  },
  "sandbox.user": {
    label: "User",
    category: "advanced",
    group: "Sandbox",
    order: 21,
    dependsOn: "sandbox.enabled",
    advanced: true,
  },
  // -- snapshots / Snapshots --
  "snapshots.auto_before_destructive": {
    label: "Auto Before Destructive",
    category: "advanced",
    group: "Snapshots",
    order: 1,
    dependsOn: "snapshots.enabled",
    advanced: true,
  },
  "snapshots.enabled": {
    label: "Enabled",
    category: "advanced",
    group: "Snapshots",
    order: 2,
  },
  "snapshots.max_snapshots_per_target": {
    label: "Max Snapshots Per Target",
    category: "advanced",
    group: "Snapshots",
    order: 3,
    dependsOn: "snapshots.enabled",
    advanced: true,
  },
  "snapshots.provider": {
    label: "Provider",
    category: "advanced",
    group: "Snapshots",
    order: 4,
    dependsOn: "snapshots.enabled",
    advanced: true,
  },
  "snapshots.providers.docker.compose_file": {
    label: "Providers.docker.compose File",
    category: "advanced",
    group: "Providers",
    order: 5,
    dependsOn: "snapshots.enabled",
    advanced: true,
  },
  "snapshots.providers.hyperv.powershell_command": {
    label: "Providers.hyperv.powershell Command",
    category: "advanced",
    group: "Providers",
    order: 6,
    dependsOn: "snapshots.enabled",
    advanced: true,
  },
  "snapshots.providers.libvirt.virsh_path": {
    label: "Providers.libvirt.virsh Path",
    category: "advanced",
    group: "Providers",
    order: 7,
    dependsOn: "snapshots.enabled",
    advanced: true,
  },
  "snapshots.providers.proxmox.host": {
    label: "Providers.proxmox.host",
    category: "advanced",
    group: "Providers",
    order: 8,
    dependsOn: "snapshots.enabled",
    advanced: true,
  },
  "snapshots.providers.proxmox.node": {
    label: "Providers.proxmox.node",
    category: "advanced",
    group: "Providers",
    order: 9,
    dependsOn: "snapshots.enabled",
    advanced: true,
  },
  "snapshots.providers.vmware.vmrun_path": {
    label: "Providers.vmware.vmrun Path",
    category: "advanced",
    group: "Providers",
    order: 10,
    dependsOn: "snapshots.enabled",
    advanced: true,
  },
  // -- stealth / Stealth (legacy) --
  "stealth.dns_over_https": {
    label: "DNS over HTTPS",
    category: "advanced",
    group: "Legacy",
    order: 1,
  },
  "stealth.doh_provider": {
    label: "DoH provider",
    category: "advanced",
    group: "Legacy",
    order: 2,
    options: ["cloudflare", "google"],
  },
  "stealth.rotate_ua": {
    label: "Rotate User-Agent",
    category: "advanced",
    group: "Legacy",
    order: 3,
  },
};

export function getSettingMeta(section: string, field: string): SettingMeta | undefined {
  return SETTING_META[`${section}.${field}`];
}

export function getCategoryForSection(section: string): SettingCategory {
  return SECTION_CATEGORY[section] ?? "advanced";
}

/** Category a field renders in: its explicit meta category, else "advanced"
 *  (unknown properties surface under Advanced Configuration). */
export function fieldCategory(section: string, field: string): SettingCategory {
  return getSettingMeta(section, field)?.category ?? "advanced";
}

export function isKnownSetting(section: string, field: string): boolean {
  return !!getSettingMeta(section, field);
}

export function sectionLabel(section: string): string {
  return SECTION_LABELS[section] ?? section;
}
