// Presentation metadata for the settings page. The backend config schema is
// the source of truth for what exists; this file only decorates it with
// friendly labels, descriptions, categories, and control hints. Unknown
// properties (no entry here) still render automatically under Advanced with
// their raw config key.

export type SettingCategory = "general" | "ai" | "features" | "advanced";

export interface SettingMeta {
  label: string;
  description?: string;
  category: SettingCategory;
  /** Hidden under "Show advanced settings" within its category. */
  advanced?: boolean;
  /** Enumerated values → rendered as a select. May be a function of the draft
   *  for dynamic options (e.g. default model = registry keys). */
  options?: string[] | ((draft: Record<string, unknown>) => string[]);
  placeholder?: string;
  /** Rendered as a password input. */
  secret?: boolean;
  /** Never rendered (e.g. token_file). */
  hide?: boolean;
}

export const CATEGORY_LABELS: Record<SettingCategory, string> = {
  general: "General",
  ai: "AI & Providers",
  features: "Features",
  advanced: "Advanced",
};

export const CATEGORY_DESCRIPTIONS: Record<SettingCategory, string> = {
  general: "Common application configuration.",
  ai: "Provider, models, and API keys.",
  features: "Optional subsystems you can turn on or off.",
  advanced: "Technical configuration, diagnostics, and system information.",
};

/** Default category for a schema section. Sections not listed here (and
 *  fields without explicit meta) fall through to "advanced". */
export const SECTION_CATEGORY: Record<string, SettingCategory> = {
  ollama: "ai",
  models: "ai",
  chatgpt: "ai",
  mcp: "general",
  engine_mcp: "general",
  nmap: "general",
  api: "general",
  agent: "general",
  reasoning: "general",
  memory: "features",
  plugins: "features",
  skills: "features",
  swarm: "features",
  multi_model: "features",
  adaptive_exploits: "features",
  long_session: "features",
  webhook_notify: "features",
  mitre: "features",
  ticketing: "features",
  witness: "features",
};

export const SECTION_LABELS: Record<string, string> = {
  ollama: "Ollama",
  models: "Models",
  chatgpt: "ChatGPT",
  mcp: "MCP",
  engine_mcp: "Engine MCP",
  nmap: "Nmap",
  exploit: "Exploit engine",
  stealth: "Stealth (legacy)",
  cve_lookup: "CVE lookup",
  threat_intel: "Threat intel",
  research: "Web research",
  swarm: "Swarm",
  witness: "Witness agent",
  autonomous: "Autonomous orchestrator",
  orchestrator: "Orchestrator",
  recon: "Recon",
  opsec: "OPSEC",
  eval: "Eval harness",
  long_session: "Long session",
  reasoning: "Reasoning",
  memory: "Memory",
  outcome_judgment: "Outcome judgment",
  poc_verification: "PoC verification",
  replay_simulator: "Replay simulator",
  adaptive_exploits: "Adaptive exploits",
  multi_model: "Multi-model",
  skills: "Skills",
  plugins: "Plugins",
  webhook_notify: "Webhook notifications",
  mitre: "MITRE ATT&CK",
  ticketing: "Remediation tickets",
  api: "WebUI",
  agent: "Agent",
};

const registryKeys = (draft: Record<string, unknown>): string[] => {
  const registry = (draft.models as Record<string, unknown> | undefined)?.registry;
  if (registry && typeof registry === "object") return Object.keys(registry as Record<string, unknown>);
  return [];
};

export const SETTING_META: Record<string, SettingMeta> = {
  // ── General ────────────────────────────────────────────────────────────────
  "mcp.default_transport": {
    label: "MCP transport",
    description: "Transport used to connect to the exploit MCP server.",
    category: "general",
    options: ["stdio", "http"],
  },
  "mcp.http_host": { label: "MCP HTTP host", category: "general", advanced: true },
  "mcp.http_port": { label: "MCP HTTP port", category: "general", advanced: true },
  "engine_mcp.enabled": { label: "Engine MCP server", category: "general", advanced: true },
  "engine_mcp.host": { label: "Engine MCP host", category: "general", advanced: true },
  "engine_mcp.port": { label: "Engine MCP port", category: "general", advanced: true },
  "nmap.path": { label: "Nmap path", description: "Path to the nmap binary.", category: "general" },
  "nmap.sudo": {
    label: "Run nmap with sudo",
    description: "Use sudo -n for root-only scans (Linux).",
    category: "general",
  },
  "nmap.priv_fallback": {
    label: "Auto-downgrade privileged flags",
    description: "Drop -O / -sS instead of failing when unprivileged.",
    category: "general",
    advanced: true,
  },
  "api.port": { label: "WebUI port", category: "general" },
  "api.host": { label: "WebUI host", category: "general", advanced: true },
  "api.enabled": { label: "WebUI API", category: "general", advanced: true },
  "api.token_file": { label: "Token file", category: "general", hide: true },
  "api.allowed_origins": {
    label: "Allowed origins",
    description: "Extra loopback origins permitted for CORS/WebSocket.",
    category: "general",
    advanced: true,
  },
  "api.event_buffer_size": { label: "Event buffer size", category: "general", advanced: true },
  "api.shutdown_timeout_seconds": { label: "Shutdown timeout (s)", category: "general", advanced: true },
  "api.serve_webui": { label: "Serve WebUI", category: "general" },
  "api.max_concurrent_runs": {
    label: "Max concurrent runs",
    description: "How many assessments can run at once.",
    category: "general",
  },
  "api.multi_operator": {
    label: "Multi-operator accounts",
    description: "Enable user accounts for pair-testing collaboration.",
    category: "general",
  },
  "api.graph_route": { label: "Attack graph route", category: "general", advanced: true },
  "agent.max_actions": {
    label: "Maximum agent actions",
    description: "Maximum number of actions the agent can take during one run.",
    category: "general",
  },
  "agent.max_retries_per_task": { label: "Max retries per task", category: "general" },
  "agent.task_graph_enabled": { label: "Task graph", category: "general", advanced: true },
  "agent.capability_discovery_enabled": { label: "Capability discovery", category: "general", advanced: true },
  "agent.state_tools_enabled": { label: "State tools", category: "general", advanced: true },
  "agent.planner_hints_enabled": { label: "Planner hints", category: "general", advanced: true },
  "agent.decision_log_enabled": { label: "Decision log", category: "general", advanced: true },
  "agent.reflection_enabled": { label: "Reflection", category: "general", advanced: true },
  "agent.generated_code_repair_attempts": { label: "Code repair attempts", category: "general", advanced: true },
  "reasoning.chain_of_thought": { label: "Chain of thought", category: "general" },
  "reasoning.observer_mode": { label: "Observer mode", category: "general", options: ["heuristic", "llm", "hybrid"] },
  "reasoning.critic_enabled": { label: "Critic", category: "general" },
  "reasoning.reflection_every_n_actions": { label: "Reflect every N actions", category: "general" },
  "reasoning.ultrathink": { label: "Ultrathink", category: "general" },
  "reasoning.ultrathink_reflection_interval": { label: "Ultrathink reflection interval", category: "general", advanced: true },
  "reasoning.llm_reflection": { label: "LLM reflection", category: "general", advanced: true },
  "reasoning.peer_consult_on_failure_threshold": { label: "Peer consult threshold", category: "general", advanced: true },

  // ── AI & Providers ────────────────────────────────────────────────────────
  "ollama.host": { label: "Ollama host", description: "Base URL for the Ollama API.", category: "ai" },
  "ollama.model": { label: "Ollama model", category: "ai" },
  "ollama.api_key_env": { label: "Ollama API key env var", category: "ai", advanced: true },
  "ollama.embed_host": { label: "Embeddings host", category: "ai", advanced: true },
  "models.provider": { label: "Provider", category: "ai", options: ["ollama", "chatgpt"] },
  "models.default_alias": {
    label: "Default model",
    description: "Model alias used when no model is chosen for a run.",
    category: "ai",
    options: registryKeys,
    // Rendered as the "Default model" select in the AI provider card instead.
    hide: true,
  },
  "models.registry": { label: "Model registry", category: "ai", advanced: true },
  "models.roles": { label: "Model roles", category: "ai", advanced: true },
  "models.info": { label: "Model info", category: "ai", advanced: true },
  "chatgpt.enabled": { label: "ChatGPT provider", category: "ai" },
  "chatgpt.default_model": { label: "ChatGPT default model", category: "ai", hide: true },
  "chatgpt.base_url": { label: "ChatGPT base URL", category: "ai", advanced: true },
  "chatgpt.auto_start": { label: "Auto-start proxy", category: "ai" },
  "chatgpt.host": { label: "ChatGPT host", category: "ai", advanced: true },
  "chatgpt.port": { label: "ChatGPT port", category: "ai", advanced: true },
  "chatgpt.models": { label: "ChatGPT models", category: "ai", advanced: true },
  "chatgpt.context_window": { label: "Context window", category: "ai", advanced: true },
  "chatgpt.request_timeout_seconds": { label: "Request timeout (s)", category: "ai", advanced: true },
  "chatgpt.login_timeout_seconds": { label: "Login timeout (s)", category: "ai", advanced: true },
  "chatgpt.start_timeout_seconds": { label: "Start timeout (s)", category: "ai", advanced: true },
  "chatgpt.discover_cache_seconds": { label: "Model discovery cache (s)", category: "ai", advanced: true },
  "chatgpt.local_repo": { label: "OAuth repo", category: "ai", advanced: true },
  "chatgpt.runtime": { label: "Runtime", category: "ai", advanced: true },
  "chatgpt.oauth_file": { label: "OAuth file", category: "ai", advanced: true },

  // ── Features ──────────────────────────────────────────────────────────────
  "memory.semantic_enabled": {
    label: "Semantic memory",
    description: "Store useful information between agent operations.",
    category: "features",
    // Rendered as the Memory toggle in the Features highlights row instead.
    hide: true,
  },
  "memory.cross_mission_learning": { label: "Cross-mission learning", category: "features" },
  "memory.attack_memory_enabled": { label: "Attack memory", category: "features" },
  "memory.embedding_model": { label: "Embedding model", category: "features" },
  "memory.attack_memory_max_context_chars": { label: "Attack memory max chars", category: "features", advanced: true },
  "memory.experience_min_samples": { label: "Experience min samples", category: "features", advanced: true },
  "memory.experience_time_decay_days": { label: "Experience decay (days)", category: "features", advanced: true },
  "plugins.enabled": { label: "Enabled plugins", category: "features" },
  "plugins.disabled": { label: "Disabled plugins", category: "features" },
  "plugins.search_paths": { label: "Plugin search paths", category: "features", advanced: true },
  "plugins.entry_points": { label: "Entry-point discovery", category: "features", advanced: true },
  "skills.enabled": { label: "Skills", category: "features" },
  "skills.max_active_skills": { label: "Max active skills", category: "features" },
  "skills.semantic_matching": { label: "Semantic matching", category: "features" },
  "skills.reselect_mid_run": { label: "Re-select mid-run", category: "features", advanced: true },
  "skills.feedback_enabled": { label: "Skill feedback", category: "features", advanced: true },
  "skills.allow_model_lookup": { label: "Allow model lookup", category: "features", advanced: true },
  "skills.inject_startup_context": { label: "Inject startup context", category: "features", advanced: true },
  "skills.max_chars_per_skill": { label: "Max chars per skill", category: "features", advanced: true },
  "skills.max_total_chars": { label: "Max total chars", category: "features", advanced: true },
  "skills.default_enabled": { label: "Default enabled skills", category: "features", advanced: true },
  "skills.include_tags": { label: "Include tags", category: "features", advanced: true },
  "skills.exclude_names": { label: "Exclude names", category: "features", advanced: true },
  "skills.maybe_enabled": { label: "Maybe enabled", category: "features", advanced: true },
  "skills.roots": { label: "Skill roots", category: "features", advanced: true },
  "skills.min_contextual_skills": { label: "Min contextual skills", category: "features", advanced: true },
  "skills.default_skill_weight": { label: "Default skill weight", category: "features", advanced: true },
  "skills.context_skill_weight": { label: "Context skill weight", category: "features", advanced: true },
  "skills.reselect_max_per_run": { label: "Max re-selections per run", category: "features", advanced: true },
  "skills.reselect_min_interval_actions": { label: "Min interval between re-selections", category: "features", advanced: true },
  "skills.reselect_sticky_defaults": { label: "Sticky defaults", category: "features", advanced: true },
  "skills.swarm_inject": { label: "Inject into swarm", category: "features", advanced: true },
  "skills.swarm_phase_hints_only": { label: "Swarm phase hints only", category: "features", advanced: true },
  "skills.feedback_skill_weight": { label: "Feedback skill weight", category: "features", advanced: true },
  "skills.feedback_min_observations": { label: "Feedback min observations", category: "features", advanced: true },
  "skills.semantic_skill_weight": { label: "Semantic skill weight", category: "features", advanced: true },
  "skills.semantic_min_similarity": { label: "Semantic min similarity", category: "features", advanced: true },
  "skills.semantic_model": { label: "Semantic model", category: "features", advanced: true },
  "skills.diversity_penalty": { label: "Diversity penalty", category: "features", advanced: true },
  "skills.include_metadata": { label: "Include metadata", category: "features", advanced: true },
  "skills.allow_reference_listing": { label: "Allow reference listing", category: "features", advanced: true },
  "swarm.enabled": { label: "Swarm", category: "features" },
  "swarm.max_parallel_agents": { label: "Max parallel agents", category: "features" },
  "swarm.parallel_enabled": { label: "Parallel swarm", category: "features" },
  "swarm.per_phase_concurrency": { label: "Per-phase concurrency", category: "features", advanced: true },
  "swarm.exploit_parallel": { label: "Parallel exploit agents", category: "features", advanced: true },
  "swarm.subagent_timeout_seconds": { label: "Subagent timeout (s)", category: "features", advanced: true },
  "swarm.negotiation_rounds": { label: "Critic negotiation rounds", category: "features", advanced: true },
  "swarm.agents": { label: "Agents", category: "features", advanced: true },
  "multi_model.enabled": { label: "Multi-model consult", category: "features" },
  "multi_model.consult_aliases": { label: "Consult aliases", category: "features" },
  "multi_model.max_consultations": { label: "Max consultations", category: "features", advanced: true },
  "multi_model.max_question_chars": { label: "Max question chars", category: "features", advanced: true },
  "multi_model.max_answer_chars": { label: "Max answer chars", category: "features", advanced: true },
  "adaptive_exploits.enabled": { label: "Adaptive exploits", category: "features" },
  "adaptive_exploits.max_mutations": { label: "Max mutations", category: "features", advanced: true },
  "adaptive_exploits.mutation_strategies": { label: "Mutation strategies", category: "features", advanced: true },
  "long_session.enabled": { label: "Long session", category: "features" },
  "long_session.request_timeout_seconds": { label: "Request timeout (s)", category: "features", advanced: true },
  "long_session.swarm_session_timeout_minutes": { label: "Swarm session timeout (min)", category: "features", advanced: true },
  "long_session.attack_max_rounds": { label: "Attack max rounds", category: "features", advanced: true },
  "long_session.attack_max_commands": { label: "Attack max commands", category: "features", advanced: true },
  "long_session.attack_max_duration_minutes": { label: "Attack max duration (min)", category: "features", advanced: true },
  "long_session.persist_messages": { label: "Persist messages", category: "features", advanced: true },
  "webhook_notify.enabled": { label: "Webhook notifications", category: "features" },
  "webhook_notify.url": { label: "Webhook URL", category: "features", secret: true },
  "webhook_notify.events": { label: "Events", category: "features", advanced: true },
  "webhook_notify.timeout_seconds": { label: "Timeout (s)", category: "features", advanced: true },
  "webhook_notify.max_retries": { label: "Max retries", category: "features", advanced: true },
  "webhook_notify.backoff_seconds": { label: "Backoff (s)", category: "features", advanced: true },
  "webhook_notify.max_payload_chars": { label: "Max payload chars", category: "features", advanced: true },
  "mitre.enabled": { label: "MITRE ATT&CK export", category: "features" },
  "mitre.technique_map": { label: "Technique map", category: "features", advanced: true },
  "mitre.navigator_output_dir": { label: "Navigator output dir", category: "features", advanced: true },
  "mitre.include_skill_tags": { label: "Include skill tags", category: "features", advanced: true },
  "ticketing.enabled": { label: "Remediation tickets", category: "features" },
  "ticketing.provider": { label: "Ticket provider", category: "features", advanced: true },
  "ticketing.base_url": { label: "Ticket base URL", category: "features", advanced: true },
  "ticketing.token_env": { label: "Ticket token env", category: "features", advanced: true },
  "ticketing.project_key": { label: "Project key", category: "features", advanced: true },
  "ticketing.max_retries": { label: "Max retries", category: "features", advanced: true },
  "ticketing.backoff_seconds": { label: "Backoff (s)", category: "features", advanced: true },
  "witness.enabled": { label: "Witness agent", category: "features" },
  "witness.log_path": { label: "Witness log path", category: "features", advanced: true },
  "witness.poll_interval_seconds": { label: "Poll interval (s)", category: "features", advanced: true },
  "witness.escalate_to_event_broker": { label: "Escalate to event broker", category: "features", advanced: true },
  "witness.max_flags_per_signal_per_minute": { label: "Max flags per signal/min", category: "features", advanced: true },
  "witness.dos_failure_window_seconds": { label: "DoS failure window (s)", category: "features", advanced: true },
  "witness.dos_failure_threshold": { label: "DoS failure threshold", category: "features", advanced: true },

  // ── Advanced ──────────────────────────────────────────────────────────────
  "exploit.enabled": { label: "Exploit engine", category: "advanced" },
  "exploit.permission": {
    label: "Exploit permission",
    description: "full_access auto-approves every action; read_only proposes only.",
    category: "advanced",
    options: ["read_only", "approve_only", "full_access"],
  },
  "exploit.attack_mode": { label: "Attack mode", category: "advanced" },
  "exploit.command_timeout_seconds": { label: "Command timeout (s)", category: "advanced" },
  "exploit.max_commands_per_session": { label: "Max commands per session", category: "advanced" },
  "exploit.max_rounds": { label: "Max rounds", category: "advanced" },
  "exploit.attack_max_commands": { label: "Attack max commands", category: "advanced" },
  "exploit.attack_max_rounds": { label: "Attack max rounds", category: "advanced" },
  "exploit.attack_max_duration_minutes": { label: "Attack max duration (min)", category: "advanced" },
  "exploit.require_explicit_allowlist": { label: "Require explicit allowlist", category: "advanced" },
  "exploit.allowed_targets": { label: "Allowed targets", category: "advanced" },
  "exploit.disallowed_assets": { label: "Disallowed assets", category: "advanced" },
  "exploit.forbidden_actions": { label: "Forbidden actions", category: "advanced" },
  "exploit.workspace_dir": { label: "Workspace dir", category: "advanced" },
  "exploit.shell": { label: "Shell", category: "advanced" },
  "exploit.msfconsole_path": { label: "msfconsole path", category: "advanced" },
  "exploit.attacker_os": { label: "Attacker OS", category: "advanced", options: ["auto", "linux", "windows"] },
  "exploit.max_pivot_depth": { label: "Max pivot depth", category: "advanced" },
  "exploit.auto_post_exploit": { label: "Auto post-exploit", category: "advanced" },
  "exploit.context_summarize_every": { label: "Context summarize every", category: "advanced" },
  "exploit.web_search": { label: "Web search", category: "advanced" },
  "exploit.max_query_chars": { label: "Max query chars", category: "advanced" },
  "exploit.cache_ttl_seconds": { label: "Cache TTL (s)", category: "advanced" },
  "exploit.cache_max_entries": { label: "Cache max entries", category: "advanced" },
  "exploit.terminal": { label: "Terminal", category: "advanced", options: ["visible", "hidden"] },
  "exploit.searchsploit_path": { label: "searchsploit path", category: "advanced" },
  "exploit.ad_kerberos": { label: "AD / Kerberos", category: "advanced" },
  "exploit.msf": { label: "Metasploit recipes", category: "advanced" },
  "exploit.listeners": { label: "C2 listeners", category: "advanced" },
  "cve_lookup.enabled": { label: "CVE lookup", category: "advanced" },
  "cve_lookup.max_results": { label: "Max results", category: "advanced" },
  "cve_lookup.rate_limit_seconds": { label: "Rate limit (s)", category: "advanced" },
  "cve_lookup.timeout_seconds": { label: "Timeout (s)", category: "advanced" },
  "cve_lookup.cache_ttl_seconds": { label: "Cache TTL (s)", category: "advanced" },
  "cve_lookup.cache_max_entries": { label: "Cache max entries", category: "advanced" },
  "cve_lookup.api_key_env": { label: "NVD API key env", category: "advanced" },
  "cve_lookup.circuit_failure_threshold": { label: "Circuit failure threshold", category: "advanced" },
  "cve_lookup.circuit_recovery_timeout": { label: "Circuit recovery timeout", category: "advanced" },
  "cve_lookup.search_rate_limit_per_minute": { label: "Search rate limit/min", category: "advanced" },
  "cve_lookup.epss_enabled": { label: "EPSS enrichment", category: "advanced" },
  "cve_lookup.kev_enabled": { label: "KEV enrichment", category: "advanced" },
  "cve_lookup.kev_cache_ttl_seconds": { label: "KEV cache TTL (s)", category: "advanced" },
  "cve_lookup.kev_cache_path": { label: "KEV cache path", category: "advanced" },
  "cve_lookup.github": { label: "GitHub", category: "advanced" },
  "threat_intel.enabled": { label: "Threat intel feed", category: "advanced" },
  "threat_intel.cache_dir": { label: "Cache dir", category: "advanced" },
  "threat_intel.cache_ttl_seconds": { label: "Cache TTL (s)", category: "advanced" },
  "threat_intel.sources": { label: "Sources", category: "advanced" },
  "threat_intel.max_results": { label: "Max results", category: "advanced" },
  "threat_intel.github_token_env": { label: "GitHub token env", category: "advanced" },
  "threat_intel.timeout_seconds": { label: "Timeout (s)", category: "advanced" },
  "research.enabled": { label: "Web research", category: "advanced" },
  "research.provider": { label: "Research provider", category: "advanced", options: ["ollama", "serpapi"] },
  "research.fallback_provider": { label: "Fallback provider", category: "advanced", options: ["ollama", "serpapi"] },
  "research.timeout_seconds": { label: "Timeout (s)", category: "advanced" },
  "research.max_results": { label: "Max results", category: "advanced" },
  "research.max_fetch_depth": { label: "Max fetch depth", category: "advanced" },
  "research.max_content_chars": { label: "Max content chars", category: "advanced" },
  "research.cache_ttl_seconds": { label: "Cache TTL (s)", category: "advanced" },
  "research.cache_max_entries": { label: "Cache max entries", category: "advanced" },
  "research.min_source_quality": { label: "Min source quality", category: "advanced", options: ["low", "medium", "high"] },
  "research.require_api_key_for_mcp_tools": { label: "Require API key for MCP tools", category: "advanced" },
  "research.allow_local_fetch": { label: "Allow local fetch", category: "advanced" },
  "research.ollama": { label: "Ollama research", category: "advanced" },
  "research.serpapi": { label: "SerpAPI", category: "advanced" },
  "research.assistant": { label: "Research assistant", category: "advanced" },
  "recon.extended_enumerators": { label: "Extended enumerators", category: "advanced" },
  "recon.udp_top_ports": { label: "UDP top ports", category: "advanced" },
  "recon.shodan_api_key": { label: "Shodan API key", category: "advanced", secret: true },
  "recon.subdomain_enum": { label: "Subdomain enumeration", category: "advanced" },
  "recon.vhost_discovery": { label: "Vhost discovery", category: "advanced" },
  "recon.waf_fingerprint": { label: "WAF fingerprinting", category: "advanced" },
  "recon.asn_whois": { label: "ASN / WHOIS", category: "advanced" },
  "recon.cloud_metadata_probe": { label: "Cloud metadata probe", category: "advanced" },
  "recon.snmp_enum": { label: "SNMP enumeration", category: "advanced" },
  "recon.dns_zone_transfer": { label: "DNS zone transfer", category: "advanced" },
  "opsec.enabled": { label: "OPSEC", category: "advanced" },
  "opsec.ua_rotation": { label: "User-Agent rotation", category: "advanced" },
  "opsec.doh": { label: "DNS over HTTPS", category: "advanced" },
  "opsec.doh_provider": { label: "DoH provider", category: "advanced", options: ["cloudflare", "google"] },
  "opsec.min_gap_seconds": { label: "Min gap (s)", category: "advanced" },
  "opsec.jitter_seconds": { label: "Jitter (s)", category: "advanced" },
  "opsec.rate_per_minute": { label: "Rate per minute", category: "advanced" },
  "opsec.quiet_command_patterns": { label: "Quiet command patterns", category: "advanced" },
  "opsec.noise_budget": { label: "Noise budget", category: "advanced" },
  "opsec.local_targets_off": { label: "Disable for local targets", category: "advanced" },
  "opsec.local_cidrs": { label: "Local CIDRs", category: "advanced" },
  "opsec.public_autonomy": { label: "Public target autonomy", category: "advanced" },
  "autonomous.persistence_phase": { label: "Persistence phase", category: "advanced" },
  "autonomous.checkpoint_every": { label: "Checkpoint every N targets", category: "advanced" },
  "autonomous.adaptive_replan": { label: "Adaptive replan", category: "advanced" },
  "autonomous.max_cycles": { label: "Max cycles", category: "advanced" },
  "autonomous.max_pivot_depth": { label: "Max pivot depth", category: "advanced" },
  "orchestrator.semantic_memory": { label: "Orchestrator semantic memory", category: "advanced" },
  "eval.enabled": { label: "Eval harness", category: "advanced" },
  "eval.output_dir": { label: "Eval output dir", category: "advanced" },
  "eval.max_rounds": { label: "Eval max rounds", category: "advanced" },
  "eval.write_markdown": { label: "Write markdown", category: "advanced" },
  "eval.write_html": { label: "Write HTML", category: "advanced" },
  "outcome_judgment.max_inconclusive_attempts": { label: "Max inconclusive attempts", category: "advanced" },
  "outcome_judgment.confirmation_threshold": { label: "Confirmation threshold", category: "advanced" },
  "outcome_judgment.refutation_threshold": { label: "Refutation threshold", category: "advanced" },
  "outcome_judgment.min_evidence_references": { label: "Min evidence references", category: "advanced" },
  "outcome_judgment.flow_a": { label: "Flow A outcome judging", category: "advanced" },
  "outcome_judgment.peer_review": { label: "Peer review judging", category: "advanced" },
  "poc_verification.enabled": { label: "PoC verification", category: "advanced" },
  "poc_verification.docker_image": { label: "Docker image", category: "advanced" },
  "poc_verification.compile_timeout_seconds": { label: "Compile timeout (s)", category: "advanced" },
  "poc_verification.max_retries": { label: "Max retries", category: "advanced" },
  "poc_verification.docker_network": { label: "Docker network", category: "advanced" },
  "poc_verification.docker_read_only": { label: "Docker read-only", category: "advanced" },
  "poc_verification.docker_memory": { label: "Docker memory", category: "advanced" },
  "replay_simulator.enabled": { label: "Replay simulator", category: "advanced" },
  "stealth.rotate_ua": { label: "Rotate User-Agent", category: "advanced" },
  "stealth.dns_over_https": { label: "DNS over HTTPS", category: "advanced" },
  "stealth.doh_provider": { label: "DoH provider", category: "advanced", options: ["cloudflare", "google"] },
};

export function getSettingMeta(section: string, field: string): SettingMeta | undefined {
  return SETTING_META[`${section}.${field}`];
}

export function getCategoryForSection(section: string): SettingCategory {
  return SECTION_CATEGORY[section] ?? "advanced";
}

/** Category a field renders in: its explicit meta category, else "advanced"
 *  (unknown properties surface under Advanced Configuration). */
export function fieldCategory(section: string, field: string): SettingCategory {
  return getSettingMeta(section, field)?.category ?? "advanced";
}

export function isKnownSetting(section: string, field: string): boolean {
  return !!getSettingMeta(section, field);
}

export function sectionLabel(section: string): string {
  return SECTION_LABELS[section] ?? section;
}
