"""Generate docs/generated/source-map.md from imports/shims (TODO 020).

AST/import scan listing public import -> canonical implementation ->
compatibility status -> removal version. New contributors never guess.

Usage:
    python scripts/generate_source_map.py [--check]
"""

from __future__ import annotations

import argparse
import ast
import datetime
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "docs" / "generated" / "source-map.md"


def _read_version_warning(path: Path) -> str:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return ""
    m = re.search(r"remove in (0\.\d+)", text)
    return m.group(1) if m else ""


def collect() -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    # Root shims: `import X` -> legacy.X
    for py in sorted(REPO.glob("*.py")):
        if py.name.startswith((".", "_")):
            continue
        try:
            text = py.read_text(encoding="utf-8")
        except OSError:
            continue
        m = re.search(r'import_module\("legacy\.(\w+)"\)', text)
        if m:
            ver = _read_version_warning(py) or "0.71"
            rows.append(
                {
                    "public": py.stem,
                    "canonical": f"legacy.{m.group(1)}",
                    "status": "Deprecated shim",
                    "removal": f"remove in {ver}",
                }
            )
    # Facades (canonical, not deprecated).
    facades = [
        ("tools.autonomous_orchestrator", "tools.campaign.*", "Facade (canonical)"),
        ("tools.config_manager", "tools.config.*", "Re-export shim (canonical)"),
        ("tools.mcp_tools.registry", "tools.mcp_tools.*", "Central wiring (canonical)"),
        ("tools.kernel.action_result", "tools.exploit_agent.outcome_truth", "Canonical outcome contract"),
        ("tools.kernel.run_manifest", "tools/run_service/*", "Canonical run index"),
    ]
    for public, canonical, status in facades:
        rows.append({"public": public, "canonical": canonical, "status": status, "removal": "n/a"})
    # tools/kernel strict-tier pilot (new development target).
    kernel = REPO / "tools" / "kernel"
    if kernel.is_dir():
        for py in sorted(kernel.glob("*.py")):
            if py.name == "__init__.py":
                continue
            rows.append(
                {
                    "public": f"tools.kernel.{py.stem}",
                    "canonical": f"tools.kernel.{py.stem}",
                    "status": "Strict-tier canonical (new code here)",
                    "removal": "n/a",
                }
            )
    # Target namespace plan.
    rows.append(
        {
            "public": "breachpilot.* (planned)",
            "canonical": "tools/* + legacy/* (current)",
            "status": "Migration planned, phased after 0.69 freeze",
            "removal": "py-modules shrinks per release",
        }
    )
    return rows


def render(rows: list[dict[str, str]]) -> str:
    today = datetime.date.today().isoformat()
    lines = [
        "---",
        "title: Source Map (Generated)",
        "source: scripts/generate_source_map.py (AST/import scan)",
        f"generated: {today}",
        "---",
        "",
        "# Source Map (Generated)",
        "",
        "> Auto-generated by `scripts/generate_source_map.py` — do not edit by hand. "
        f"Public import → canonical implementation → status → removal ({today}). "
        "Target layout: real `breachpilot.*` namespace for new development "
        "(phased after 0.69; pilot: `tools/kernel` strict-tier).",
        "",
        "| Public import | Canonical | Status | Removal |",
        "|---|---|---|---|",
    ]
    for r in rows:
        lines.append(f"| `{r['public']}` | `{r['canonical']}` | {r['status']} | {r['removal']} |")
    lines += [
        "",
        "## Migration phases",
        "",
        "1. 0.69 freeze: plan only, no big-bang rename.",
        "2. After freeze: one package at a time (`tools/kernel` first).",
        "3. Keep one-release compat imports; shrink `pyproject.toml py-modules` per release.",
        "",
    ]
    # Validate syntax of scanned files (AST parse must succeed).
    _ = ast
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    rows = collect()
    text = render(rows)
    if args.check:
        try:
            committed = OUT.read_text(encoding="utf-8")
        except OSError as exc:
            print(f"source-map missing: {exc}", file=sys.stderr)
            return 1

        # Freshness: same row set (ignore date-stamps, which change daily).
        def _norm(s: str) -> str:
            s = re.sub(r"\d{4}-\d{2}-\d{2}", "DATE", s)
            return "\n".join(line for line in s.splitlines() if not line.startswith("generated:"))

        if _norm(committed) != _norm(text):
            print("source-map drift: run python scripts/generate_source_map.py", file=sys.stderr)
            return 1
        print(f"source-map fresh: {len(rows)} rows")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
