"""Generate docs/generated/safety-defaults.md from CONFIG_SCHEMA sandbox defaults.

Single source of truth for fail-closed sandbox defaults. CI / release gate
asserts schema + config.yaml + docs agreement; this file is the generated
table that docs link to instead of hand-maintaining default values.

Usage (from repo root):
    python scripts/generate_safety_defaults.py
"""

from __future__ import annotations

import argparse
import datetime
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from tools.config.schema import CONFIG_SCHEMA  # noqa: E402

DOC = REPO / "docs" / "generated" / "safety-defaults.md"


def render(today: str) -> str:
    sandbox = CONFIG_SCHEMA.get("sandbox", {})
    out = [
        "---",
        "title: Safety Defaults (Generated)",
        "description: Canonical fail-closed sandbox defaults from CONFIG_SCHEMA.",
        "source: tools/config/schema.py CONFIG_SCHEMA[sandbox]",
        f"generated: {today}",
        "---",
        "",
        "# Safety Defaults (Generated)",
        "",
        "> Auto-generated by `scripts/generate_safety_defaults.py` — do not edit by hand. "
        f"Source: `tools/config/schema.py` CONFIG_SCHEMA[sandbox] as of {today}.",
        "",
        "Fail-closed contract: `sandbox.enabled: true` with "
        f"`sandbox.fallback_native: {str(sandbox.get('fallback_native')).lower()}` "
        "(default, fail-closed). Explicit opt-in `fallback_native: true` degrades "
        "the whole server to legacy uncontained host-execution at boot with a "
        "warning — never a per-command fallback. See `docs/sandbox.md`.",
        "",
        "## Sandbox defaults",
        "",
        "| Key | Default | Meaning |",
        "|-----|---------|---------|",
    ]
    # Top-level sandbox scalars first, in stable order.
    for key in ("enabled", "backend", "image", "user", "read_only_rootfs", "fallback_native"):
        if key in sandbox:
            out.append(f"| `sandbox.{key}` | `{str(sandbox[key])}` | fail-closed default |")
    for key in ("auto_manage_docker", "docker_start_timeout_seconds", "docker_stop_timeout_seconds", "multi_net_raw"):
        if key in sandbox:
            out.append(f"| `sandbox.{key}` | `{str(sandbox[key])}` | see `docs/sandbox.md` |")
    network = sandbox.get("network", {}) or {}
    for key in ("enforce", "fail_closed", "allow_dns", "map_host_loopback", "allow_gateway", "allow_research_hosts"):
        if key in network:
            out.append(f"| `sandbox.network.{key}` | `{str(network[key])}` | containment default |")
    out += [
        "",
        "## Verification",
        "",
        "- `python scripts/release_gate.py` (`safety-defaults` box)",
        "- `pytest tests/test_config_semantic_truth.py -n 0`",
        "",
    ]
    return "\n".join(out)


def _normalized(text: str) -> str:
    """Date-stamps are metadata: normalize them so --check tracks content drift.

    Without this the check fails every day after generation day even when
    nothing changed, training the team to ignore it.
    """
    return re.sub(r"\d{4}-\d{2}-\d{2}", "DATE", text)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate safety-defaults.md from CONFIG_SCHEMA sandbox defaults.")
    parser.add_argument(
        "--check", action="store_true", help="fail (exit 1) when the checked-in file drifts; do not write"
    )
    args = parser.parse_args(argv)
    today = datetime.date.today().isoformat()
    text = render(today)
    if args.check:
        if _normalized(DOC.read_text(encoding="utf-8")) != _normalized(text):
            print("safety-defaults drift: run python scripts/generate_safety_defaults.py", file=sys.stderr)
            return 1
        print(f"safety-defaults fresh: date={today}")
        return 0
    DOC.parent.mkdir(parents=True, exist_ok=True)
    DOC.write_text(text, encoding="utf-8")
    print(f"wrote {DOC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
